### ISSUE TITLE
renewAuth returns null.

### ISSUE THREAD

**Issue by David-Molloy** [auth0/Auth0.Android#101]
Hi.

The version I am using is 'com.auth0.android:lock:2.5.0'. I am logging in successfully using the Lock UI, but later when I try to refresh the token it is returning a null value.

Logging in:
accessToken: aBm3tb2DYBRpjb6l
refreshToken: REDACTED

After running the renewAuth(refreshToken) I am always getting back null?
accessToken: null
refreshToken: null

**Comment by cocojoe** [comment]
Please do not paste your `refreshToken` value, I have removed it. I suggest you revoke that `refreshToken` from your `User / Devices` in the Auth0 dashboard.  Best to be on the safe side :)

**Comment by David-Molloy** [comment]
It's a testing/throw away account, but I will revoke to be on the safe side.

**Comment by lbalmaceda** [comment]
@David-Molloy I can't reproduce it with that version. I'm logging in asking for `openid offline_access` scope and then use the *refresh_token* I get to call `renewAuth({refresh_token})` on an AuthenticationAPIClient instance, and get back fresh *access_token* and *id_token*. 

I suggest you check our docs or submit a ticket with more details in https://support.auth0.com
