### ISSUE TITLE
Proposal: CredentialsManager.getCredentials() should save renewed Credentials

### ISSUE THREAD

**Issue by psam44** [auth0/Auth0.Android#109]
CredentialsManager.getCredentials() is able to renew expired credentials and that is valuable. But this renewal is not persisted, so every time getCredentials() is called there is a network hit if the currently stored item has expired. Furthermore:

- getCredentials() doesn't say if the returned item is from the storage or a renewed one.
- hasValidCredentials() doesn't tell the difference neither.

So the only way I found for now would be to use an other storage unit to keep the last ExpiresAt for comparison with the returned credentials and in case of progression to do a saveCredentials().
I would prefer this process be done by the CredentialsManager.

Something like:
```
            @Override
            public void onSuccess(Credentials freshCredentials) {
/* + */         CredentialsManager.this.saveCredentials(freshCredentials);
                callback.onSuccess(freshCredentials);
            }
```

[Edit 28 Aug]
I discovered another issue with the call to `renewAuth(refreshToken)`, which may introduce an infeasibility:
My freshCredentials has these unexpected properties:
`getIdToken()` is null.
`getRefreshToken()` is null.
`getExpiresIn()` is 86400, i.e. 24 hours ; I don't know where it comes from.

These ones seem correct:
`getAccessToken()` is a 16 chars string.
`getType()` is "Bearer".
`getScope()` is null.

Note: I also made a trial with my own duplicate of this part of source, to insert `.addParameter("scope", "openid offline_access")` before `.start()` and the result is the same.

My setting is `setOIDCConformant(true)`.
The initial credentials comes from react-native-lock 0.6.1, with Lock 1.17.+, so the endpoints are /oauth/ro and /tokeninfo. The requested scope is the default one, i.e. "openid offline_access".
Is it possible that this refreshToken is not suitable for the oauth/token endpoint?

**Comment by lbalmaceda** [comment]
The save credentials feature is currently being added here https://github.com/auth0/Auth0.Android/pull/118.

When renewing credentials using the refresh_token, you won't receive a new refresh_token because the old one is still valid 😄 , so that's OK. But that thing you mention about the id_token being null is a little weird. Could you please share the snippets on how you're 1) initializing the Auth0, 2) the AuthenticationAPIClient and 3) making the requests?

**Comment by psam44** [comment]
Initial acquisition:
```javascript
import Auth0Lock from 'react-native-lock';
import credentials from './auth0-credentials';
const lock: Auth0Lock = new Auth0Lock(credentials);
//...
      lock.show({
        closable: true,
        disableSignUp: true,
        disableResetPassword: true,
      }, (err, profile, token) => {
        this.props.onLogin(err, {profile, token});
      });
```
Logs:
```
D/com.auth0.api.authentication.AuthenticationAPIClient: Trying to login using https://[...].eu.auth0.com/oauth/ro with parameters
 {device=Nexus 6, scope=openid offline_access, client_id=[...], connection=Username-Password-Authentication}
D/com.auth0.api.internal.SimpleRequest: Received response from request to https://[...].eu.auth0.com/oauth/ro with status code 200
D/com.auth0.api.internal.SimpleRequest: Received successful response from https://[...].eu.auth0.com/oauth/ro
D/com.auth0.api.internal.SimpleRequest: Received response from request to https://[...].eu.auth0.com/tokeninfo with status code 200
D/com.auth0.api.internal.SimpleRequest: Received successful response from https://[...].eu.auth0.com/tokeninfo
```
1) initializing the Auth0
2) the AuthenticationAPIClient

```java
final Auth0 account = new Auth0(context);
account.setOIDCConformant(true);
final AuthenticationAPIClient authentication = new AuthenticationAPIClient(account);
final Storage storage = new SharedPreferencesStorage(context);
sCredentialsManager = new CredentialsManager(authentication, storage);
```
3) making the requests

```java
sCredentialsManager.getCredentials(new BaseCallback<Credentials, CredentialsManagerException>(){
	public void onSuccess(Credentials credentials) {
		final String idToken = credentials.getIdToken();
		if (idToken != null) /* ok, additional code with idToken */;
		else {
			Log.e(TAG, "Unexpected null idToken");
		}
	});
}
```

**Comment by lbalmaceda** [comment]
Ah sorry, yes. You shouldn't be mixing the tokens obtained in /oauth/ro (v1) with /oauth/token. AFAIK v1 doesn't support OIDC endpoints and that's what RNLock is using behind the scenes. Either implement your own UI with [RNAuth0](https://github.com/auth0/react-native-auth0) using oidc=true there and in the Auth0.Android client (I recommend this); or use the v1 token with oidc=false on Auth0.Android, which will use /delegation to exchange a given refresh_token for a valid id_token. If this doesn't happen please ping me again here so I can try to reproduce it and check if it's a bug on the sdk side.
Further reading on [delegation deprecation](https://auth0.com/docs/api-auth/tutorials/adoption/delegation)

**Comment by psam44** [comment]
@lbalmaceda 
I confirm your last doubt: if I set `account.setOIDCConformant(true);`, /delegation should be used (there is no trace in logcat to be sure) but every `.getCredentials()` ends on `onFailure()` with `error.getMessage()` as: `An error occurred while trying to use the Refresh Token to renew the Credentials.`
