### ISSUE TITLE
Cannot minimize application with opened Chrome Tabs

### ISSUE THREAD

**Issue by MikolajKakol** [auth0/Auth0.Android#116]
If during login process user minimize application and restore it we will get an error in `AuthCallback.onFailure(AuthenticationException)` method with

> exception = {AuthenticationException@4900} "com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server."
>  code = "invalid_request"
>  description = "Missing required parameter: code"
>  statusCode = 0
>  values = {HashMap@4908}  size = 2
>   0 = {HashMap$HashMapEntry@4917} "error" -> "invalid_request"
>   1 = {HashMap$HashMapEntry@4918} "error_description" -> "Missing required parameter: code"
>  backtrace = {Object[10]@4909} 
>  cause = {AuthenticationException@4900} "com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server."
>  detailMessage = "An error occurred when trying to authenticate with the server."

it's important for us to handle those situations correctly because if you are trying to log in with mobile using Norwegian BankID user is prompt with system Acitivty (launched from USSD code I think) in which user must enter some number and when it's closed I'm getting that error.

It's easily to reproduce in sample 00-login. Just click "show log in" then minimize app and restore.

**Comment by lbalmaceda** [comment]
@MikolajKakol This should be fixed in the latest patch. Please try `1.10.1` and reopen if necessary.
