### ISSUE TITLE
Auth0Exception and SocketTimeoutException when calling renewAuth not OIDC Conformant

### ISSUE THREAD

**Issue by endy-s** [auth0/Auth0.Android#123]
I'm the developer of an app that is available at the Play Store and I received some crash reports that I couldn't reproduce, all related to the renewAuth method.

The app uses the idToken to perform requests to our own back-end and the accessToken to authenticate with Auth0. Having that in mind, sometimes I need to refresh both tokens.

To refresh the accessToken I call the renewAuth with OIDC Conformant set to true, the request returns as a success and I save the refreshed token. 
Then, when I refresh the idToken performing a request to renewAuth without setting OIDC Conformant (false as default), it worked as expected in my tests and uses, but some users received an AuthenticationException or SocketTimeoutException.

I created gists with the Stack Traces of both exceptions, [here for AuthenticationException](https://gist.github.com/endy-s/2f257e99f36ee986c528c8d0cc1a2f80) and [here for SocketTimeoutException](https://gist.github.com/endy-s/94f0e735e620fbebc0e8e39762080888).

This is the link for the app in the play store: https://play.google.com/store/apps/details?id=org.singularityu.suhub.android

I understand that the SocketTimeoutException probably is caused by a bad network connection, but should this performs a crash?

The AuthenticationException I don't have idea why it happen.

Any help with theses crashes will be very appreciated 🙂

**Comment by lbalmaceda** [comment]
I think you're mixing up concepts between the legacy and OIDC endpoints. At first, I'd recommend you to use OIDC conformant endpoints. Turning ON that setting on the client dashboard will help you to not make mistakes. Make sure to call `auth0.setOIDCConformant(true)` on the Auth0 instance that you pass to the AuthenticationAPIClient as well. 

When you log in using any of your connections requesting `scope=openid offline_access` (at least) a refresh_token is also returned. I guess you are also requesting the  `response_type=code id_token` to get the id_token back. Now you have access_token, id_token and refresh_token, and you use them as needed. At some point, both the access_token and id_token expire. To refresh them using the refresh_token, you will call the renewAuth method which requires a REFRESH_TOKEN and returns new access_token and id_token (if response_type included it). You must keep the first refresh_token as you'll not get another one on this call, and of course, the previous one is still valid. Per the logs attached, I see that you're calling `/delegation` (I guess to "refresh the id_token") which shouldn't be needed at all.
Cheers.

**Comment by endy-s** [comment]
Thanks for your quick answer!

About turning ON the OIDC Conformant setting, older versions of the app perform this requests without calling `auth0.setOIDCConformant(true)`, this change of settings make older versions stop working, right?

When I log in I'm requesting `scope=openid profile offline_access`, getting the three tokens (access, id and refresh) as expected, but I don't use the `response_type` in any request. Tested including this parameter over here, but had no success... Maybe because of the Conformant setting?

When I need to refresh the tokens, I call the renewAuth with the REFRESH_TOKEN, but it only returns me ONE token. And you're right about the call to `/delegation`.

If I set the `Conformant true`, I receive the `access token`.
If I let the `Conformant false`, I receive the `id token`.

And the crashes only happens when I'm with the `Conformant false`.

Looking forward to keep investigating this.

**Comment by endy-s** [comment]
Good to know, will keep the dashboard setting as it is.

- If I try to perform a login with `auth0.setOIDCConformant(true)`, the requests for our back-end is getting **error 500**.

- If I try to set the `response_type=code id_token` in my requests (login and refresh), the `renewAuth` still gives me only one token (with OIDC Conformant true).

Since the exceptions was caught because of the call to `renewAuth with Conformant false`, the second approach still doesn't fix my problem :(

Will check the error 500 with the BE devs tomorrow ASAP, but if you have another idea/suggestion it would be great!

**Comment by lbalmaceda** [comment]
Changing from legacy to OIDC is not a simple thing, that's why I said you need to "make the necessary changes to keep what you have today working". The content or format of the responses will differ from what you had before because the endpoints change, and you'll have to update the code in every platform to reflect that. I suggest you check the [OIDC adoption docs](https://auth0.com/docs/api-auth/tutorials/adoption) to get into the concepts. If you're using your own back-end you'll probably want to [setup a new Auth0 API](https://auth0.com/docs/apis) and request that audience when logging in on the mobile app, so later you can check that value in your back-end before actually using the tokens. 

If you find an SDK issue feel free to open the ticket again. You'll have to check https://support.auth0.com/ or https://community.auth0.com/ as this is not our official support channel and we just use it to keep track of SDK specifics.
