### ISSUE TITLE
Using AppCompat v25.3.1

### ISSUE THREAD

**Issue by asinel** [auth0/Auth0.Android#125]
Why do you use AppCompat v25.3.1, not the new ones? Gradle shows an error:
<img width="1183" alt="screen shot 2017-10-26 at 18 57 18" src="https://user-images.githubusercontent.com/11772185/32066270-857d7eec-ba7f-11e7-9227-77159e69fa7f.png">

**Comment by lbalmaceda** [comment]
We use `compileSdkVersion` and `targetSdkVersion` 25, so until we don't bump it the support libraries major must be that one. 
To solve the error you attached you'll have to either use the one we use or [deal](https://stackoverflow.com/a/20016971) with transitive dependencies.
