### ISSUE TITLE
Support TLSv1.2 on older Android API

### ISSUE THREAD

**Issue by carlyonj** [auth0/Auth0.Android#126]
Auth0 supports down to API 15 but as detailed [here](https://github.com/ssllabs/ssllabs-scan/issues/258) TLSv1.1 and v1.2 are not used by default on older APIs. Potential solutions are detailed [here](https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1), [here](https://github.com/square/okhttp/issues/2372) and [here](https://stackoverflow.com/questions/28329652/enabling-specific-ssl-protocols-with-android-webviewclient).

Currently by using the Auth0 API you are unable to support devices using APIs lower than 21 with a backend that enforced TLSv1.2. Because of this the Auth0 android library is not very useful to any apps that plan on supporting older devices in a secure manner.

**Comment by lbalmaceda** [comment]
I would prefer a method that sets a flag rather than exposing the OkHttp client. Maybe in the Auth0 class, or in both API client classes. This is not a priority for us.. Feel free to fork the repo and add the required changes or propose a PR and I'll review it when I can.

**Comment by dj-mal** [comment]
PR Submitted as #128

**Comment by lbalmaceda** [comment]
This has been released on version 1.12.0. Thanks
