### ISSUE TITLE
Incomplete Management API

### ISSUE THREAD

**Issue by borice** [auth0/Auth0.Android#129]
The SDK implements only a small portion of the Management API features. 
It would be great if it implemented the entire set of calls in order to be really usable.

**Comment by lbalmaceda** [comment]
Hey! What's your use case? We don't implement the full Management API as most of the endpoints are meant to be called from a secure client (like your backend) using a library like [this one](https://github.com/auth0/auth0-java).

**Comment by borice** [comment]
Was looking for an API to rename a user account. 
I understand that this sort of stuff is better done via the backend, which makes sense.
