### ISSUE TITLE
Mismatch between `Client Quick Settings` instruction and ReadMe on Auth0.Android

### ISSUE THREAD

**Issue by toantran-ea** [auth0/Auth0.Android#134]
Hello Auth0, 

Thanks for your support on Android.
On setting up the client for Android (Native app), I found there is something not synced between the  Client Quick Start guide (see attached image) 
![screen shot 2017-12-08 at 5 16 21 pm](https://user-images.githubusercontent.com/8085722/33761452-a23e5ef6-dc3b-11e7-94e8-88b439aa4954.png)

and the guide on ReadMe of this project.

In details,

The Quick Start guide asks us to prepare 2 string resources value:

```xml
<resources>
    <string name="com_auth0_client_id">my-client-id</string>
    <string name="com_auth0_domain">my-domain.auth0.com</string>
</resources>
```
Then, if we add the follow code snippet into app.gradle to add Manifest placeholder:

```Maven
  manifestPlaceholders = [auth0Domain: "@string/auth0_domain", auth0Scheme: "https"]
```
And compile the project, we will get the following error:

![screen shot 2017-12-08 at 5 20 36 pm](https://user-images.githubusercontent.com/8085722/33761578-24c8eddc-dc3c-11e7-8582-73ce8aa9361f.png)

### Fix work for me
I change the string resource names into:

```xml
 <string name="auth0_client_id">my-id</string>
 <string name="auth0_domain">my-domain.auth0.com</string>
```
Now, project can be build and run successfully

**Comment by lbalmaceda** [comment]
Hey! I don't know where you've read that. I've checked the [Login Sample](https://github.com/auth0-samples/auth0-android-sample/blob/master/00-Login/app/build.gradle#L12) and the Login Quickstart where you [add the strings](https://auth0.com/docs/quickstart/native/android/getting-started#set-credentials) and [add the placeholders](https://auth0.com/docs/quickstart/native/android/00-login#add-auth0-to-gradle) and it's using the `com_auth0_*` names. Please point us to the document so we can fix it. 👍 

To clarify, the `com_auth0_*` naming is required if you're using the `new Auth0(context)` constructor, as [that requires](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L74) those values. But if you're using the explicit version where you pass both values to the constructor, then you can name it how you want it. 🎉

**Comment by toantran-ea** [comment]
Hi @lbalmaceda 
Thanks for your quick response, please find the image attached the guide in README I have read and followed.

<img width="1409" alt="screenshot 2017-12-08 22 42 10" src="https://user-images.githubusercontent.com/8085722/33773079-56ee287c-dc69-11e7-8e44-cd1fe0789413.png">

If that is only the mismatched in the document then updating the placeHolder's template is good to continue with the rest of my project. Thanks again!
