### ISSUE TITLE
Can't logout from Webclient

### ISSUE THREAD

**Issue by zfort-vitalii** [auth0/Auth0.Android#135]
Hello, 
i use this code to start auth process : 
```
auth0 = Utils.getAuth0();
        WebAuthProvider.init(auth0)
                .withScheme(getString(R.string.scheme))
                .start(this, callback);
```
    And login/registration flow works perfectly. 

When try to logout - i can't find any way to do this. 
Tried to save and clear with 
` credentialsManager.clearCredentials();`
Yes, i know that i need to login in this way. But when i open WebAuthProvider again - it automatically login me to the app. 

Used just email/password auth.
SDK version 'com.auth0.android:auth0:1.12.0'

Thanks for help.

**Comment by cocojoe** [comment]
@zfort-vitalii You can force a fresh login if you specify the key `prompt` and value `login. You can add this using `withParameters`

**Comment by zfort-vitalii** [comment]
@cocojoe works like a charm! Thanks!

**Comment by Viked** [comment]
@cocojoe This solution is not working, how can I logout?

**Comment by iancboswell** [comment]
Thanks for this solution. It would be very helpful if it were documented somewhere. The absence of built-in logout functionality is a little rough.

**Comment by lbalmaceda** [comment]
@iancboswell I agree that the logout is not straight forward in this cases. Note the authentication endpoints are OpenID Connect conformant. The `prompt` parameter is documented here https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest.

**Comment by iancboswell** [comment]
Ah, gotcha! Thanks!
