### ISSUE TITLE
State doesn't match when activity that launched the login page is destroyed

### ISSUE THREAD

**Issue by mitsest** [auth0/Auth0.Android#139]
Steps to reproduce:
Turn on "Don't keep activities" on developer options
Launch auth0 login page

Result:
```
Received state doesn't match. Received mwSJ2GrYEwcYQWL98G-mqw6TbeEOxKJLyjNmpWrSYH8 but expected Yp-KOXEv6too8d2kYi-mfO-fVIKvtmoCxGgOe_EQylQ
```
Is this expected?
Any workarounds?

Thanks

**Comment by lbalmaceda** [comment]
That's weird as the whole state of the authentication is supposed to be kept. I've tried with the [Lock](https://github.com/auth0/lock.android) sample app and I can't reproduce it. I have the "Don't keep activities" setting turned ON and I'm using Firefox browser, although the browser app shouldn't matter...
There seems to be an issue in the sample that prevents the authentication result from being shown. I've edited the `DemoActivity#showResult` method like this:

```java
private void showResult(final String message) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(DemoActivity.this, message, Toast.LENGTH_LONG).show();
            }
        });
    }
```

After running the app I can successfully login. -> GIF: http://g.recordit.co/D6fXtpDinY.gif

**Comment by mitsest** [comment]
I 'm using com.auth0.android:auth0:1.12.0 targeting 27.
My configuration is the bare minimum described in the offiical website. No intents in manifest,xml and strings.xml instead of constructor arguments

I could try with 'com.auth0.android:lock:2.8.0' and see if the problem persistis.

**Comment by lbalmaceda** [comment]
Lock has a sample app with a "Web Login" button on the bottom of the activity (the one shown in the GIF above). This web authentication is performed using only the `Auth0.Android` library. If you **clone** the Lock.Android repo you should be able to run this sample as I did, just for the sake of testing this issue. There's no need for you to change the dependency to Lock instead of Auth0. 👍

**Comment by mitsest** [comment]
You were right, it did work with the sample app/.
I'll investigate more.

Thanks for your time

**Comment by mitsest** [comment]
The issue was that I initialized the hosted login page without user action.

As soon as I created a button to initialize the page onClick, the login process finished even with a killed activity.

My understanding is that this is implemented this way for security reasons.
Am I right to assume this?

If I don't want a button, do I have to do something else?

Thanks

**Comment by mitsest** [comment]
So the issue was that when the activity was recreated it tried to redisplay the login page.
I solved it by updating a boolean (loginInitiated) that I save onSaveInstanceState.

Sorry for the fuss and thanks again

**Comment by lbalmaceda** [comment]
Glad you solved it!! Cheers
