### ISSUE TITLE
NPE in AuthenticationException

### ISSUE THREAD

**Issue by sebastian-heinz** [auth0/Auth0.Android#149]
Hello,

In our crashlytics logs some users are getting an NPE.
It starts by having a null `mapPayload` from the gson parsing here:
https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.java#L137

And the crash happens when creating a new HashMap from a null-object here:
https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.java#L76

This is the log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
       at java.util.HashMap.(HashMap.java:253)
       at com.auth0.android.authentication.AuthenticationException.(AuthenticationException.java:76)
       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:23)
       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:9)
       at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:137)
       at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:68)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

Would it make sense to guard against it in such a way?:
```
    public AuthenticationException(Map<String, Object> values) {
        this(DEFAULT_MESSAGE);
        if(values == null) {
                  this.code = UNKNOWN_ERROR;
                  return;
        }
        this.values = new HashMap<>(values);
        ....
```

Please let me know your thoughts and how this could be resolved,
Thanks alot!

Edit: I noticed there was a similar issue before (https://github.com/auth0/Auth0.Android/issues/137). Is this somehow related?

**Comment by lbalmaceda** [comment]
👋 No, the issue you mentioned in the end is not related. That's weird, you shouldn't be receiving a `null` payload unless something had changed on the server side. Can you please share more details, such as which was the endpoint involved and how you called it?

**Comment by sebastian-heinz** [comment]
I only saw this in other logs, so I really don't know what happened here. Judging from the flow and that there is no `JsonSyntaxException` the server must have responded with something that could be parsed to an `null`-object. 

As a server might not be always reliable do you think it makes sense to implement a guard condition at any point in the chain to stop the NPE ?

**Comment by lbalmaceda** [comment]
Server IS always reliable. There's an [API definition](https://auth0.com/docs/api/authentication) that this library is based on. What I meant in my previous comment is that there _might_ be some new undocumented error that the server returns and this library is not handling. In that case, the only way to handle it is to know what the payload looks like, so without those details I can't add it.

This error you are reporting is happening after an unsuccessful response, meaning the request failed for some reason. The parser you pointed out in the links first extracts the raw body string , and then tries to convert it from a JSON object to a Map. If that fails, it sticks to the raw string value and creates the exception with that. Note in the API docs I shared that the errors can be either plaintext or JSON, hence that logic. 

That said the only thing I can imagine that can be messing with the error format is if you have a custom [Rule](https://manage.auth0.com/#/rules) returning as error an exception with an unsupported format.

**Comment by lbalmaceda** [comment]
I'll close this due to inactivity. Feel free to re open it when you have confirmation of the issue.
