### ISSUE TITLE
Missing required parameter: code

### ISSUE THREAD

**Issue by iancboswell** [auth0/Auth0.Android#166]
I'm getting an AuthenticationException in my app after following your instructions to create a boilerplate authorization flow. Strangely, I got the sample app working with the same client ID and domain. With my own app, I have it set up the exact same way (as far as I can tell -- I even tried copying and pasting the Activity from the sample app, with no luck), but it fails after redirecting back to the app (after the Auth0 login page). The Auth0 logs claim I'm using development keys to connect when I try with my own app (I'm not, as far as I'm aware). Any idea what's going on here? I've followed all instructions in the README, and double-checked my client ID/domain and callback URL. I've tried to break the sample app by including all the Gradle dependencies that exist in my app.

**Comment by lbalmaceda** [comment]
No worries, it might be a configuration error (maybe on the manifest or `build.gradle` files). Please link to the instructions you're following to achieve this on your app.

**Comment by iancboswell** [comment]
Thanks for the quick reply! I'm following the instructions in the README in this repo (the simple way, not implementing a custom RedirectActivity). I have the `manifestPlaceholders` set up as specified in `build.gradle`. My `minSdkVersion` is 21, `targetSdkVersion` is 25, `compileSdkVersion` is 25, and `buildToolsVersion` is '27.0.3'. Of note, my app also uses Google Play Services, and I have a `google-services.json` in my `app` directory (see [https://developers.google.com/android/guides/google-services-plugin](here) for reference). There are some OAuth parameters there; could those be accidentally used instead of the Auth0 credentials in the `manifestPlaceholders`?

**Comment by lbalmaceda** [comment]
No, those shouldn't be conflicting at all with this SDK, but I'll leave you a note on this on the bottom just to be safe. 

So if you're following [web authentication](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) make sure to:

1.  setup [OIDC conformant](https://github.com/auth0/Auth0.Android#oidc-conformant-mode) mode 
2. add the [manifest placeholders](https://github.com/auth0/Auth0.Android#authentication-with-universal-login). This one you said it was OK, but see if you're using `https` as scheme you might want to switch at least for this test to a custom scheme, such as `demo`.
3. If you changed the scheme above, when you call `WebAuthProvider.init(account)` you will need to set the custom scheme as well `withScheme("demo")` before calling start as noted [here](https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking) ;)

Lastly, read how the code flow works [here](https://auth0.com/docs/api-auth/grant/authorization-code-pkce) and note that after the authentication is successful in our Universal Login Page, the `code` param will be given back to the app for it to be exchanged. Your application's [dashboard](https://manage.auth0.com/#applications) must be set to a `Native` type and have the Callback URL whitelisted matching the one defined in the intent-filter configuration. i.e.`{scheme}://{tenant}.auth0.com/android/{app-package}/callback`. You can check the actual value in the URL that gets open in the browser.


A note regarding other libraries. Maybe the gradle plugin is deciding a different manifest merge order and messes with the auto defined intent-filter (the one that makes use of the `manifestPlaceholders`). See if the above doesn't work, you can try manually defining the intent-filter, overriding the one defined by this SDK. To do so, follow the steps under [this section](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) where it names the `RedirectActivity`.

Cheers

**Comment by iancboswell** [comment]
Declaring `RedirectActivity` in my Manifest fixed it! Thanks so much for your help.
