### ISSUE TITLE
Make manifestPlaceholders optional

### ISSUE THREAD

**Issue by alikyo** [auth0/Auth0.Android#168]
Hi,

I am trying to upgrade form the 1.8.0 version to the 1.13.0 version, with this last version  a manifestPlaceholders configuration is required. But from what I understand it is only used for webAuth0 which I don't use for my project.

Is it possible please to make it optional so I don't need to put dummy configuration or remove RedirectActivity from my manifest ?

Thanks

**Comment by lbalmaceda** [comment]
@alikyo You're right. They are required for Web Auth. We never actually thought about this no-use case to be honest. We think of Web Auth as one of the core features and that's where most of the improvements go. The correct way to fix the compile error is removing the activity from the merged manifest. You achieve that by adding `tools:node="remove"` to the activity entry in your app's manifest.

```xml
<activity
            android:name="com.auth0.android.provider.RedirectActivity"
            tools:node="remove"/>
```

I'll add a mention to the README file.

**Comment by alikyo** [comment]
@lbalmaceda yes that I did
```
<!-- OAuth -->
        <!-- Disable unwanted activities from OAuth library, we don't use web/universal authentication flow -->
        <activity
            android:name="com.auth0.android.provider.AuthenticationActivity"
            tools:node="remove"
            />
        <activity
            android:name="com.auth0.android.provider.RedirectActivity"
            tools:node="remove"
            />
        <activity
            android:name="com.auth0.android.provider.WebAuthActivity"
            tools:node="remove"
            />
```
But I was wondering if it could be handled by the library itself.
Anyway, thank you for your time and effort :)

**Comment by alikyo** [comment]
Hi,

We don't use any of the OAuth UI.
All interactions are through background network calls :)

Best regards
