### ISSUE TITLE
IllegalArgumentException: Service not registered: when unbinding CustomTabsController

### ISSUE THREAD

**Issue by idcuesta** [auth0/Auth0.Android#174]
I am getting a consistent crash in my android emulator when trying to integrate Auth0 into my app. I am using last version of the library (1.13.1).

After some time debugging the issue I think I get a basic understanding of what's going on.

`CustomTabsController` define these methods
```
/**
     * Attempts to bind the Custom Tabs Service to the Context.
     */
    public void bindService() {
        Log.v(TAG, "Trying to bind the service");
        Context context = this.context.get();
        boolean success = false;
        if (context != null && preferredPackage != null) {
            success = CustomTabsClient.bindCustomTabsService(context, preferredPackage, this);
        }
        Log.v(TAG, "Bind request result: " + success);
    }

    /**
     * Attempts to unbind the Custom Tabs Service from the Context.
     */
    public void unbindService() {
        Log.v(TAG, "Trying to unbind the service");
        Context context = this.context.get();
        if (context != null) {
            context.unbindService(this);
        }
    }
```

When I am starting a `WebAuthProvider`, an `AuthenticationActivity` is presented to the user, and this activity is calling the method `bindService`. For some reason,  `preferredPackage ` is null in my emulator and `success = CustomTabsClient.bindCustomTabsService(context, preferredPackage, this);` is not getting called. Then, when activity is destroyed, `unbindService` is called and my app crashes because context is trying to unbind a service that was never bind.

I believe the if clause should match in both methods so if it doesn't enter in the first one to bind the service, it doesn't;t enter in the second one either to unbind it, and then you don't get calls unbalanced.

I have tried with previous version of the library (1.13.0), as this change has been introduced recently (6 days ago), and it is not crashing anymore in my emulator.

**Comment by lbalmaceda** [comment]
hey! This is already addressed here https://github.com/auth0/Auth0.Android/pull/173. I was waiting for circleci to come back to life :) I'll make a patch release soon.

**Comment by idcuesta** [comment]
Thanks !
