### ISSUE TITLE
How can i retrieve user metadata?

### ISSUE THREAD

**Issue by javichaques** [auth0/Auth0.Android#181]
Hello,

I send some user metada at signup, i can see this in Auth0 panel, and i want to retrieve this when I get user info.

How can i retrieve the user metadata?

Thank you

**Comment by lbalmaceda** [comment]
You should call the `UsersAPIClient#getProfile` method. There's a quickstart you can follow [here](https://auth0.com/docs/quickstart/native/android/04-user-profile)

**Comment by javichaques** [comment]
I tried to retrieve user profile but returns "Unauthorized" "An error occurred when trying to authenticate with the server."

The AuthenticationAPIClient#Userinfo call works but UsersAPIClient#getProfile doesn't works.

Should I activate something from Settings?

**Comment by lbalmaceda** [comment]
@javichaques Make sure you follow the steps in the guide I linked above. _Unauthorized_ means the token you're passing to the constructor of the `UsersAPIClient` doesn't have the right _scope_ or _audience_ to reach that endpoint. You can also start from the login quickstart if you missed any steps or find that some of them are not detailed in this later guide.

**Comment by javichaques** [comment]
I followed the login quickstart.
I'm using this scope when login:
**openid profile email address phone offline_access**

It's correct?

**Comment by lbalmaceda** [comment]
> I'm using this scope when login: `openid profile email address phone offline_access`

The quickstart I linked is about user-profile (the endpoint you need to call) and it's using a different scope. Please try again following the instructions https://auth0.com/docs/quickstart/native/android/04-user-profile
