### ISSUE TITLE
Facebook Re-prompt doesn't work

### ISSUE THREAD

**Issue by alikyo** [auth0/Auth0.Android#195]
Hi,

I am trying to integrate social login into my App using Universal login (I am using the 1.14.1 version of the SDK)

I need to present the Facebook prompt each time the user try to login (even if he is already logged in.
From [documentation](https://auth0.com/docs/connections/social/reprompt-permissions) I just need to add **prompt=consent** but it doesn't work.

```
final Auth0 auth0 = new Auth0(activity);
        auth0.setOIDCConformant(true);

        Map<String, Object> map = new HashMap<>();
        map.put("prompt", "consent");
        //map.put("prompt", "login"); // login is working fine (ask the user to enter his password each time

        WebAuthProvider.init(auth0)
                .withScheme("demo")
                .withConnection("facebook")
                .withParameters(map)
```
Thanks

**Comment by lbalmaceda** [comment]
Unfortunately this is out of our scope. See related issue https://github.com/auth0/Lock.Android/issues/475#issuecomment-422040326

**Comment by alikyo** [comment]
Ok thank you for your feedback.
