### ISSUE TITLE
Cannot GET Callback When Targeting Android P

### ISSUE THREAD

**Issue by kbaldauf** [auth0/Auth0.Android#201]
Hey there. We've been using the Auth0 SDK for quite some time without any issues, however we started to run into issues after upgrading our app's `targetSdkVersion` to 28. Since upgrading to target Android P, we've started seeing `Cannot GET /android/applicationId/callback` errors. I thought it was a case of using an outdated version of the Auth0 SDK, however the issue has persisted even after upgrading to version 1.14.1.

Are there any known issues or special steps we need to take when using the `WebAuthProvider`  in an app that's targeting Android P?

**Comment by kbaldauf** [comment]
Thanks for the quick reply @lbalmaceda! Prior to upgrading to `1.14.1`, we were using `1.13.2`. Below is a copy of our app's dependencies section. Please let me know if there's any other I can provide that might help us diagnose this issue.

```groovy
dependencies {
    implementation fileTree(dir: project.libsLocation, include: ['*.jar'])

    compileOnly 'javax.annotation:jsr250-api:1.0'

    api 'com.jakewharton.timber:timber:4.7.0'
    api 'androidx.appcompat:appcompat:1.0.0'
    api 'androidx.constraintlayout:constraintlayout:1.1.3'
    api 'com.google.android.material:material:1.0.0'
    api 'androidx.cardview:cardview:1.0.0'
    api 'androidx.recyclerview:recyclerview:1.0.0'
    api 'androidx.browser:browser:1.0.0'
    api 'androidx.exifinterface:exifinterface:1.0.0'
    api 'androidx.percentlayout:percentlayout:1.0.0'
    api 'androidx.media:media:1.0.0'

    api 'com.jakewharton:butterknife:9.0.0-SNAPSHOT'
    api 'androidx.legacy:legacy-support-v4:1.0.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-SNAPSHOT'

    api 'com.crystal:crystalrangeseekbar:1.1.3'

    api 'androidx.lifecycle:lifecycle-runtime:2.0.0'
    api 'androidx.lifecycle:lifecycle-common-java8:2.0.0'
    api 'androidx.lifecycle:lifecycle-extensions:2.0.0'

    api 'com.google.firebase:firebase-core:16.0.4'
    api 'com.google.firebase:firebase-messaging:17.3.3'

    api 'com.google.code.gson:gson:2.8.5'
    implementation 'org.apache.commons:commons-text:1.3'
    implementation 'org.apache.commons:commons-lang3:3.7'
    implementation 'com.google.guava:guava:25.1-android'

    api 'pl.droidsonroids.gif:android-gif-drawable:1.2.15'
    api 'jp.wasabeef:blurry:2.1.1'
    api 'com.github.barteksc:android-pdf-viewer:2.8.2'
    api 'com.github.chrisbanes:PhotoView:2.2.0'
    api 'com.stripe:stripe-android:8.0.0'
    api 'com.appsflyer:af-android-sdk:4.8.15@aar'
    api 'com.android.installreferrer:installreferrer:1.0'

    api 'com.airbnb.android:lottie:2.7.0'
    api 'org.apache.commons:commons-text:1.3'
    api 'org.apache.commons:commons-lang3:3.7'

    api 'io.branch.sdk.android:library:2.19.3'
    api 'com.squareup.retrofit2:retrofit:2.4.0'
    api 'com.squareup.retrofit2:converter-gson:2.4.0'
    api 'com.squareup.retrofit2:retrofit-mock:2.4.0'
    api 'com.squareup.okhttp3:logging-interceptor:3.11.0'

    // GRPC
    api 'io.grpc:grpc-okhttp:1.12.0'
    api 'io.grpc:grpc-protobuf-lite:1.12.0'
    api 'io.grpc:grpc-stub:1.12.0'

    api 'com.google.android.gms:play-services-maps:16.0.0'
    api 'com.google.android.gms:play-services-location:16.0.0'
    api 'com.google.android.gms:play-services-places:16.0.0'
    api 'com.google.android.gms:play-services-ads:16.0.0'
    api 'com.google.android.gms:play-services-wallet:16.0.1'

    api 'com.auth0.android:auth0:1.14.1'
    api 'com.squareup.picasso:picasso:2.71828'

    // Separating this out from heap and grpc as otherwise they cause conflicts
    api 'com.google.protobuf:protobuf-lite:3.0.1'

    // MParticle
    api 'com.mparticle:android-core:5.6.0'

    // Lean Plum
    api 'com.leanplum:leanplum-fcm:4.1.1'

    // Heap Analytics dependency
    api 'com.heapanalytics.android:heap-android-client:0.7.0'

    // ThreatMetrix
    api(name: 'TrustDefender-5.2-36', ext: 'aar')

    // Sentry
    api 'io.sentry:sentry-android:1.7.10'

    // Apptentive
    api 'com.apptentive:apptentive-android:5.3.0'

    // Instabug
    api 'com.instabug.library:instabug:8.0.3'

    // Jodatime
    api 'joda-time:joda-time:2.10'

    api('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true
    }

    api 'com.helpshift:android-helpshift-en-aar:7.2.0'

    api 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71'

    api(name: 'sanselan-release', ext: 'aar')

    api 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-beta01'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-beta01'

    debugImplementation 'com.willowtreeapps.hyperion:hyperion-core:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-attr:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-measurement:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-disk:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-recorder:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-phoenix:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-shared-preferences:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-geiger-counter:0.9.24'
    debugImplementation 'com.willowtreeapps.hyperion:hyperion-timber:0.9.24'

    debugImplementation 'com.readystatesoftware.chuck:library:1.0.0'
    releaseImplementation 'com.readystatesoftware.chuck:library-no-op:1.0.0'
    androidTestImplementation 'com.readystatesoftware.chuck:library-no-op:1.0.0'
    debugImplementation 'com.github.Commit451:Hyperion-Chuck:1.0.0'
}
```

**Comment by kbaldauf** [comment]
@lbalmaceda We've been doing more internal testing today and have discovered that we're only seeing the `Cannot GET /android/applicationId/callback` errors on debug builds. The callback/redirect occurs without issue on our release builds. I've been combing through our codebase and haven't found any differences in how we're interacting with Auth0 in debug builds vs release builds. Is there anything in the SDK itself contain any internal difference between debug and release builds?

**Comment by lbalmaceda** [comment]
@kbaldauf The redirect should be captured by the `Intent-Filter` defined in the `AndroidManifest.xml`. We have only one manifest (no alternative version for debug or release builds). The intent filter declaration is [here](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/AndroidManifest.xml#L49-L51) referencing the 2 manifest placeholders that [you must add](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) on your own app's `build.gradle` file, plus the one included automatically by the android plugin (the `applicationId` one). With all this 3 strings we build the redirect URL that will later be registered to capture the callback and launch your app.

You might have 2 different manifest (e.g. an extra one for the release build) or you might be referencing the `string.xml` file that also overrides that scheme/domain value definition for another build type. For further debugging this, you could use the manifest merger tab in Android Studio to check that the final manifest includes the right intent filter definition, or check that the resulting callback url (used in the `WebAuthProvider`) matches the one defined in the intent filter and in your dashboard

**Comment by kbaldauf** [comment]
@lbalmaceda Thanks for the suggestions. We did some more testing today and it appears that the issue was related to Android App Links and `auth0Scheme` we've been using. It would seem that the redirect just fails outright when the scheme of `https` is used in a build signed with key that's not included in our `.well-known/assetlinks.json. We had assumed that a chooser dialog would be shown in such a case, but that doesn't seem to be what happens. 

It would appear that the solution for our app will be to change the callback url scheme from `https` to something more app specific (like our app's name) and now the redirect is working on all of our builds regardless of the signing config used.

**Comment by lbalmaceda** [comment]
@kbaldauf per the documentation [here](https://developer.android.com/training/app-links/verify-site-associations) they do accept multiple key hashes. You should be able to add both the debug and the release build certificates' hashes to have the same behavior both in dev and on prod.

> This field supports multiple fingerprints, which can be used to support different versions of your app, such as debug and production builds.

Remember that the domain verification is performed on every install-time. It's normal that if the verification failed you don't get the dialog prompting for what app to resolve that, since you probably have the browser app chosen as "default app" to handle URL like intents. Try having 2 browsers installed and see if the behavior is the same. Though this is the SO behavior and it's out of our scope.

I'm glad you could find the issue. I'll proceed to close this.
