### ISSUE TITLE
WebAuth login hangs when MS Edge in-app browser is used

### ISSUE THREAD

**Issue by d60402** [auth0/Auth0.Android#223]
### Description

WebAuth login hangs when MS Edge in-app browser is used

Adding this issue as per [internal thread](https://auth0.slack.com/archives/C9F94RE0K/p1549301158137400?thread_ts=1549299521.135800&cid=C9F94RE0K)

### Environment

Please provide the following:

- Version of Auth0.Android used: 1.15.1
- Version of Android being used: 7.0
- Additional packages that might be affecting your instance: n/a

### Reproduction

1. Install MS Edge as default browser on the device
2. Start the [Auth0 Login Quickstart](https://auth0.com/docs/quickstart/native/android/00-login)
3. Attempt to Login. Notice that the hosted login page progress indicator will spin forever

If on the login page you choose **Open in Microsoft Edge** from the in-app browser ... menu and login there, it succeeds. 

Also, the issue exists both with custom callback scheme as well as https+app links.

**Comment by lbalmaceda** [comment]
This is a problem external to this SDK, and there's nothing we can do to fix it. Hopefully the latests Edge Browser app has fixed it.
