### ISSUE TITLE
Usage of v2 users search engine

### ISSUE THREAD

**Issue by hoang-ei** [auth0/Auth0.Android#225]
Usage of api/v2/users instead of v3. Please update to v3

It gives me warning in admin web saying:

The User Search v2 engine is deprecated, please use v3 (search_engine=v3) instead.

### Environment

- Lock version 2.12.1
- Auth0 1.15.1

**Comment by lbalmaceda** [comment]
That seems not to belong to this SDK. If this is related to some other auth0 library feel free to re-open it in there, filling the issue template that you are asked to complete.
