### ISSUE TITLE
WebAuthProvider cuts off the bottom of the universal login page

### ISSUE THREAD

**Issue by tomrom95** [auth0/Auth0.Android#226]
### Description
We are switching from the native Auth0 Lock to use the WebAuthProvider in our Android app, but we are noticing a UI issue when we load the login page. When the universal login page loads, since there is an address bar at the top, the page gets cutoff and the user has to scroll to find the submit button (shown below with URL hidden). This is not ideal for our users, and we were wondering if there's some way to change the WebAuthProvider to show the entire page, even when the address bar is shown.

<img width="421" alt="Screen Shot 2019-03-12 at 3 24 07 PM" src="https://user-images.githubusercontent.com/7095894/54243856-58d50380-44e7-11e9-8ce8-21884e6afa77.png">

### Environment

Please provide the following:

- Version of Auth0.Android used: 1.14.1
- Version of Android being used: 28
- Additional packages that might be affecting your instance: none

### Reproduction
Launch the WebAuthProvider using the default Universal Login page. Notice that the submit button is cut off at the bottom.

**Comment by lbalmaceda** [comment]
Thanks for the report! This is not an issue of this SDK but rather the Lock web widget itself.
I've reported this some time ago, and it got fixed but now seems to be back again :D I know there's work in progress for this but I myself can't provide an estimate. You can do any follow up questions in here https://github.com/auth0/lock/issues/1474

**Comment by tomrom95** [comment]
Thanks @lbalmaceda ! I'll take a look and report back

**Comment by tomrom95** [comment]
@lbalmaceda The issue was that the Universal Login page templates were pinned on a very old version of the Lock web widget. I should have checked this first! I'm going to contact support to make sure the templates are updated. Thanks for all the help
