### ISSUE TITLE
Retrieving the User Profile using a refreshed token returns an empty object and errors

### ISSUE THREAD

**Issue by tomrom95** [auth0/Auth0.Android#232]
### Description
After retrieving user credentials for the first time, we can successfully use the returned token to get the User Profile using the `AuthenticationAPIClient.userInfo(token)` method. However, after the token is refreshed, calling the `userInfo` method with the refreshed token results in the following exception:

```
 com.google.gson.JsonParseException: user profile json is not a valid json object
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:21)
        at com.auth0.android.request.internal.UserProfileDeserializer.deserialize(UserProfileDeserializer.java:17)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
        at com.auth0.android.request.internal.SimpleRequest.execute(SimpleRequest.java:111)
```
The reason for this is because the `/userInfo` endpoint is returning an empty JSON object (`{}`) back and this cannot be parsed. We have additionally found that an empty JSON object is being returned because the refreshed token does not contain the scopes necessary to fetch the user's profile (`openid` and `profile`). Using the CredentialsManager, there's also no way to pass in these scopes when fetching/refreshing the token:
```java
void getCredentials(@NonNull final BaseCallback<Credentials, CredentialsManagerException> callback) {
```

Is there any way we can pass in these scopes or enable the refreshed token to have the same scope as the original token?

### Environment
- Android Auth0 1.15.1
- Java 8

### Reproduction

Call `CredentialsManager.getCredentials()` after a token has expired and then use the token to call `AuthenticationAPIClient.userInfo(token).execute()`. This will result in a JsonParseException

**Comment by tomrom95** [comment]
Looks like Auth0 swift added support for optionally specifying the scope when retrieving credentials: https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift#L120 . I can implement something similar for this library if it looks okay.

**Comment by lbalmaceda** [comment]
Closing as explained in linked PR's conversation.
