### ISSUE TITLE
id token not renewed during getCredentials call unless access token is expired.

### ISSUE THREAD

**Issue by camhart** [auth0/Auth0.Android#253]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

I use the id token with my AWS Cognito integration.  I'd like my id tokens to ideally be set with a 1-2 hour expiration.  However I can't currently using the `SecureCredentialsManager.getCredentials` call because that call only checks if the access token is expired when considering if it should renew.  And the access token is required to have an expiration of 24 hours.

### Prerequisites

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:
- Version of Auth0.Android used: 1.18.0
- Version of Android being used: 10

### Reproduction

Drop JWT expiration down to 5 minutes.  Authenticate.  Wait 5 minutes, then make a call to `getCredentials`.  The idToken won't be renewed--no call to apiClient.renewAuth is ever made.

```
private void continueGetCredentials(final BaseCallback<Credentials, CredentialsManagerException> callback) {
        String encryptedEncoded = storage.retrieveString(KEY_CREDENTIALS);
        byte[] encrypted = Base64.decode(encryptedEncoded, Base64.DEFAULT);

        String json;
        try {
            json = new String(crypto.decrypt(encrypted));
        } catch (IncompatibleDeviceException e) {
            callback.onFailure(new CredentialsManagerException(String.format("This device is not compatible with the %s class.", SecureCredentialsManager.class.getSimpleName()), e));
            decryptCallback = null;
            return;
        } catch (CryptoException e) {
            //If keys were invalidated, existing credentials will not be recoverable.
            clearCredentials();
            callback.onFailure(new CredentialsManagerException("A change on the Lock Screen security settings have deemed the encryption keys invalid and have been recreated. " +
                    "Any previously stored content is now lost. Please, try saving the credentials again.", e));
            decryptCallback = null;
            return;
        }
        final Credentials credentials = gson.fromJson(json, Credentials.class);
        if (isEmpty(credentials.getAccessToken()) && isEmpty(credentials.getIdToken()) || credentials.getExpiresAt() == null) {
            callback.onFailure(new CredentialsManagerException("No Credentials were previously set."));
            decryptCallback = null;
            return;
        }
        if (credentials.getExpiresAt().getTime() > getCurrentTimeInMillis()) { //<----------------- this needs to check if idToken is expired.
            callback.onSuccess(credentials);
            decryptCallback = null;
            return;
        }
        if (credentials.getRefreshToken() == null) {
            callback.onFailure(new CredentialsManagerException("No Credentials were previously set."));
            decryptCallback = null;
            return;
        }

        Log.d(TAG, "Credentials have expired. Renewing them now...");
        apiClient.renewAuth(credentials.getRefreshToken()).start(new AuthenticationCallback<Credentials>() {
            @Override
            public void onSuccess(Credentials fresh) {
                //RefreshTokens don't expire. It should remain the same
                Credentials refreshed = new Credentials(fresh.getIdToken(), fresh.getAccessToken(), fresh.getType(), credentials.getRefreshToken(), fresh.getExpiresAt(), fresh.getScope());
                saveCredentials(refreshed);
                callback.onSuccess(refreshed);
                decryptCallback = null;
            }

            @Override
            public void onFailure(AuthenticationException error) {
                callback.onFailure(new CredentialsManagerException("An error occurred while trying to use the Refresh Token to renew the Credentials.", error));
                decryptCallback = null;
            }
        });
```

**Comment by lbalmaceda** [comment]
Sounds good to me. Let me discuss with the team.

**Comment by camhart** [comment]
@lbalmaceda If it's safe to say Auth0 want getCredentials to ALWAYS return valid values (id and access token), I'd be happy to put a PR up using the https://github.com/auth0/JWTDecode.Android library.

Or if there's a different set of configurability you'd like to added, I'd consider doing it too... if it gets too big I'll punt and let you guys handle it :D.

**Comment by lbalmaceda** [comment]
@camhart Sorry I forgot to reply. We were discussing with the team whether the manager's responsibility was to keep only the ID Token in sync or also the Access Token. I think it doesn't hurt to use both when deciding when the whole thing expires.

Can you please put a PR for this? 🙏  The SDK is already using as dependency the `JWTDecode.Android` library. What you'd need to do is only change the "save credentials" logic, so that it now decodes the ID token (if available) and takes the `exp` claim. That claim should be compared against the `credentials.getExpiresAt()` value (which represents the access_token expiration). You would take the min value of both and save that here https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/CredentialsManager.java#L55.

**Comment by camhart** [comment]
Here's a commit with the code changes... https://github.com/camhart/Auth0.Android/commit/53db068cd827ce6598135e759576b6a2f7a68856, but I'm unable to run the tests (and I haven't added any tests as a result).  I use a windows box and am hitting this issue: https://github.com/robolectric/robolectric/issues/4603.  On my Mac (which I'm unfamiliar with) I can't get Android Studio to run the sdk manager, which is preventing me from building...

@lbalmaceda can you guys pick it up from here?  (not that I did much...).

**Comment by camhart** [comment]
Thanks for the help @lbalmaceda.  I worked around it in a less than ideal way, so I can wait a little.  I would still like to have it all cleaned up at some point though.

**Comment by gurprt** [comment]
com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The supplied auth credential is malformed or has expired. [ ID Token issued at ************ is stale to sign-in. ]
Same issue having.
Please, someone, fix the issue for me. Thank You

**Comment by lbalmaceda** [comment]
@gurprt this library is not part of Firebase. If you are having trouble with them, I suggest you raise the issue on their side.

**Comment by gurprt** [comment]
@lbalmaceda  Thank you

**Comment by hackaprende** [comment]
> com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The supplied auth credential is malformed or has expired. [ ID Token issued at ************ is stale to sign-in. ]
> Same issue having.
> Please, someone, fix the issue for me. Thank You

Same issue here, it only happens in one cellphone.
