### ISSUE TITLE
SecurityException Permission Denial in CustomTabsController

### ISSUE THREAD

**Issue by h-mubarak** [auth0/Auth0.Android#257]
### Description
User is complaining about the crashes. Its mostly occurring in android 6 version.

**Here is crashalitics log:**
`Fatal Exception: java.lang.SecurityException
Permission Denial: starting Intent { act=android.intent.action.VIEW cmp=com.android.stk/.StkMenuActivity (has extras) } from ProcessRecord{aa8191a 10334:com.newscorp.theaustralian/u0a197} (pid=10334, uid=10197) not exported from uid 1001
android.os.Parcel.readException + 1620 (Parcel.java:1620)
android.os.Parcel.readException + 1573 (Parcel.java:1573)
android.app.ActivityManagerProxy.startActivity + 3131 (ActivityManagerProxy.java:3131)
android.app.Instrumentation.execStartActivity + 1540 (Instrumentation.java:1540)
android.app.Activity.startActivityForResult + 4283 (Activity.java:4283)
android.app.Activity.startActivityForResult + 4230 (Activity.java:4230)
android.app.Activity.startActivity + 4567 (Activity.java:4567)
android.app.Activity.startActivity + 4535 (Activity.java:4535)
com.auth0.android.provider.CustomTabsController$1.run + 149 (CustomTabsController.java:149)
java.lang.Thread.run + 818 (Thread.java:818)`

### Environment
- Version of Auth0.Android used: 1.15.2
- Version of Android being used: Android 6

### Reproduction

Detail the steps taken to reproduce this error and note if this issue can be reproduced consistently or if it is intermittent.

Please include:
- Specific devices affected: In Crashlytics: I am able to see **galaxy s5 and galaxy s5 mini**
- Log files or stacktraces (redact/remove sensitive information): Logs added under description

**Comment by harshmittal29** [comment]
Getting this issue again.

> Fatal Exception: java.lang.SecurityException
> Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://mindvalley.auth0.com/... cmp=com.cleanmaster.security/cms.pb.PBLinkActivity (has extras) } from ProcessRecord (pid=10553, uid=10170) not exported from uid 10074

auth0 SDK version : 1.17.0

**Comment by h-mubarak** [comment]
I am also facing this issue.  Can the auth0 team help me with this?
auth0_version = 1.15.2

**Comment by stephen1706** [comment]
I am facing the same issue, it happened when auth0 try to open a custom tab which is not supporting the mechanism. In my case, i try to install nearbuy application and set their browser as default browser, then when i start login flow, it will open their custom tab and crash. is there a way to blacklist certain browser used?

```
Fatal Exception: java.lang.SecurityException
Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://loginurlhere.com/... cmp=com.nearbuy.nearbuymobile/.feature.DeepLinkWebViewActivity (has extras) } from ProcessRecord{5b10745 9886:com.package.name/u0a1067} (pid=9886, uid=11067) requires com.nearbuy.nearbuymobile
com.auth0.android.provider.CustomTabsController$1.run
com.auth0.android.provider.CustomTabsController$1.run (CustomTabsController.java:149)
```
