### ISSUE TITLE
TokenValidationException when using 1.20.1

### ISSUE THREAD

**Issue by Entreco** [auth0/Auth0.Android#278]
### Description

> TokenValidationException when updating from 1.19.0 to 1.20.1

### Reproduction

> We use auth0 to authenticate our users. With auth0 1.19.0 everything works as expected, when we update to 1.20.1 we get this exception:

```
Issuer (iss) claim mismatch in the ID token, expected "https://xxx-xxxxx.xxxxxxxxxx.nl/", found "https://xxx-xxxxxxxxxxnl.xxx.nxtid.nl/"
```

This happens consistently. E.g. When reverting back to 1.19.0, everything works fine. Switching back to 1.20.1 -> we get the Exception and are not able to proceed.

Here's how we start the WebFlow:

```
        val clientId = ...
        val domain = ...        
        val url = ...
        val scheme = ...

        val auth = WebAuthProvider.login(Auth0(clientId, domain).apply { isOIDCConformant = true })
        auth.withParameters(mapOf("prompt" to "login"))
                .withAudience(url)
                .withScope("openid offline_access")
                .withScheme(scheme)
                .withResponseType(ResponseType.CODE)
                .withCustomTabsOptions(CustomTabsOptions.newBuilder().showTitle(true).build())
                .start(activity, object : AuthCallback {
                    override fun onSuccess(credentials: Credentials) {
                        success(credentials)
                    }

                    override fun onFailure(dialog: Dialog) {
                        failure()
                    }

                    override fun onFailure(exception: AuthenticationException?) {
                        failure(exception)
                    }

                })
```

### Environment

> Please provide the following:

- auth0 version: 1.20.1
- Android 10
- Testing on a real device 
- Using local build with Android Studio 3.5 on Mac Catalina

**Comment by lbalmaceda** [comment]
Hi @Entreco. Are you using custom domains?

**Comment by Entreco** [comment]
I don't know what that means exactly, but probably yes. 

We have our own server, which receives the request and returns an authorization code.
That server is a black box for me, but since swapping between auth0 versions changes the behaviour, my first guess is something in the library changed.

I understand it's hard to reproduce on your end, so let me know how I can help you pin point the issue. 
Or to point me into another direction for a solution. All help is welcome ;)

**Comment by lbalmaceda** [comment]
@Entreco We introduced changes in how the SDK conforms to the OpenID Connect spec. This normally wouldn't be an issue, but I'm thinking of the scenario in which your app is launched with a custom domain (e.g. auth.mycompany.com) vs the auth0 domain (e.g. mycompany.auth0.com). That might be what you are seeing in the exception message. Is that message something you can share, or at least confirm this is the case?

**Comment by Entreco** [comment]
Yes, that's what I'm seeing in the message! 
Looks like our server is not following the OpenID Connect spec to the letter. 
Thanks for pointing me in the right direction.


I'll start to experiment by changing: 
`WebAuthProvider.login(Auth0(clientId, domain).apply { isOIDCConformant = true })`

to 

`WebAuthProvider.login(Auth0(clientId, domain).apply { isOIDCConformant = false })`

**Comment by lbalmaceda** [comment]
That is not the ideal path, going forward we would like everyone to be on an OIDC compliant client. You might want to check this article and turn the flag ON on the auth0 dashboard side for your application. https://auth0.com/docs/api-auth/tutorials/adoption#terminology

**Comment by Entreco** [comment]
Thanks! Forwarded to the relevant teams in our organisation
