### ISSUE TITLE
No method for renewing token with different audience 

### ISSUE THREAD

**Issue by shahakash1997** [auth0/Auth0.Android#286]
The existing renew token method renews the token but returns the same audience. It has no method to change the audience.Like in our use case we have multiple APIs each having a different audience.
To login for these backends we have to call WebAuthProvider.login() method multiple times each time providing different audience. This results in bad UI/UX.
Please provide a method to exchange token for different audience

**Comment by lbalmaceda** [comment]
Requesting a different "scope" is a valid feature request. But requesting a totally different audience sounds like it is an invalid one. The correct way would be the one you're doing today: multiple logins. The ideal scenario would be requesting multiple audiences but that is not supported by auth0 today. See a suggested alternative on this [post](https://community.auth0.com/t/multiple-audiences-in-an-access-token/21945/2).
