### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String java.security.cert.Certificate.getType()' on a null object reference

### ISSUE THREAD

**Issue by Belka1000867** [auth0/Auth0.Android#291]
### Description

Got this error from Firebase crashlytics.

### Reproduction

Happens on SecureCredentialsManager.saveCredentials

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'java.lang.String java.security.cert.Certificate.getType()' on a null object reference
> 

> java.security.KeyStore$PrivateKeyEntry.<init> (KeyStore.java:567)
java.security.KeyStore$PrivateKeyEntry.<init> (KeyStore.java:526)
com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat (CryptoUtil.java:208)
com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry (CryptoUtil.java:97)
com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt (CryptoUtil.java:297)
com.auth0.android.authentication.storage.CryptoUtil.getAESKey (CryptoUtil.java:353)
com.auth0.android.authentication.storage.CryptoUtil.encrypt (CryptoUtil.java:434)
com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials (SecureCredentialsManager.java:163)

### Environment

- **Version of this library used:**   com.auth0.android:auth0:1.20.1
- **Version of the platform or framework used, if applicable:** Android 10 (Samsung Galaxy S10)

**Comment by lbalmaceda** [comment]
Fixed with https://github.com/auth0/Auth0.Android/pull/288
