### ISSUE TITLE
Support for multiple tenants doesn't work

### ISSUE THREAD

**Issue by MattPhilpot** [auth0/Auth0.Android#292]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Authentication never completes in webview if the auth0Domain manifestPlaceholder in build.gradle is set to ""

Our use-case is that we want to support multiple auth0 tenants that have different domains (ie login.auth0.com and dev.auth0.com)

### Reproduction

build.gradle:
```groovy
//purposefully leaving auth0Domain blank
//If you remove auth0Domain, it won't compile
manifestPlaceholders = [auth0Domain: "", auth0Scheme: "@string/auth0_scheme"]
```

code:
```kotlin
private var useProd = true

//other code in the class

private fun generateCorrectAuth0(): Auth0 {
	return if (useProd) {
		generateProdAuth0()
	} else {
		generateStagAuth0()
	}
}

private fun generateProdAuth0(): Auth0 = Auth0(clientIdProd, domainProd)

private fun generateStagAuth0(): Auth0 = Auth0(clientIdStag, domainStag)
```

In this configuration, I can get to the auth0 webview screen fine, but no matter which authentication method I choose (google, user/pass, etc), the webview never returns to the application, it just sits there with a spinner forever.

If I set the "auth0Domain" within build.gradle to the same as what domainProd or domainStag is, I can authenticate against that tenant/domain, but am thus unable to against any other.

**Comment by lbalmaceda** [comment]
👋 @MattPhilpot those 2 manifest placeholder are core to the intent result communication. If you don't define them (or use wrong values) then the browser won't be able to take back the authentication result to your app. So the solution would be to define them.


If you're using _flavours_ you can define each set of manifestPlaceholders separately https://developer.android.com/studio/build/build-variants.

If you have a more advanced scenario, you can always declare the activity yourself, overriding the one this SDK defines. See https://github.com/auth0/Auth0.Android#authentication-with-universal-login.
