### ISSUE TITLE
Support for Proxy 

### ISSUE THREAD

**Issue by YuriRudenyaDev** [auth0/Auth0.Android#296]
### Description

Auth0 doesn't work when an android phone connected to wifi with NTLM Proxy. 
We had the same issue before stated working with Auth0 SDK but we used the retrofit SDK.

OkHTTP client builder:

```
    public OkHttpClient createClient(boolean loggingEnabled, boolean tls12Enforced, int connectTimeout, int readTimeout, int writeTimeout) {

        OkHttpClient.Builder defaultHttpClient = new OkHttpClient.Builder();

        Authenticator proxyAuthenticator = new Authenticator() {

            @Override
            public Request authenticate(Route route, okhttp3.Response response) throws IOException {
                if (response.code() == 407) {

                    ProxyCredentials credentials = getProxyCredentials();

                    if (credentials == null) {
                        throw new IOException("Failed to authenticate with proxy");
                    }

                    List<HTTPAuthMethod> httpAuthMethods = HTTPAuthMethod.ReadMethodsFromResponse(response);
                    ProxyAuthenticator resolvedAuthenticator = null;
                    HTTPAuthMethod resolvedMethod = null;
                    for (ProxyAuthenticator authenticator : proxyAuthenticators) {
                        for (HTTPAuthMethod authMethod : httpAuthMethods) {
                            if (authenticator.supportsAuthMethod(authMethod)) {
                                resolvedAuthenticator = authenticator;
                                resolvedMethod = authMethod;

                                break;
                            }
                        }

                        if (resolvedAuthenticator != null) {
                            break;
                        }
                    }

                    if (resolvedAuthenticator == null) {
                        return null;
                    }

                    try {
                        return resolvedAuthenticator.authenticate(credentials, resolvedMethod, route, response);
                    } catch (Throwable e) {
                        if (e instanceof ProxyErrors.CredentialsAreInvalidException) {
                            updateProxyCredentials(null);
                        }

                        throw new IOException("Failed to authenticate with proxy");
                    }
                }

                return null;
            }
        };

        defaultHttpClient = defaultHttpClient
                .proxyAuthenticator(proxyAuthenticator);

        return modifyClient(defaultHttpClient.build(), loggingEnabled, tls12Enforced, connectTimeout, readTimeout, writeTimeout);
    }
```

```
            @Override
            public void onFailure(Call<T> call, Throwable t) {
                t.printStackTrace();
                if (result == null) {
                    return;
                } else if ("Canceled".equalsIgnoreCase(t.getMessage())) {
                    return;
                }

                if (t.getMessage() != null && t.getMessage().equals("Failed to authenticate with proxy")) {
                    handleProxyError(call, result, context, t);
                    return;
                }

                notifyErrorResult(call, result, context, t);
            }
```

```
    public static <T> void handleProxyError(final Call<T> call, final CallbackResponse<T> result, final Context context, final Throwable error) {
        if (instance.proxyErrorHandler == null) {
            notifyErrorResult(call, result, context, error);
            return;
        }

        ErrorRequestFulfiller fulfiller = new ErrorRequestFulfiller() {
            @Override
            void notifyError() {
                notifyErrorResult(call, result, context, error);
            }

            @Override
            void redo() {
                enqueue(call.clone(), result, context);
            }
        };

        inflightRequests.add(fulfiller);

        if (handlingProxyError) {
            return;
        }

        handlingProxyError = true;
        instance.proxyErrorHandler.handle(new ProxyErrorHandler.Callback() {
            @Override
            public void onResult(ProxyErrorHandler.Result resolveResult) {
                handlingProxyError = false;


                if (resolveResult.getError() != null) {
                    for (ErrorRequestFulfiller fulfiller : inflightRequests) {
                        fulfiller.notifyError();
                    }
                } else {
                    ProxyData proxyData = resolveResult.getProxyData();
                    ProxyCredentials credentials = new ProxyCredentials(proxyData.getProxyUser(), proxyData.getProxyPass());
                    instance.updateProxyCredentials(credentials);
                    for (ErrorRequestFulfiller fulfiller : inflightRequests) {
                        fulfiller.redo();
                    }
                }
            }
        });
    }

```

In case of a proxy authentication error, we show a dialog and ask users to enter a login/password to save it for the current and next session.

### Environment

Android:
 implementation 'com.auth0.android:lock:2.17.1'
 implementation 'com.auth0.android:jwtdecode:1.4.0'

### NTLM setup on a local machine for testing

Requirements:
1. Windows

I use parallels, install windows there, establish a connection between host and virtual machine (ping to check)

Steps:

1. Install WinGate
  a)  https://www.wingate.com/download/wingate/download.php?gclid=EAIaIQobChMI0bbYzoT14wIVlOiaCh1XzQ_EEAAYASABEgIioPD_BwE

2. Start Wingate
  a)  Select the first square button
  b) In wizard select win proxy as a provider (should be automatically though)
  c) Select + on the same screen where we selected the first button and click on in popup
  d). Select the created a button and choose to Use another account
  e) Name: Administrator, Pass: <None>

3. Enable NTLM and Select Port
  a) Control panel -> services -> www proxy
  b) In General select port (let's say 9020), enable NTLM, disable basic (we want to check NTLM right?)

4. Force NTLM authentication
  a) Right-click, new policy.
  b) Source Type: Any HTTPProxy, Event type: Request.
  c) The easiest way to configure policy is to drag and drop some policy elements from other policies.
  d) To do this Open web authenticate policy in another window (you can see this policy in the list)
  e) Drag and drop to a new policy from authenticating policy: "Auth", "Allow", "Is authenticated?" elements.
 f) Drag and drop to new policy from a list of elements "WWW Proxy Server: Request" element.
 g) Connect "WWW Proxy Server: Request" to "Is authenticated" element
 h) Connect the bottom of "Is authenticated"  (Yes) to "Allow" element
 i) Connect right of "Is authenticated"  (No) to "Auth" element
 j) Save (the policy will start to work automatically)

5. Create user.
  a) Control Panel -> Users and Groups
  b) Right click -> new Users
  c) Fill in name pass etc.

Check (For mac).

1. Add proxy.
  a)  Go to settings -> Network -> Choose network used for internet -> Advanced -> Proxy
  b) Fill in IP and port of proxy for Web Proxy and Secure Web Proxy (Do not fill in pass etc)
2. Check proxy is used
  c) Go to, say, google.com.
  d) Name and Pass requests should be requested.
  e) Use ones from 5.iii

Check (For Android Device and Wingate is on a virtual machine).

1. Add Proxy in android Settings
2. Add port forwarding to port selected on step 3(b)

Warnings.

1. Wingate caches auth status. To force re-auth change user password 5(c) and restart WinGate (Kill Wingate Manager from Tasks Manager (Ctrl + Shift + Esc))

**Comment by lbalmaceda** [comment]
> We had the same issue before stated working with Auth0 SDK but we used the retrofit SDK.

This SDK uses the OkHttp library as a networking client, which is a dependency of Retrofit. If you had trouble with Retrofit, you most definitely will have trouble with this OkHttp as well.

The code for configuring the proxy looks fine but I haven't tested it. What is the issue that you're running into?

**Comment by YuriRudenyaDev** [comment]
> > We had the same issue before stated working with Auth0 SDK but we used the retrofit SDK.
> 
> This SDK uses the OkHttp library as a networking client, which is a dependency of Retrofit. If you had trouble with Retrofit, you most definitely will have trouble with this OkHttp as well.
> 
> The code for configuring the proxy looks fine but I haven't tested it. What is the issue that you're running into?

The problem inside the Auth0 SDK. For us the proxy issue is solved, but when we try to get something from auth0 we won’t get dialog to enter credentials to pass trought the proxy auth.
I looked in the auth0 sdk. The is no Retrofit library inside, that means we have two options:
1) Make a fork and change api call with Retrofit 
2) Try to make the same base only on OkHttp library 

Anyway this is not the issue of Auth0 team. It is the android problem, but if you can solve from your side we will be pleased. The solution from my first comment is working for us in production.

**Comment by jalleyne** [comment]
@lbalmaceda thanks for getting back to us, to be clear the code above is from our own api calls, so we are looking for a way to either expose the okhttp client to apply this code to it or work with you to add support for the proxy authentication into auth0. At present the Auth0 calls for authentication from the sdk fail to connect and authenticate with the proxy.

**Comment by lbalmaceda** [comment]
If I understand correctly, you say the proxy works fine for all request but it doesn't work for those made against Auth0 backend. If that's the case, then yes and that's because of what I said on my previous comment. This library doesn't offer support for Proxy. So you'd need to fork this repository and add it yourself. 

This is the class you'd need to add the proxy in https://github.com/auth0/Auth0.Android/blob/34bc106ff56d30ad28b90b7d63deee0e6079fd4c/auth0/src/main/java/com/auth0/android/request/internal/OkHttpClientFactory.java#L48

And this is where it's being used on for calling the Authentication API.https://github.com/auth0/Auth0.Android/blob/34bc106ff56d30ad28b90b7d63deee0e6079fd4c/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L136

You might find easier to share the client instance that you already have created for your own application, and feed that into the authentication API. Maybe by adding an OkHttpClient setter.

Do note that you will have to maintain your own fork, pulling any changes we do, etc.

**Comment by jalleyne** [comment]
Thanks, exposing the OkHttpClient sounds like a great solution, my question as an enterprise customer with this need is there any option where we work with you to make this change so we don't have to maintain our own fork?

**Comment by YuriRudenyaDev** [comment]
> Thanks, exposing the OkHttpClient sounds like a great solution, my question as an enterprise customer with this need is there any option where we work with you to make this change so we don't have to maintain our own fork?

Ok, let’s try. I will implement the solution in a fork and then we can implement this into master. 
It is not a solution for each proxy protocol. It is only for NTLM

**Comment by jalleyne** [comment]
@lbalmaceda Do you take contributing PRs?

**Comment by lbalmaceda** [comment]
> is there any option where we work with you to make this change so we don't have to maintain our own fork?

Supporting proxy is not in our backlog today.

> Do you take contributing PRs?

Yes, as long as the solution does not expose any external dependency class as part of our public APIs. i.e. exposing the OkHttp client would not be an option. I mentioned it above because you're maintaining your own fork. An alternative could be base on the java `Proxy` class and passing that to the client somehow. 

We also look for a general proxy solution and not one that works only for a specific protocol.

**Comment by jalleyne** [comment]
@lbalmacina thank you. We will discuss our options and get back to you tomorrow if we have any further questions.
