### ISSUE TITLE
Pass custom parameters to token request

### ISSUE THREAD

**Issue by limdale** [auth0/Auth0.Android#300]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am trying to pass custom parameters to my initial `/oauth/token` call. Similar to how you are able to pass parameters to a call to refresh token like so:
```
AuthenticationAPIClient client...;
client.renewAuth("{refresh_token}")
    .addParameter("custom key", "custom value")
    ...
    .start(...);
```
it would be nice to be able to do the same for the initial `TokenRequest` used by `OAuthManager` and `PKCE.getToken` when logging in.

### Describe the ideal solution
Just a blind solution, maybe we can pass another map when building `WebAuthProvider`, something like `withTokenParameters(Map<String, Object> parameters)` which gets used when PKCE does the getToken request.

## Alternatives and current work-arounds
Right now `AuthenticationAPIClient.token(...)` does pass parameters, we can probably have a way to pass custom ones there too. I've also tried extending `AuthenticationAPIClient` but currently there is no way to pass a custom `AuthenticationAPIClient` to `OAuthManager`, it just creates it's own in the constructor, unlike how you can do so in `SecurityCredentialsManager`.

**Comment by lbalmaceda** [comment]
@limdale 👋In general, request instances should accept being cast to `ParameterizableRequest` and call `addParameters` on them. You mentioned many names above and I got a bit lost. Can you please clarify which class and method are you calling and want to have custom params added?

**Comment by limdale** [comment]
so when doing the following:
```
WebAuthProvider.login(auth0)
    ...
    .withParameters(params)
    .start()
```
two API-related things happen: 
1) you open the browser/webview to log the user in, and 
2) after getting an auth code, you do an API call to `/oauth/token` exchange it with a token

the params passed right now are being used for the first one. I was wondering if there's any way to pass custom params to the second one as well

**Comment by lbalmaceda** [comment]
@limdale The additional params are for customizing the authentication, and that begins with the first request. What is your exact use case?

**Comment by limdale** [comment]
@lbalmaceda we were passing some custom parameters on token refresh, and were just investigating if we can also pass it in the initial request as well. Either way the problem has been solved so we can close this up :)
