### ISSUE TITLE
AuthenticationAPIClient function login is not working with custom connection

### ISSUE THREAD

**Issue by GabCast** [auth0/Auth0.Android#302]
### Description

When using login fuction with AuthenticationAPIClient in Android SDK is always setting default connection. 

Its not setting the connection eventhough we are using login with connection parameter. The code error we are getting is: invalid_request. 

We were able to fix that by setting the default connection in our dashboard. So the Android SDK is not working with custom connection send from the app.

### Reproduction

1. Request Login with AuthenticationAPIClient 

```
AuthenticationAPIClient(account)
                .login(emailId, password, CONNECTION)
                .setGrantType(GRANT_TYPE_PASSWORD)
                .setScope(scope)
                .setAudience(audience)
                .start(baseCallback)
```

2. Code: invalid_request

### Environment

Api: com.auth0.android:auth0:1.23.0
Android API28

**Comment by lbalmaceda** [comment]
👋 How are you initializing the `account` value?

**Comment by GabCast** [comment]
We are initializing the value with the context. According to [documentation](https://auth0.com/docs/quickstart/native/android) thats fine.

```
    auth0 = new Auth0(context);
    auth0.setOIDCConformant(true);
```

We even try to initialize passing client_id and domain as parameters, wich is another way to init Auth0 class

```
    auth0 = new Auth0(client_id, domain);
    auth0.setOIDCConformant(true);
```

**Comment by lbalmaceda** [comment]
Thanks @GabCast,
I noticed you are passing a custom grant type of `password`.

The SDK will set the right grant type for you depending on the flow you are attempting to execute. You should not change that manually unless you know what you're doing. Otherwise, the server's behavior would be unexpected. 

When you are running on an OIDC conformant pipeline, for example, the `login()` method would use the password-realm flow, not password one. Your code is now mixing both. The password-realm grant expects a `realm` value that identifies the connection as explained [here](https://auth0.com/docs/api/authentication#resource-owner-password).

**Comment by GabCast** [comment]
Hi, thanks for your reply. I tried this code according to this new info:

```
        AuthenticationAPIClient(account)
                .login(emailId, password)
                .setConnection(CONNECTION)
                .setScope(config.scope)
                .setAudience(config.audience)
                .start(baseCallback)
```
And change our dashboard configuration to use another default database but we still have the same code error: invalid_request because is setting default database instead the connection Im sending.

The other [error](https://github.com/auth0/Auth0.Android/issues/303) that you closed is still happening to. That function (resetPassoword) ask for connection parameter and builder has setConnection function. Do you know the difference betewen:

```
        AuthenticationAPIClient(account)
                .resetPassword(emailId, CONNECTION)
                .setConnection(CONNECTION)
                .start(authCallback)
```

and

```
        AuthenticationAPIClient(account)
                .resetPassword(emailId, CONNECTION)
                .start(authCallback) 
```

Both cases the error still the same

**Comment by lbalmaceda** [comment]
Again you are mixing grant types. When the password-realm is used (default when OIDC is true) a "realm" must be set with `setRealm`, not a "connection". The SDK would do that for you if you call the `login(usernameOrEmail, password, realmOrConnection)` method, which you were calling before as per the initial comment on this page. 

Check the [code](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L206-L218) to understand this.

For the last 2 snippets, both achieve the same result. The `resetPassword` method already [sets the connection](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L728) for you. Unless the value you pass is different, calling it again will not have any effect.

I suggest you read the [API docs](https://auth0.com/docs/api/authentication) for accepted parameters on each endpoint and if you want to play further, [enable the logging](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L246-L254) of HTTP requests to inspect them. Remember this shouldn't be turned ON for production apps.

**Comment by GabCast** [comment]
I understand and tried with both flows: OIDC true with realm and OIDC false with connection and the error still.

OIDC true:

```
 auth0 = Auth0(it)
 auth0.isOIDCConformant = true

        AuthenticationAPIClient(account)
                .login(emailId, password, REALM)
                .setScope(config.scope)
                .setAudience(config.audience)
                .start(baseCallback)
```

OIDC false

```
 auth0 = Auth0(it)
 auth0.isOIDCConformant = false

        AuthenticationAPIClient(account)
                .login(emailId, password, CONNECTION)
                .setGrantType(GRANT_TYPE_PASSWORD)
                .start(baseCallback)
```

We are using native SDK and not the WebAuthProvider, every sample we have seen is with WebAuthProvider, do you have any sample with native implementation?

Reset password case: We have read the documentation, set client_id and domain (correctly, the others SDK functions works) but resetPassword still throwing connection not found...


For both cases this error might be a wrong configuration in our dashboard?

Thank you for your help!

**Comment by GabCast** [comment]
Hey @lbalmaceda we just figured out what was wrong in our configuration. Thank you for your help, you were a life saver!!

**Comment by BesatZardoshtCarfax** [comment]
> configuration



> Hey @lbalmaceda we just figured out what was wrong in our configuration. Thank you for your help, you were a life saver!!

Would you please share how you solved the issue? I have the same problem. I really appreciate it :)

**Comment by GabCast** [comment]
> > configuration
> 
> > Hey @lbalmaceda we just figured out what was wrong in our configuration. Thank you for your help, you were a life saver!!
> 
> Would you please share how you solved the issue? I have the same problem. I really appreciate it :)

Hey @BesatZardoshtCarfax  we were mixing realm and connection types and our connection string was misspelled. We use OIDC format so our connection was actually realm: 

```
AuthenticationAPIClient(account)
                .login(emailId, password, config.realm)
                .setScope(config.scope)
                .setAudience(config.audience)
                .start(baseCallback)
```
Make sure you have OIDC switch activated in your dashboard. The flow is case sensitive (this is what was wrong with us) so make sure you hace the right string. 

Hope it helps 💯
