### ISSUE TITLE
Problem with Sign up using AuthenticationAPIClient

### ISSUE THREAD

**Issue by BesatZardoshtCarfax** [auth0/Auth0.Android#304]
### Description

I have an issue with signing up and logging in using Auth0 in Android using AuthenticationAPIClient.

```
val clientId = "my_client_id"
val domain = "my_domain"
val email = "myemail@email.com"
val password = "myPassword"
val connection = "my_email_connection"
val account: Auth0 = Auth0(clientId, domain)
val authenticationAPIClient = AuthenticationAPIClient(account)
authenticationAPIClient.signUp(email, password, connection).start(signUpCallback)
```

I will get this error first time I try to sign up:

![Screen Shot 2020-05-25 at 11 34 45 AM](https://user-images.githubusercontent.com/52752909/82826836-de8a6800-9e7b-11ea-9dc8-254051bd551a.png)

And I will get this error if I try to sign up with same email:

![Screen Shot 2020-05-25 at 11 35 10 AM](https://user-images.githubusercontent.com/52752909/82826819-d5010000-9e7b-11ea-80af-e838c9c4d6a5.png)

### Environment

implementation 'com.auth0.android:auth0:1.23.0'

**Comment by BesatZardoshtCarfax** [comment]
I just realized that sign up has been successful (the user has been created in the database) but login after create user is failing.. 
In Summary sign up is create user + login and the second part is failing for some reason!

**Comment by lbalmaceda** [comment]
@BesatZardoshtCarfax 👋 it seems you're not setting the OIDC flag to the Auth0 object. This is required for tenants that are on the new pipeline. You can read about this migration [here](https://auth0.com/docs/api-auth/tutorials/adoption) and how to toggle the flag on the SDK here: https://github.com/auth0/Auth0.Android#oidc-conformant-mode. 

If you were following a quickstart or guide, can you please share the link? So we update the documentation. Thanks

**Comment by BesatZardoshtCarfax** [comment]
Thanks so much.. That was the issue
