### ISSUE TITLE
An error occurred while trying to use the Refresh Token to renew the Credentials.

### ISSUE THREAD

**Issue by stephen1706** [auth0/Auth0.Android#305]
When calling `SecureCredentialsManager.getCredentials`, when access token has expired, and it is trying to renew access token using the existing refresh token, it will call an `onFailure` and return an error cause of `AuthenticationException`
 
error.message : An error occurred while trying to use the Refresh Token to renew the Credentials.
error.cause.message | Request failed
error.cause.code | a0.sdk.internal_error.unknown
error.cause.description | Received error with code a0.sdk.internal_error.unknown

### Reproduction

It is reproducible if we disable network and call `SecureCredentialsManager.getCredentials` when access token has expired. However, It is happening intermittently that some users cannot refresh their token, not sure if it is purely from network issue or not, as the occurrence in production is really high, I doubt that network issue is the only cause of it. Is there any other possible cause other than network issues?

### Environment

- **Version of this library used:**
`'com.auth0.android:auth0:1.23.0'`
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
It is happening on all type of device and OS level
- **Other modules/plugins/libraries that might be involved:**

**Comment by stephen1706** [comment]
@lbalmaceda as of now, we cannot find any relevant token exchange log at Auth0 dashboard for this refresh token

**Comment by lbalmaceda** [comment]
@stephen1706 enable logs on the SDK and try to reproduce the error. Share the server response with us so we can check what error code is not being mapped correctly. Remember to strip any sensitive information such as passwords and to not ship your app to production with the logs enabled.

**Comment by stephen1706** [comment]
@lbalmaceda this is the logs from the Android Auth0 SDK: 

causedBy | Request failed
code | a0.sdk.internal_error.unknown
description | Received error with code a0.sdk.internal_error.unknown
isNetworkError | true
methodName | awaitCallback
statusCode | 0

It is weird that there are so many events like this stating `isNetworkError` is true, is there any other possible reason that might have caused this, other than user actually don't have any internet connection? Because the numbers are very high and unlikely most of them don't have internet connection

**Comment by lbalmaceda** [comment]
@stephen1706 it's difficult to tell without the full stack trace. But yes, an `IOException` is the [only reason](https://github.com/auth0/Auth0.Android/blob/0141418e5b9e0380e53d110afa093304c33e5e08/auth0/src/main/java/com/auth0/android/request/internal/SimpleRequest.java#L102) a `NetworkErrorException` would get raised. Not having an internet connection is not the only case. It could be a slow connection that times out, for example. Or the use of a proxy that forbids your app from reaching that address. You'd have to log that wrapped `IOException` cause to understand the reason.

If this is because of timeout you can tweak the values [with these](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L274-L299) methods.

**Comment by stephen1706** [comment]
@lbalmaceda ok, I will log the whole stacktrace to get a better detail of the error during my next release. For the timeout, what is the default value for connect, read, and write set by the Auth0 SDK?

**Comment by lbalmaceda** [comment]
Ah, good call I'll document them in those javadocs. The defaults are the ones set by OkHttp. They are 10 secs each, see the test covering that here https://github.com/auth0/Auth0.Android/blob/c366618caeb5fb5d08ba58d0719b8d9932bd31cb/auth0/src/test/java/com/auth0/android/request/internal/OkHttpClientFactoryTest.java#L66-L69

**Comment by stephen1706** [comment]
Hi @lbalmaceda, so I have obtained a full stack trace of the error, it looks like a pure network error.

> 
> CredentialsManagerException
> An error occurred while trying to use the Refresh Token to renew the Credentials.
> com.auth0.android.authentication.storage.SecureCredentialsManager$1 in onFailure at line 282
> com.auth0.android.authentication.storage.SecureCredentialsManager$1 in onSuccess at line 269
> com.auth0.android.authentication.storage.SecureCredentialsManager$1 in onFailure at line 269
> com.auth0.android.request.internal.BaseRequest in postOnFailure at line 97
> com.auth0.android.request.internal.BaseRequest in onFailure at line 151
> com.newrelic.agent.android.instrumentation.okhttp2.CallbackExtension in onFailure at line 34
> com.squareup.okhttp.Call$AsyncCall in execute at line 185
> com.squareup.okhttp.internal.NamedRunnable in run at line 33
> java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
> java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
> java.lang.Thread in run at line 764
> AuthenticationException
> Request failed
> com.auth0.android.request.internal.AuthenticationErrorBuilder in from at line 18
> com.auth0.android.request.internal.AuthenticationErrorBuilder in from at line 9
> 2
> com.auth0.android.request.internal.BaseRequest in onFailure at line 151
> com.newrelic.agent.android.instrumentation.okhttp2.CallbackExtension in onFailure at line 34
> com.squareup.okhttp.Call$AsyncCall in execute at line 185
> com.squareup.okhttp.internal.NamedRunnable in run at line 33
> java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
> java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
> java.lang.Thread in run at line 764
> NetworkErrorException
> Failed to execute the network request
> com.auth0.android.request.internal.BaseRequest in onFailure at line 151
> com.newrelic.agent.android.instrumentation.okhttp2.CallbackExtension in onFailure at line 34
> com.squareup.okhttp.Call$AsyncCall in execute at line 185
> com.squareup.okhttp.internal.NamedRunnable in run at line 33
> java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
> java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
> java.lang.Thread in run at line 764
> SocketTimeoutException
> failed to connect to auth.fairprice.com.sg/54.192.150.79 (port 443) from /192.168.1.129 (port 39552) after 10000ms
> libcore.io.IoBridge in connectErrno at line 185
> libcore.io.IoBridge in connect at line 129
> java.net.PlainSocketImpl in socketConnect at line 137
> java.net.AbstractPlainSocketImpl in doConnect at line 390
> java.net.AbstractPlainSocketImpl in connectToAddress at line 230
> java.net.AbstractPlainSocketImpl in connect at line 212
> java.net.SocksSocketImpl in connect at line 436
> java.net.Socket in connect at line 621
> com.squareup.okhttp.internal.Platform$Android in connectSocket at line 230
> com.squareup.okhttp.internal.io.RealConnection in connectSocket at line 141
> com.squareup.okhttp.internal.io.RealConnection in connect at line 112
> com.squareup.okhttp.internal.http.StreamAllocation in findConnection at line 184
> com.squareup.okhttp.internal.http.StreamAllocation in findHealthyConnection at line 126
> com.squareup.okhttp.internal.http.StreamAllocation in newStream at line 95
> com.squareup.okhttp.internal.http.HttpEngine in connect at line 281
> com.squareup.okhttp.internal.http.HttpEngine in sendRequest at line 224
> com.squareup.okhttp.Call in getResponse at line 286
> com.squareup.okhttp.Call$ApplicationInterceptorChain in proceed at line 243
> com.squareup.okhttp.Call in getResponseWithInterceptorChain at line 205
> com.squareup.okhttp.Call in access$100 at line 35
> com.squareup.okhttp.Call$AsyncCall in execute at line 171
> com.squareup.okhttp.internal.NamedRunnable in run at line 33
> java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
> java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
> java.lang.Thread in run at line 764

And the `online` field is returning false at the device detail. Is this a pure network fail issue?

**Comment by lbalmaceda** [comment]
It looks like, yes. `SocketTimeoutException` means the connection was made but the expected packets were not delivered in time. If this was an issue establishing the connection you'd have seen a `ConnectTimeoutException` instead. 

Maybe the device where this was experienced was running through a proxy or VPN? I don't think that's measurable, though.

**Comment by stephen1706** [comment]
@lbalmaceda the issue is very prevalent in our user, so I don't think it is an issue using proxy or VPN. I have added a manual retry in performing `getCredentials` in case there is a `NetworkErrorException` thrown at `onFailure`. I'll keep you updated if there is any new relevant data in the future.
Thank you

**Comment by lbalmaceda** [comment]
Friendly check-in. Did that retry operation work? How many users have this issue today, if still an issue?

**Comment by stephen1706** [comment]
@lbalmaceda after we do the retry operation, the users who got logged out is decreasing. thanks for the support

**Comment by lbalmaceda** [comment]
Remember you can also try increasing the timeout values as I mentioned earlier. I'm happy it's getting better now. 👍

**Comment by SarahSami** [comment]
@lbalmaceda  I have the same problem and it happens randomly while user has Internet connection
here is stack trace

`2020-10-22 11:04:27.276 15782-15782/W/ErrorExtentionsKt: Caused by: com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.

W/FirebasePerformance: Unable to process the PerfMetric due to missing or invalid values. See earlier log statements for additional information on the specific missing/invalid values.
2020-10-22 11:04:28.129 15782-15782/com.lepaya.app.dev W/ErrorExtentionsKt: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lepaya.app.ui.network.RequestLoggingInterceptor.intercept(RequestLoggingInterceptor.kt:19)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.lepaya.app.ui.network.Auth0Authority.intercept(Auth0Authority.kt:24)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(com.google.firebase:firebase-perf@@18.0.1:5)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:10955)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:10955)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by RuiRoque** [comment]
I also have this problem in 1.30.0.

For testing, I've setup the token expiration in 20 seconds and I'm requesting a new token renewal in every request.

What happens is, when the token expires, I get this exception. So I've put a retry mechanism (3 times with 1 second delay). And it works for the first renewal: as the renewal request fails, in the first retry it will get the credentials and a new token. But the problem is that after another 20 more seconds, when the token expires again, it will fail all 3 times with this exception.

Is there any throttling in the credentials request that can be causing this? Because when the token expires, I have multiple requests being fired from the app with an invalid token, and all of those requests try to renew the token.

**Comment by devzeze** [comment]
Same here with version: 'com.auth0.android:auth0:2.7.0'

Is this the expected response when **Refresh** token espires? 
Note that on SecureCredentialsManager before call getCredentials method I check if hasValidCredentials method.

In this case doesn't matter how many retries are performed, always same response. 
I assume here response is OK, what I would expect is that hasValidCredentials method would return false in this scenario.

**Comment by cooperkong** [comment]
same thing happening with 2.11.0, about 0.1% of the user constantly getting this issue. When they get it they are logged out of the app which is a bad experience.

**Comment by DhanushprabhuS** [comment]
/// Fetch the latest access token if it's expired or refreshed
  Future<String> _refreshAccessTokenIfNeeded(String oldToken, String refreshToken) async {
  debugPrint("☑️ Checking access token");

  if (!isTokenExpired(oldToken)) {
    debugPrint("✅ Access token is still valid.");
    return oldToken;
  }

  debugPrint("🔄 Access token is expired or about to expire. Refreshing...");

  try {
    final val = await _auth0.credentialsManager.hasValidCredentials();
    debugPrint("😶‍🌫️ ${val.toString()}");
    final result = await _auth0.credentialsManager.credentials();
    
    //final credentials = await _auth0.
    debugPrint("Credentials retrieved successfully: ${result.accessToken}");
    if (result.accessToken != oldToken) {
      debugPrint("✨ Access token updated, storing the new one.");
      return result.accessToken;
    }
  } catch (e) {
    
    debugPrint("Error refreshing access token: $e");

    // Handle specific errors
    if (e is ApiException) {
      debugPrint("API Error: ${e.statusCode} - ${e.message}");
      if (e.statusCode == 401) {
        debugPrint("Refresh token is invalid or expired. Logging out user...");
        await logout();
      }
    }
  }

  return oldToken; // Return the old token if there's no update
}


I am trying to update the access token and getting the below error can someone help me on this

 An error occurred while trying to use the Refresh Token to renew the Credentials!

**Comment by pmathew92** [comment]
Hi @DhanushprabhuS  , 
Could you check if your refresh token is valid or not ? Ideally the lifetime of the refresh token should be more than the access token configured in the manage dashboard

**Comment by DhanushprabhuS** [comment]
> Hi [@DhanushprabhuS](https://github.com/DhanushprabhuS) , Could you check if your refresh token is valid or not ? Ideally the lifetime of the refresh token should be more than the access token configured in the manage dashboard Also what is the status code you are getting when this error occurs ?

Hi @pmathew92  Thank you for you reply. I have checked it. I has been enforcing MFA for all actions so it can't able to renew the access token. I have made the changes now it is working fine.

Thank you! 😊

**Comment by gtsak1** [comment]
Hi @pmathew92.

I also get "Unknown or invalid refresh token" (403 error) when calling getCredentials() method (regardless of the library version). This does not happen all the time.

In our app we first make our internal call /accountDetails and if this call returns 400 or 401, then we try to obtain new Auth0 Id with getCredentials(). This is what we get sometimes (403 renew_failed error):

![Image](https://github.com/user-attachments/assets/ef0a0a67-a9f3-4802-a244-9432436a5180)

I had managed to solve the issue by increasing the timeout values based on @lbalmaceda' s recommendation:

account = Auth0.getInstance(BuildConfig.AUTH0_CLIENT_ID, BuildConfig.AUTH0_DOMAIN)
val netClient = DefaultClient(60, 60, HashMap(), BuildConfig.DEBUG)
account.networkingClient = netClient

But a few days ago the problem reappeared. Is there a workaround for this and what causes this to happen? Our iOS app follows the exact same steps and credentials call succeeds. 

For testing, id token expiration has been set to 900 sec and reuse interval is set to 300sec for refresh token rotation.

Please for your input on this, as we get constant complaints for user logout due to token renewal failure.

**Comment by pmathew92** [comment]
Hi @gtsak1 , The above error is thrown when the refresh toke used to get a new access token is either expired or invalid. Since you are using a rotating refresh token, are you sure you are sending the newly obtained token as part of the new request ? Also could you check what does your management dash board logs say when you hit this error ?

**Comment by gtsak1** [comment]
Hi @pmathew92. Eventually, there was an issue with the refresh token we were using. getCredentials() is working fine now. Thanks for your support anyway.
