### ISSUE TITLE
NPE in SecureCredentialsManager.getCredentials

### ISSUE THREAD

**Issue by iancboswell** [auth0/Auth0.Android#309]
### Description

My app experienced a strange series of crashes last night, all due to a NPE in getCredentials. Here's the stack trace:

```
java.lang.NullPointerException · chain == null
KeyStore.java:1206java.security.KeyStore$PrivateKeyEntry.<init>
KeyStoreSpi.java:374java.security.KeyStoreSpi.engineGetEntry
KeyStore.java:645java.security.KeyStore.getEntry
CryptoUtil.java:151com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat
CryptoUtil.java:88com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry
CryptoUtil.java:200com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt
CryptoUtil.java:228com.auth0.android.authentication.storage.CryptoUtil.getAESKey
CryptoUtil.java:241com.auth0.android.authentication.storage.CryptoUtil.decrypt
SecureCredentialsManager.java:208com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials
SecureCredentialsManager.java:175com.auth0.android.authentication.storage.SecureCredentialsManager.getCredentials
```

### Reproduction

Unfortunately I have no idea why this happened or how it could be reproduced. The app code that calls `getCredentials` has been working in production for some time and hasn't been changed recently.

### Environment

- Auth0 library version: 1.15.0
- Android version: 6.0.1
- Language: Java, some Kotlin
- Other libraries: Gson, OKHttp, Google Play

**Comment by iancboswell** [comment]
Actually, a couple of earlier crashes might be related. These happened a couple days before the one above.

```
 java.lang.IllegalArgumentException · key.length == 0
SecretKeySpec.java:62javax.crypto.spec.SecretKeySpec.<init>
CryptoUtil.java:241com.auth0.android.authentication.storage.CryptoUtil.decrypt
SecureCredentialsManager.java:208com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials
SecureCredentialsManager.java:175com.auth0.android.authentication.storage.SecureCredentialsManager.getCredentials
```

```
 com.auth0.android.authentication.storage.CredentialsManagerException · An error occurred while encrypting the credentials.
SecureCredentialsManager.java:152com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials
```

I haven't encountered these before, either.

**Comment by lbalmaceda** [comment]
I found [this](https://stackoverflow.com/questions/23977407/android-4-3-keystore-chain-null-while-trying-to-retrieve-keys) where it mentions that apparently the key alias is meant to be unique in android version 4.3. Today, that name is not customizable as it's being hardcoded [here](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L44). 

Are you aware of that device having other apps using this same utility class?

We could start prefixing the key alias with the app's package name, for example. That would imply though that your app's next release will not find the previously generated keys and perform a clear and re-create operation. Probably failing on that first call.

**Comment by iancboswell** [comment]
Interesting. As far as I know, this is the only app on that device using the Auth0 library. That does sound like a reasonable fix, if that's what's going on. I've already added some logic to check for exceptions around these calls, so that would be all right regarding the next release.

**Comment by lbalmaceda** [comment]
Makes sense. I'm tracking this internally under `SDK-1764 `, and expect to work on it sometime in the next 2 weeks.

**Comment by iancboswell** [comment]
Excellent. Thanks for the quick response!

**Comment by iancboswell** [comment]
An update on my original issue. I was able to get my hands on the phone in question. I tried a number of things, but after clearing my app's data through the application manager, the `chain == null` issue wasn't happening anymore. To me, this implies that something else may have been going on rather than another app installed using the same key alias.

**Comment by iancboswell** [comment]
Another comment on that SO question mentions async operations causing this situation sometimes. I do have some async code in the part of the app where this crash happened, so I'm wondering if an edge case caused by async put the keystore in a bad state, which was only fixed through clearing data. What baffles me is that this is the first time that this has happened, and this code has run in production for a while on multiple phones without issue.

**Comment by lbalmaceda** [comment]
what kind of operation are you doing in that async code? Is that interacting with the Keystore in some way?

**Comment by iancboswell** [comment]
I'm calling `SecureCredentialsManager.getCredentials` or `SecureCredentialsManager.saveCredentials`. As far as I know I have this set up to not do this multiple times/simultaneously, but there could be a bug that could cause that to happen.

**Comment by lbalmaceda** [comment]
@iancboswell I don't know. To be honest I haven't tested this in that scenario. How I test this is having a "login activity" that checks if there are valid credentials stored or not before calling `setContent` so that I can close the activity and launch the "main activity" if the user is already logged in. That second activity is the one that would call `getCredentials`. I understand that any error at that point (existing credentials) would mean a temporary issue that a retry operation could resolve. But I haven't faced any other issues. That said, I don't have a big pool of devices to test this, so any feedback with reproduceable steps is appreciated.

**Comment by iancboswell** [comment]
Yeah, this has been an odd bug that I haven't been able to reproduce. I'll let you know if I am able to get it to reliably happen.
