### ISSUE TITLE
AuthenticationAPIClient Request Header

### ISSUE THREAD

**Issue by vrickey123** [auth0/Auth0.Android#314]
### Describe the problem you'd like to have solved

I would like to add a HTTP Request Header to an `AuthenticationApiClient` request like a delegation call, but the `AuthenticationApiClient` doesn't provide an API to do so.

### Describe the ideal solution

The `Authentication` constructor in [the iOS SDK](https://github.com/auth0/Auth0.swift/blob/3547cee87a071227322ba3e7d8e700ec1e835846/Auth0/Authentication.swift#L35) allows you to pass in a `URLSession` that can implement `URLSessionConfiguration.default.httpAdditionalHeaders = ...`

The [Android SDK](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L137) has a `AuthenticationAPIClient(Auth0 auth0, RequestFactory factory, OkHttpClientFactory clientFactory)` constructor which could surface similar functionality, but it is package private.

## Alternatives and current work-arounds

In order to add an HTTP Header to an `AuthenticationApiClient` request, like a delegation call, you must subclass `AuthenticationApiClient` and add a `OkHttpRequestInterceptor`.

**Comment by lbalmaceda** [comment]
Thanks for suggesting that change. We're tracking this internally as `SDK-1791`. 
Today, as a workaround and only for those Requests that implement the `ParameterizableRequest` interface, you can call the `addHeader ` method. Note that not all requests implement this interface.

Is there any specific method you'd like this on?

**Comment by vrickey123** [comment]
Thanks. Yes, our use case requires support for `authApiClient.delegationWithRefreshToken(refreshToken)`.

Does that API fall under your suggested workaround or is it best just to wait for the update? This is not necessary urgent for us so we'd prefer a clean SDK implementation over unnecessary hacks.

**Comment by lbalmaceda** [comment]
No, unfortunately for that one there's no current workaround.

**Comment by vrickey123** [comment]
Thanks, I came to the same conclusion... In that case, we'll wait for your fix. In terms of your roadmap, is this something in your next sprint or the icebox? How can we track `SDK-1791`. Feel free to link me to a README if I missed something.

**Comment by lbalmaceda** [comment]
We're tracking it in our backlog, but that's internal. However, I'm confident this feature could be delivered sometime around the coming 2 weeks. I'll keep this issue open until it's added and post here any updates.

**Comment by vrickey123** [comment]
Excellent, that's doable. Thanks for the great support!

**Comment by vrickey123** [comment]
Hi @lbalmaceda, a coworker mentioned to me that we're also interested in this functionality for the `renewAuthentication` API after migrate off of `delegationWithRefreshToken`. I'm not sure if it's already supported or how you plan to implement the feature, but I'll put it on your team's radar. Thanks.

**Comment by HuaiYuanMike** [comment]
I believe `AuthenticationAPIClient#renewAuth()` returns a `ParameterizableRequest`, which means the workaround @lbalmaceda mentioned earlier works. However, at the moment we are still using `delegationWithRefreshToken()`, which means the workaround doesn't work and we need the change this issue suggests.

**Comment by lbalmaceda** [comment]
Should be available on 1.24.0

**Comment by vrickey123** [comment]
@lbalmaceda Thanks! We'll report back if we notice anything.
