### ISSUE TITLE
Documentation: Callbacks might be executed on background thread

### ISSUE THREAD

**Issue by dsuresh-ap** [auth0/Auth0.Android#316]
### Describe the problem you'd like to have solved

The documentation in the READMe do not suggest that the callbacks might be executed on a background thread. Looking into `BaseRequest.java`, OkHttp's callbacks and checking if the `onSuccess(credentials: Credentials)` is actually called on the main thread show that it could be executed on a background thread.

### Describe the ideal solution

Update the documentation to mention threading.
Ex:
```
authentication
    .login("info@auth0.com", "a secret password", "my-database-connection")
    .setScope("openid offline_access")
    .start(activity, new BaseCallback<Credentials, AuthenticationException>() {
        @Override
        public void onSuccess(Credentials payload) {
            //Save the credentials
            manager.saveCredentials(credentials);
            activity.runOnUiThread { //Update UI }
        }

        @Override
        public void onFailure(AuthenticationException error) {
            //Error!
            activity.runOnUiThread { //Update UI }
        }
    });
```

**Comment by lbalmaceda** [comment]
I agree. Probably by the end of this section https://github.com/auth0/Auth0.Android#authentication-with-universal-login and the logout one. 
Would you send a PR to update the readme?

**Comment by dsuresh-ap** [comment]
@lbalmaceda Created a PR. Feel free to modify it. However looking at the rest of the README I think it would be better if the code was changed to call the callback functions on the main thread since there are a lot of different callback examples.

**Comment by lbalmaceda** [comment]
Merged. Thanks for raising this 🎉
