### ISSUE TITLE
1.24.0 crashes Lock.Android

### ISSUE THREAD

**Issue by barzoj** [auth0/Auth0.Android#321]
### Description

53582861da072f82c9655fae61e4016e1d160fac breaks compatibility with the latest Lock.Android library, app crashes immediately after login attempt.

here is the traceback:

`java.lang.NoSuchMethodError: No virtual method login(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/auth0/android/request/AuthenticationRequest; in class Lcom/auth0/android/authentication/AuthenticationAPIClient; or its super classes (declaration of 'com.auth0.android.authentication.AuthenticationAPIClient' appears in /data/app/***.*******.*****-J2m2ju-jHLGkO-5x7sj5Ig==/base.apk)
        at com.auth0.android.lock.LockActivity.onDatabaseAuthenticationRequest(LockActivity.java:390)` 

Lock expects `login` method to return `AuthenticationRequest`, not `AuthRequest`.

**Comment by lbalmaceda** [comment]
I'm putting up a release of `Lock.Android` with the bump on the SDK version. You'll find it available in the coming hours as `2.21.0`.
