### ISSUE TITLE
Can require authentication dynamically after login?

### ISSUE THREAD

**Issue by miabanana** [auth0/Auth0.Android#342]
### Description

Hello, 

Is there a way to require authentication (like read contacts authentication) dynamically? 
I use social sign in without `connectionScope` to requesting permission, and want to add `connectionScope` to require user for some particular authentication when needed.

Or is there a way to enforce email address through calling `WebAuthProvider.login()`?

### Environment

- **Version of this library used:**
com.auth0.android:auth0:1.22.1, 
com.auth0.android: lock:2.17.1, 
com.auth0.android:jwtdecode:2.0.0

- **Other relevant versions (language, server software, OS, browser):**
Android

**Comment by lbalmaceda** [comment]
The details that you receive depend both on the `scope` you ask and the connection that you are using. 

I'd try first asking for `openid profile email` as scope. See https://github.com/auth0/Auth0.Android#specify-scope

**Comment by miabanana** [comment]
This is the `scope` that I use for login: `"openid profile email id offline_access"`. 

When get google contacts the `scope` is not enough, a `connectionScope` need to be added: `val googleConnectionScope: String = "https://www.googleapis.com/auth/contacts.readonly"`. 

For user experience I don't want to log user out and make them log back again.

In web version there's [`checkSession()` that enables get authentication dynamically](https://auth0.com/docs/libraries/auth0js?_ga=2.240724611.1203528185.1600154951-1350203260.1600154951#using-checksession-to-acquire-new-tokens). So I wonder is there any thing like this with Android?

**Comment by lbalmaceda** [comment]
No, none of the mobile SDKs have the equivalent to `checkSession`. 

The `scope` applies to Auth0 server. The `connectionScope` is passed unmodified to the external identity provider, google in this case. 

We do have [credential managers](https://github.com/auth0/Auth0.Android#credentials-manager) that when used to store a pair of credentials, can keep them valid by refreshing them when required using the refresh token. However, as far as I know, the access token returned by Auth0 is only to be used against Auth0. So if you want to authenticate with Google and get a specific "Google scope" to call the "Google APIs", using the credentials manager won't work for you.

This is the article that I could find that explains how to consume external identity provider's token with Auth0: https://auth0.com/docs/connections/calling-an-external-idp-api#from-the-frontend

**Comment by miabanana** [comment]
Thank you for the reply and help on this.

I found a way to do it dynamically by calling `WebAuthProvider.login(account)` and add parameter `("login_hint", userEmail)` to it, and what's needed to `connectionScope`.

This way I can specify a specific user to require permission dynamically.

**Comment by lbalmaceda** [comment]
Glad you were able to solve it. 🎉
