### ISSUE TITLE
Forgot Password Redirection

### ISSUE THREAD

**Issue by sonusurender** [auth0/Auth0.Android#348]
Hi,

I want to redirect user to some other screen when the user selects Forgot password from the SSO screen. I couldn't found any example or document for it. 

Can you tell me it is possible? If yes, then how?

Thanks

**Comment by lbalmaceda** [comment]
@sonusurender What you are seeing in the browser is outside of this SDK's knowledge. I think your question is related to the login page template used in the Universal Login. There are ways to customize it or choose a different experience, e.g. https://auth0.com/docs/universal-login/universal-login-page-customization. 

The answer to your question is "it depends", it depends how much of that template you are willing to code yourself and maintain overtime vs using a "universal" solution with a few styling and theming options like Universal Login. Anyway, this is not an SDK issue so I'm closing this. But happy to continue chatting as long as I can help 👋
