### ISSUE TITLE
Get time from Clock [SDK-1973]

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#350]
### Describe the problem you'd like to have solved

We're using a NTP library to get the current time. 

### Describe the ideal solution

Get current time from a `java.time.Clock` instance instead of `System.currentTimeMillis()`. Probably unit-testing will be more simple as well.

## Alternatives and current work-arounds

Subclassing and/or cloning classes. Explicitly passing in the current time to methods.

### Additional context

[SecureCredentialsManager](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java)

**Comment by lbalmaceda** [comment]
That would be ideal, but the `java.time.Clock` class [does not seem to be available](https://developer.android.com/reference/java/time/Clock) until Android API 26, and this library targets as min API 15. We plan to raise this minimum but is not going to be 26, unfortunately. I guess we could go with a solution like the one [java-jwt has](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L193-L196).

The only reason to push back on a change that will let the developer pass the Clock instance is that you can put as much documentation and warning flags as you want, but anyone could still mistakenly use it and break the application.

**Comment by skjolber** [comment]
We are going to have consumer apps, and can not controll their internal clock, and we know from experience that some of them are off (by minutes or more). So the plan is to use an NTP library to get the correct current time, so that the app is unaffected by the time skew.

I missed that backwards compatible target - then `java.time.Clock` is not going to work. The java-jwt approach is a good alternative.

**Comment by lbalmaceda** [comment]
I think the java-jwt solution is an easy path forward. I need to evaluate if this can be set in a global way, maybe through the `Auth0` object, so it can also be considered when validating ID tokens, for example. 

I'm tracking this as `SDK-1973`.
