### ISSUE TITLE
Ability to inject OkHttpClientFactory (currently only `@VisibleForTesting`)

### ISSUE THREAD

**Issue by rubencagnie-toast** [auth0/Auth0.Android#352]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We'd like to manipulate the HTTP requests coming out of Auth0, so we can automate our UI testing. We want to be able to stub out a certain response without having to maintain the credentials. On iOS this is possible to this through injecting `URLSession` in the Auth0 `authentication` initializer 

### Describe the ideal solution

Ability to inject the OkHttpClientFactory, so interceptors could be registered

## Alternatives and current work-arounds

Not that I know of. If there is anything, that would be great!

### Additional context

The main goal is to automate the UI Testing, but having the ability to control the behavior of the network

**Comment by rubencagnie-toast** [comment]
Small update: I was able to call this function using mirroring. Obviously this is not desirable, but it's working for the time being
```
AuthenticationAPIClient::class.java.declaredConstructors.filter { it.parameterCount == 3 }.first()?.let {
  it.isAccessible = true
  val client = it.newInstance(auth0, RequestFactory(), interceptor) as AuthenticationAPIClient
  ...
```

**Comment by lbalmaceda** [comment]
agh. Sure using _java reflection_ will do the trick, but there's a reason why that's not part of the public API of this SDK. It all comes down to our internal implementation changing and breaking your app. If you use it, keep that in mind as we won't provide support for you in this case.

Back to the feature request, it's one of the core features the next version will have. We're still in the planning phase and there's no ETA date to share externally.
