### ISSUE TITLE
Instant App fails due to missing android:scheme="http" in Manifest

### ISSUE THREAD

**Issue by rai2270** [auth0/Auth0.Android#360]
### Description

> Instant App bundle creation fails due to missing http scheme.

### Reproduction

> Use Auth0 in app. Create bundle. Push to Play Store. Error message: "You should use both http and https as schemes for your web intent-filters". 
Took me a few hours to find out this is related to Auth0 Manifest.
When checking source code I found only "https":
<data android:scheme="https"...

### Solution

> Please add to Manifest also: <data android:scheme="http" ...

**Comment by lbalmaceda** [comment]
@rai2270 I was not aware of this requirement, but good to know for future reference. 

This SDK declares an intent-filter for handling links that use https and have the verification enabled. This is to support App Links easily out of the box. However, the scheme can be changed via a user-provided parameter (the manifest placeholder), so we can't just add "http" to the default list of accepted schemes as those not using this feature would receive the change and might break their login flow experience. e.g. showing the disambiguation dialog when using custom schemes other than "https".

If you need to accept both `https` and `http` I suggest that you override the intent-filter declaration by re-declaring the activity in your manifest. See [this section](https://github.com/auth0/Auth0.Android#authentication-with-universal-login) of the readme where it talks about "Alternatively, you can declare the RedirectActivity in the AndroidManifest.xml" for guidance.
