### ISSUE TITLE
Google Sign-in native support.

### ISSUE THREAD

**Issue by zhukic** [auth0/Auth0.Android#367]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com.).

### Description

Description of the bug or feature request and why it's a problem. Consider including:

- The use case or overall problem you're trying to solve
- Information about when the problem started

### Prerequisites

- [x] I have checked the [documentation](https://auth0.com/docs/libraries/auth0-android) for this library.

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/Auth0.Android/issues) and [PRs](https://github.com/auth0/Auth0.Android/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.Android used: 1.28.0
- Version of Android being used: any
- Additional packages that might be affecting your instance:

### Description

Hello!

Currently I'm trying to implement Sign-in with Google in my Android app. The only way I see right now is to use `WebAuthProvider` with "google-oauth2" connection which works over `WebView`. But it would be great to have [native](https://developers.google.com/identity/sign-in/android/start) Google Sign-in for better user experience. 

Is there any way to exchange Google token for Auth0 access and id tokens? I tried to implement it through `AuthenticationAPIClient.loginWithOAuthAccessToken(googleToken, "google-oauth2")` or `AuthenticationAPIClient.loginWithNativeSocialToken` but Auth0 api internally returns 4xx error codes.

Thanks!

**Comment by lbalmaceda** [comment]
@zhukic The WebAuthProvider, as its name suggest, makes use of a web-auth flow to authenticate you. To clarify "Webview" (the component) is not recommended and actually will have OAuth requests blocked. See our [blogpost](https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/) about that.

Regarding your inquiry, "native" Google Sign-In (through Google's SDK) is not currently supported. The server side needs to support that provider token type first. Currently, the supported ones are Apple and Facebook. You can check the quickstart for both https://auth0.com/docs/quickstart/native. You can fill a _product request_ [here](https://auth0.com/feedback).

**Comment by zhukic** [comment]
@lbalmaceda Thank you the quick reply!

**Comment by agusvazquez** [comment]
Hello people!  Hope you are having a great day!

I just wanted to ask if there are plans for implementing this provider like you did with Apple Sign In here
https://auth0.com/docs/authenticate/identity-providers/social-identity-providers/apple-native

Basically the solution would be to send Google Sign In `id_token` to Auth0 and retrieve the access token. 

Is that possible now? If not, are you planning to release it? Is there any estimated time?

Thank you!!!

**Comment by qsdigor** [comment]
I need as well some option to integrate native google login with auth0 token exchange. I see it works for facebook but it would be nice to have it for google as well with auth0 `loginWithNativeSocialToken` option and custom token and tokenType.
