### ISSUE TITLE
Invalid grant type on renewAuth with refresh token.

### ISSUE THREAD

**Issue by long-greg-c** [auth0/Auth0.Android#48]
Tried new ```renewAuth(refreshtoken)``` method [added](https://github.com/auth0/Auth0.Android/pull/43) in release 1.2.0.

AuthenticationException code is ```unsupported_grant_type```, exception description is ```Unsupported grant type: refresh_token```.

**Comment by lbalmaceda** [comment]
Hi @long-greg-c 
We're still working on the new flow. Meanwhile if you want to give it a try check that you have enabled it in your settings.
1. Go to https://manage.auth0.com/
2. Click the upper right corner button and select _Account Settings_.
3. Go to _Advanced_.
4. Enable the `OAuth 2.0 API Authorization` switch.

![image](https://cloud.githubusercontent.com/assets/3900123/20795533/6be79242-b7b0-11e6-9f35-9aaf6c86c866.png)

Cheers.
