### ISSUE TITLE
`BaseRequest` uses `Charset.defaultCharset()`

### ISSUE THREAD

**Issue by Marcono1234** [auth0/Auth0.Android#484]
### Describe the problem
`BaseRequest` uses [`Charset.defaultCharset()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/charset/Charset.html#defaultCharset()), which is the operating system charset:
https://github.com/auth0/Auth0.Android/blob/5f20b76c8bca3ec5a5fba135e6ce4ae183e2ec5b/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt#L96

Is there a reason for this? Normally JSON is UTF-8 encoded; using the operating system charset will most likely cause issues if the charset does not support all Unicode code points or uses an encoding which is not even compatible with ASCII.
It looks like #390 introduced the change [here](https://github.com/auth0/Auth0.Android/pull/390/files#diff-c61404ff99127bb379a5afa779eab8b6597a495d3165af1fea98a6bc5501efdaR118) but I did not find any explanation.

Ideally one of OkHttp `ResponseBody` methods would be used, such as [`charStream()`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/char-stream/), since they also consider the HTTP headers, maybe `ServerResponse` should have a `Reader` instead of an `InputStream` as `body` then.

Also note that exception handling of `BaseRequest.execute()` should probably be improved by using [`Closeable.use`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) so in all cases the `reader` is closed.

**Comment by lbalmaceda** [comment]
Thanks for the good write-up! We talked about the charset in the issue linked above 👍 

1. About the improvements in the networking stack, I know historically Auth0 always sent UTF8 content back from the server. Relying on the content-type headers would be a good idea, especially given that it fallbacks to UTF8 in the end. `ServerResponse` is a public class though, and is the one we ask users to implement when they want to pass their own version of a `NetworkingClient`. 

2. We make sure the reader is closed and we can test that by using the `AwareInputStreamReader` class. But I guess you mean in case something goes wrong right before we call `reader.close()`. Are you suggesting we wrap all [these lines](https://github.com/auth0/Auth0.Android/blob/5f20b76c8bca3ec5a5fba135e6ce4ae183e2ec5b/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt#L96-L115) with `Closeable.use`?

**Comment by Marcono1234** [comment]
> 1. `ServerResponse` is a public class though, and is the one we ask users to implement when they want to pass their own version of a `NetworkingClient`.

Yes that is an issue. Changing `body` from `InputStream` to `Reader` is not an option then (and it would also prevent future use in case some of the APIs return non-String data). But since you control the API anyways, hardcoding UTF-8 is probably fine.


> 2. Are you suggesting we wrap all [these lines](https://github.com/auth0/Auth0.Android/blob/5f20b76c8bca3ec5a5fba135e6ce4ae183e2ec5b/auth0/src/main/java/com/auth0/android/request/internal/BaseRequest.kt#L96-L115) with `Closeable.use`?

Exactly, so in all cases the stream is closed. The class `AwareInputStreamReader` might not even be needed, it looks like the unit tests could be rewritten to test if the underlying `InputStream` was closed (since the `InputStreamReader` delegates the `close()` call to it).

**Comment by lbalmaceda** [comment]
The sole reason the `AwareInputStreamReader` exists is to assert in the unit tests that the stream was actually closed. If that's possible with the change you mention above, I'm OK with having those tests updated. Do you want to send a PR or update the existing one with that?
