### ISSUE TITLE
`AsymmetricSignatureVerifier` should not use `Charset.defaultCharset()`

### ISSUE THREAD

**Issue by Marcono1234** [auth0/Auth0.Android#485]
### Describe the problem
`AsymmetricSignatureVerifier` uses the default charset during token validation:
https://github.com/auth0/Auth0.Android/blob/5f20b76c8bca3ec5a5fba135e6ce4ae183e2ec5b/auth0/src/main/java/com/auth0/android/provider/AsymmetricSignatureVerifier.java#L42

It should probably instead specify an explicit charset, most likely either [`StandardCharsets.ISO_8859_1`](https://developer.android.com/reference/java/nio/charset/StandardCharsets#ISO_8859_1) or [`StandardCharsets.US_ASCII`](https://developer.android.com/reference/java/nio/charset/StandardCharsets#US_ASCII).

**Comment by lbalmaceda** [comment]
@Marcono1234 thanks for raising this. We use it to extract `UTF-8` content. As per the [Android docs](https://developer.android.com/reference/java/nio/charset/Charset#defaultCharset()), this value is always "UTF-8". A change from the Android OS side would be a breaking change for everyone who depends on it, so it's highly unlikely 
![image](https://user-images.githubusercontent.com/3900123/122445161-8f8d0480-cfa1-11eb-855b-ab81830c9134.png)

Can you expand a bit on the reasons why we shouldn't use the default charset?

**Comment by Marcono1234** [comment]
Ah you are right. This might not actually a problem then. I created the issue with the Java implementation in mind which does not make such guarantee and therefore using the default charset there is in most cases not a good idea.
Though if your intention is to use UTF-8, then it might be good to make that more explicit by using [`StandardCharsets.UTF_8`](https://developer.android.com/reference/java/nio/charset/StandardCharsets#UTF_8). You are targeting API level 21 and that constant exists since API level 19 so you could use it without any issues.

**Comment by lbalmaceda** [comment]
Sounds good. We used to pass the string name of the charset and that made us try/catch or ignore a runtime exception that would never be thrown (on android at least). 

Would you like to send a PR with that change? Note that it might be used in more than one place. e.g. #484
