### ISSUE TITLE
Add possibility to turn off the share icon to CustomTabsOptions

### ISSUE THREAD

**Issue by latsson** [auth0/Auth0.Android#487]
### Describe the problem you'd like to have solved
It does not really make any sense showing a share icon in a login flow.

Since androidx.browser version 1.3.0 it's now possible to disable the share icon for custom tabs.

See the "How can I opt-out from the share icon showing in my App?" on this blog post.
https://blog.chromium.org/2021/01/better-content-sharing-with-custom-tabs.html

### Describe the ideal solution
To be able to turn the share icon off in the CustomTabsOptions builder.

## Alternatives and current work-arounds
No work-around found.

### Additional information, if any
https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder#setShareState(int)

**Comment by lbalmaceda** [comment]
@latsson I think this is a valid feature request. But I would not allow users to opt-out of the share button. Instead, I'd just remove it. As you said, there's no need to share a login page externally.

Note, however, that this would only impact Chrome browsers as of today. For that button to be hidden in other browser apps, their devs would need to implement that. From the page you linked:
> Please note: this is a change in Chrome’s behavior and we hope other browsers will add similar functionality.

Would you like to send a PR that adds the `setShareState(CustomTabsIntent.SHARE_STATE_OFF)` to the CCT builder?
