### ISSUE TITLE
Wrong handing of errors in OAuthManager.assertNoError(errorValue: String?, errorDescription: String?) method

### ISSUE THREAD

**Issue by hs-klyanava** [auth0/Auth0.Android#493]
Method OAuthManager.assertNoError(errorValue: String?, errorDescription: String?) has wrong logic.

### The problem
 When I try to sign up via Facebook and I use email that already has been used to sign up, I get the following log messages:
 
 

> D/OAuthManager: The parsed CallbackURI contains the following values: {error=access_denied, error_description=It looks like that email is already associated with a ... account, please try signing in with a social account, or use another email, state=...}
> 
> E/OAuthManager: Error, access denied. Check that the required Permissions are granted and that the Application has this Connection configured in Auth0 Dashboard.
> 
> E/AuthManager:165: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
>         at com.auth0.android.provider.OAuthManager.assertNoError(OAuthManager.java:284)
>         ... 

So you can see here that we had `error_description `there which says "I**t looks like that email is already associated with a ... account, please try signing in with a social account, or use another email**" , but in the ultimate AuthenticationException we don't see any sign of this `error_description `.

The cause of the problem is implementation of  `OAuthManager.assertNoError(errorValue: String?, errorDescription: String?) `method. Because `OAuthManager `has the following code: 

```
public override fun resume(result: AuthorizeResult): Boolean {
        ...
        Log.d(TAG, "The parsed CallbackURI contains the following parameters: ${values.keys}")
        try {
            assertNoError(values[KEY_ERROR], values[KEY_ERROR_DESCRIPTION])
            ...
        } catch (e: AuthenticationException) {
            callback.onFailure(e)
            return true
        }
        ...
}
```
and

```
   private fun assertNoError(errorValue: String?, errorDescription: String?) {
        if (errorValue == null) {
            return
        }
        Log.e(
            TAG,
            "Error, access denied. Check that the required Permissions are granted and that the Application has this Connection configured in Auth0 Dashboard."
        )
        when {
            ERROR_VALUE_ACCESS_DENIED.equals(errorValue, ignoreCase = true) -> {
                throw AuthenticationException(
                    ERROR_VALUE_ACCESS_DENIED,
                    "Permissions were not granted. Try again."
                )
            }
            ...
        }
    }
```
where `ERROR_VALUE_ACCESS_DENIED = "access_denied"`. This means that `errorDescription `is not used here if `errorValue` is "access_denied".

### What was the expected behavior?

I guess that the fix of this problem can be done via changing the method of `OAuthManager.assertNoError(errorValue: String?, errorDescription: String?)`, e.g.:

```
   private fun assertNoError(errorValue: String?, errorDescription: String?) {
        if (errorValue == null) {
            return
        }
        Log.e(
            TAG,
            "Error, access denied. Check that the required Permissions are granted and that the Application has this Connection configured in Auth0 Dashboard."
        )
        when {
            ERROR_VALUE_ACCESS_DENIED.equals(errorValue, ignoreCase = true) -> {
                throw AuthenticationException(
                    ERROR_VALUE_ACCESS_DENIED,
                    if (errorDescription.isNullOrEmpty()) "Permissions were not granted. Try again." else errorDescription
                )
            }
            ...
        }
    }
```

### Environment

- **Version of this library used: 2.2.0**
- **Which framework are you using, if applicable: Android**

**Comment by lbalmaceda** [comment]
@hs-klyanava thanks for raising this. As far as I know, accounts in Auth0 are created based on the provider used to log in. So if you create a new "Auth0 Database connection" user with your email `me@user.com` and then sign up using "Facebook Social connection" with a user whose email is also `me@user.com`, those would be two different users. You can still link these accounts following a special process described in the [user-account-linking](https://auth0.com/docs/users/user-account-linking) article.

What I believe happened above is that you created your user with connection A, then created another one with connection B, and then linked both. But now one of those connections got disabled for the Auth0 application that you are using and the login got blocked. Is this assumption accurate?

I think the fix that you propose above is correct. The `access_denied` error that the [OAuth spec documents is pretty generic](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2.1) and while the description sent by the server can be optional, it could be used to help the dev understand what went wrong a bit more. Although every `access_denied` error should be treated the same and no string matching should be done against the `error_description` field as it can change at any time, as opposed to the `error` value.

Would you be able to send a PR with the fix?

**Comment by hs-klyanava** [comment]
@lbalmaceda I've tried to created the PR, but I got an error "Permission to auth0/Auth0.Android.git denied". The fix is essentially changing of 1 line of the code:
https://dropmefiles.com/eefV6

**Comment by lbalmaceda** [comment]
That's because you were trying to push to our remote (the "auth0" github user). You should instead click the FORK button on the top right, create a public fork under your own username ("hs-klyanava"), and push to `hs-klyanava/Auth0.Android` instead. Then with that, you can come here and open a PR across different forks. 

I've opened a PR with the change you proposed above and added a few unit tests. I'll wait for someone from the team to pick it up.

**Comment by hs-klyanava** [comment]
@lbalmaceda Thank you a lot!
