### ISSUE TITLE
Close button on toolbar just reloads the login view 

### ISSUE THREAD

**Issue by shivamarujolla** [auth0/Auth0.Android#495]
### Describe the problem
 Close button on toolbar just reloads the login webpage and on failure is called back
doesn't close the app

Atleast need a call back to handle the expected behavior

**Comment by lbalmaceda** [comment]
The action of closing the opened /authorize page either via pressing the "back" key of the device or clicking the "x" in the custom tabs toolbar, is what we raise through the callback as an "authentication canceled" error. There are many properties you can check to assert the type of error that you just received in the `onFailure` method. But to check this one in specific, see https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt#L126-L128.
