### ISSUE TITLE
expires_in field https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking 

### ISSUE THREAD

**Issue by miukki** [auth0/Auth0.Android#499]
expires_in mentioned in documentation https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking might need rename to expiresAt ?

the code based: 
```
WebAuthProvider.login(account)
            .withScheme(getString(R.string.com_auth0_scheme))
            .withScope("openid profile email offline_access read:current_user")
            .withAudience("https://${getString(R.string.audience)}")

            // Launch the authentication passing the callback where the results will be received
            .start(this, object : Callback<Credentials, AuthenticationException> {
            
                override fun onSuccess(credentials: Credentials) {
                    cachedCredentials = credentials
                    Log.i("expiresAt", "${cachedCredentials?.expiresAt}")//expires_in - the expiration date of the Access Token

```
the code source:
https://github.com/auth0/Auth0.Android/blob/cd9ba7460a4992aa804b940656d16977e743a347/auth0/src/main/java/com/auth0/android/request/internal/CredentialsDeserializer.java#L31-L33

**Comment by lbalmaceda** [comment]
> expires_in mentioned in documentation https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking might need rename to expiresAt ?

I don't see any mention of `expires_in` in that section. Are you sure that's the correct link?
"expires_in" is the name of the property that comes from the server when new tokens are issued. But locally, to the SDK, this property is converted to a calculated Date, which we name "expires_at". So, you might be correct and there might be a place in which we use the other name by mistake.

**Comment by miukki** [comment]
@lbalmaceda  sorry for delay. 
link https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking
paragraph:
```
Save credentials: The credentials to save must have expires_in and at least an access_token or id_token value. If one of the values is missing when trying to set the credentials, the method will throw a CredentialsManagerException. If you want the manager to successfully renew the credentials when expired you must also request the offline_access scope when logging in in order to receive a refresh_token value along with the rest of the tokens. i.e. Logging in with a database connection and saving the credentials:
```

**Comment by lbalmaceda** [comment]
Ah yes! Good catch. That's a left over from v1. The new major directly takes a parsed date type representing the "expires at" date instead of the "expires in" seconds that comes from the server. Source: https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/result/Credentials.kt

Do you feel like sending that PR over for a review? Otherwise, we can take care. Thanks
