### ISSUE TITLE
AuthenticationException has no methods for invalid tokens

### ISSUE THREAD

**Issue by Juchar** [auth0/Auth0.Android#51]
The AuthenticationException provides different methods for checking the status code, e.g. `isPasswordLeaked()`.

I am missing methods for token validity, e.g.:

- Invalid id token
- Expired id token
- Invalid refresh token
- Expired refresh token

Also for android it might be useful to somehow have a method like `isNetworkError()`, as this could then be treated separately (e.g. the local credentials should not be deleted in this case).

**Comment by hzalaz** [comment]
@Juchar and what API call to Auth API  will yield those errors you listed?

About the network error, I'd rather leave that to the library user so, if they want, checks for network availability before making any request.

**Comment by lbalmaceda** [comment]
Hi @Juchar. 
Tokens are not validated by the `auth0.android` library, you should do that in your own app. Same for the network check.

Cheers.
