### ISSUE TITLE
Received error with code a0.sdk.internal_error.unknown

### ISSUE THREAD

**Issue by elai950** [auth0/Auth0.Android#525]
### Describe the problem

- Using Kotlin

Any attempt to use the `AuthenticationAPIClient` and execute/start any function follows by error:
`Received error with code a0.sdk.internal_error.unknown`

Any other models like WebProvider works perfectly.

**The exact same network layer and API works perfectly in the iOS version. Using also the auth0 SDK + API. Same function works great there.**

### What was the expected behavior?

Tried to any function like: Passwordless SMS, Passwordless Email, Email & Password, Creating user etc...

### Reproduction

Encounter this problem first at my own app, after getting really confused, tried the sample app from the Client section.
Thought maybe my configuration is wrong.
But still.

1. Download Sample App
2. Add this function:
```kotlin
fun login(){
var auth: AuthenticationAPIClient = AuthenticationAPIClient(account)
        CoroutineScope(IO).launch {
auth
            .passwordlessWithSMS(phoneNumber = "<VALID_PHONE_NUMBER>", passwordlessType = PasswordlessType.CODE)
            .start(object: Callback<Void?, AuthenticationException>{
                override fun onFailure(error: AuthenticationException) {
                    Log.e("Passwordless Error", error.getDescription())
                }

                override fun onSuccess(result: Void?) {
                    println("No Way")
                }
            })
}
    }
```

### Environment

- **Version of this library used:** 2.5.0 (Actually I've tried all the versions)
- **Which framework are you using, if applicable:** Kotlin
- **Other modules/plugins/libraries that might be involved:** No
- **Any other relevant information you think would be useful:** No Idea

### Already Tried
- Emulator & Physical Phone.
- Changed internet connection (even changed house...)
- Already set logging enabled but nothing showed up.
- Different client id.
- Checking the allowed callback URLs.
- Adding the SHA to the client settings.
- Praying 🙏

**Comment by elai950** [comment]
For anyone here who encounters this ridiculous problem.
This TRUE problem here is that the time in the device is incorrect!
You need to Cold Boot the device, that's all...

It's a shame for the Android creators, really.
A real joke in the face of the clients.

Closing...

**Comment by VilleMiekkoja** [comment]
Omg you saved me so many hours...
