### ISSUE TITLE
Device Authorization Flow

### ISSUE THREAD

**Issue by drdla49** [auth0/Auth0.Android#529]
Does this library support Device Authorization Flow? 
https://auth0.com/docs/authorization/flows/device-authorization-flow
If not, is it possible to add this authorization?
Thanks

**Comment by jimmyjames** [comment]
Hi @drdla49, this library does not support the Device Authorization flow; which devices/platforms are you interested in?

**Comment by drdla49** [comment]
Hi @jimmyjames and is it possible to add support of Device Authorization Flow? Our identity server is ready for it. And I can write the android client.

**Comment by jimmyjames** [comment]
Hi @drdla49, we're looking to understand in what type of device(s) you are looking to use the device authorization flow on. For phones or tablets, we recommend using the [code+PKCE flow](https://auth0.com/docs/authorization/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce) which this library supports using the `WebAuthProvider`. 

Regarding adding the device flow to this library, that is something we can discuss internally and see if it's something we'll put on our roadmap, but understanding your use case can help us in that process. Thanks!

**Comment by drdla49** [comment]
Now I use it to log in on tablet from phone. Tablet show QR code, hone scan QR and log in user on tablet.

**Comment by poovamraj** [comment]
Hi @drdla49, Thanks for explaining the use case. We would also like to know how whether providing the API method for this would be enough so that polling can be handled by yourself?

**Comment by poovamraj** [comment]
Hi @drdla49, we are closing this issue for now due to inactivity. 

Please reopen this if you have requirements over this

**Comment by drdla49** [comment]
Hi, sorry for the delay. 
The better solution is that you implement polling and I only receive tokens as for normal login.
Thanks.

**Comment by poovamraj** [comment]
Hi @drdla49, since there are not many requests for this type of login, we won't be implementing this feature right away. Though you can provide a PR for which we can help you with. Thanks for understanding.
