### ISSUE TITLE
Let WebAuthProvider tell if user is authenticated and also allow silent log out.

### ISSUE THREAD

**Issue by lokeshbhattarai** [auth0/Auth0.Android#531]
### Describe the problem

I'm running into an issue where a user once signed into the app via Auth0 SDK (`WebAuthProvider`) stays signed in even if they uninstall the app. So if they comeback again after certain time (before token expires) SDK will return the access token right away without user having to enter their credential. Sounds like the web cookies will still consider user as authenticated. I'm looking for a way to force user to input credentials when that happens.

 For now, I'm doing `WebAuthProvider#logout` before every `WebAuthProvider#login` when user doesn't have token stored in the app cache. However I had to put a delay of at least 100ms between login and logout call because the login web page wasn't rendering as soon as log out was completed. Looking beneath I found that both process launch same Android Activity in the SDK, not sure if that made any difference.

Is there a way I can get information whether user is logged in or not from the WebAuthProvider , so that I can sign out user first before asking them to login?

### What was the expected behavior?

Currently, the `WebAuthProvider#logout` pops up a browser for split second and goes away. It feels like unwanted flickr in the app for user experience.  It would be nice to have a method to silently log user out so that they don't see the flickr and log out process can happen on the background. I'd appreciate any feedback on getting rid of this.

### Reproduction

Assume there is "Login" button in the app that starts the flow

1. Tap on Login. and authenticate successfully into the app via WebAuthProvider.
2. Once you are logged in, uninstall the app.
3. Install the app back again and tap Login. 

Expected behavior is that you'd see Login Page on web.
Actual: It will log back you in to the app right away.

### Environment

Device I was using : Pixel 4XL, Android OS 12.

Auth0 SDK version: 2.5.1

**Comment by jimmyjames** [comment]
Hi @lokeshbhattarai, thanks for reporting and for providing details. Unfortunately as cookies are managed by the browser application and not controlled by the SDK, you can either continue to do logout first or try sending the `prompt=login` parameter (see the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) or the [Auth0 docs](https://auth0.com/docs/login/max-age-reauthentication)) to trigger reauthentication to force the login screen.

**Comment by lokeshbhattarai** [comment]
That seems to do the trick. Thank you for the help.
