### ISSUE TITLE
"Performing pause of activity that is not resumed" when logging in in landscape

### ISSUE THREAD

**Issue by Alexs784** [auth0/Auth0.Android#535]
### Describe the problem
I have an issue in a client when logging in landscape only in the webview. First of all, our client is currently locked in portrait. When triggering the webview to login, if the device is turned into landscape the webview will rotate as well. At this point follow the usual login flow and on success we will get

`java.lang.RuntimeException: Performing pause of activity that is not resumed: myActivity`

### What was the expected behavior?

The app should continue to work as expected. In the current scenario if I have code that should be executed in the `onCreate` it won't work. If moved to the `onPostCreate` (not recommended) we'll have the mentioned exception.

### Reproduction
The issue is reproducible every time

- Step 1: trigger the auth0 webiew through the login method
- Step 2: put the device in landscape -> the webview should rotate
- Step 3: Insert valid credentials to successfully login
- Step 4: wait to go back to the host application and observe logs

### Environment

- **Version of this library used:** both `2.4.0` and `2.6.0`
- **Other modules/plugins/libraries that might be involved:** navigation component for android, flow
- **Any other relevant information you think would be useful:** Tested on Android 8 and 12

**Comment by poovamraj** [comment]
Hi @Alexs784 

I guess this issue is similar to #530. We are currently working on this and will be providing a fix soon.

**Comment by Alexs784** [comment]
I was indeed about to comment, debugging further I also get the `AuthenticationException`. Sorry for the confusion and thanks for letting me know, good you are already aware 💪

**Comment by poovamraj** [comment]
Hi @Alexs784, we have fixed this issue in this PR - https://github.com/auth0/Auth0.Android/pull/566

Please feel free to test it out and let us know your feedback. This version should be released soon and we are closing this issue for now.
