### ISSUE TITLE
Documentation for addSignUpParameters makes little sense

### ISSUE THREAD

**Issue by Daeda88** [auth0/Auth0.Android#538]
### Describe the problem
Currently the documentation for `addSignUpParameters` makes little to no sense. It states:
```
// Define your custom fields
val metadata = mapOf("key"  to "value")
// Define the sign up parameters, adding the user_metadata
val params = mapOf("user_metadata", "metadata")
// Set the parameters in your request
signUpRequest.addSignUpParameters(params);
```

This passes the string `metadata` to the "user_metadata", rather than `{"key"="value"}`.
In addition the documentation contains a semicolon, which implies this is still Java code but the lines above are in kotlin.

### What was the expected behavior?
Documentation should be improved to make it clearer what the intended usage is:

```
val metadata = mapOf("key"  to "value")
// Define the sign up parameters, adding the user_metadata
val params = mapOf("user_metadata", "$metadata")
// Set the parameters in your request
signUpRequest.addSignUpParameters(params)
```

### Reproduction
Just read the documentation on `SignUpRequest.kt`

### Environment
Version 2.6.0

**Comment by poovamraj** [comment]
Hi @Daeda88, Thanks for raising this issue.

I was analysing this and figured that when the request is made, the JSON Object characters are escaped which returns the following error

`{"error":"invalid user_metadata type (expected object)"}`

We will update the documentation along with the fix for this.

**Comment by poovamraj** [comment]
We will check this issue and provide the fix in the next update for the library. We will keep this issue open until then 👍

**Comment by poovamraj** [comment]
@Daeda88 we have fixed this issue in this PR - https://github.com/auth0/Auth0.Android/pull/567
