### ISSUE TITLE
[Question] Is it safe to override Auth0UserAgent

### ISSUE THREAD

**Issue by fpitters** [auth0/Auth0.Android#543]
We would like to know from Auth0 logs what app name and version is triggering those login/logout events.
We have found that we can override the Auth0 user agent, that it’s turned into `auth0-client` header.
Would it be OK to pass any value we would like to see on the request logs?

Sample:
 ```
 auth0.auth0UserAgent = Auth0UserAgent("Our app name", "Our app version")
 ```

Notice I've raised the question [here](https://community.auth0.com/t/is-it-safe-to-override-auth0useragent/78759)
and doesn't seem to be a `question` type for issues.

Thanks

**Comment by poovamraj** [comment]
Hi @fpitters, This is actually an internal implementation as of now and we will be removing it from being a public API in our next release. So it wouldn't be right to depend on this parameter. Currently, we do not have a way to send custom data that can show up in the logs. I do understand this could be a good feature though. Sorry about that :(
