### ISSUE TITLE
Does any body knows how to perform a native logout action?

### ISSUE THREAD

**Issue by zhangwenxue** [auth0/Auth0.Android#546]

**Comment by poovamraj** [comment]
Hi @zhangwenxue, 

1. For clearing the credentials stored in the browser cookies, you can use

```java
WebAuthProvider.logout(account)
    .start(this, logoutCallback)
```

For clearing the credentials stored in the `CredentialManager` you can call
```java
manager.clearCredentials()
```

If you are looking for something else, please provide more information using our Template to report issues and it will help us provide more details for you.
