### ISSUE TITLE
How to fetch code and state after successful login.

### ISSUE THREAD

**Issue by Nitishreddy787** [auth0/Auth0.Android#548]
Hey, i’m facing an issue, how to fetch the code and state values after successful login , when i've checked the logs I got this **D/OAuthManager: The parsed CallbackURI contains the following parameters: [code, state]**. Can you help to retrieve the code and state values?

**Comment by poovamraj** [comment]
Hi @Nitishreddy787 👋, Currently we don't expose these parameters. Since they are used only for PKCE exchange and we handle the exchange by default internally, There wouldn't be any need to expose them. Can you let us know for what use case these values are required?

**Comment by Nitishreddy787** [comment]
Hi @poovamraj , we are using state and code to our internal api to generate a token.

There is an other option for us to generate the token using Auth0 Jwt. I just wanted to know whether we can get the state and code.

**Comment by poovamraj** [comment]
Great 🙂 Do let us know if you have any more questions for us. We will close this issue for now but feel free to reopen it in case needed.
