### ISSUE TITLE
Retain Login session in Web view

### ISSUE THREAD

**Issue by Nitishreddy787** [auth0/Auth0.Android#550]
Hi,

I have implemented auth0 login in my  app with Auth0 SDK . When i try to open profile page in app web view, it is taking me to login again. How to maintain the session to open the profile page without login again.

**Comment by poovamraj** [comment]
Hi @Nitishreddy787, What framework and SDK are you using for your web application? Since this is mostly directed towards that particular SDK, it would be better to raise the query there.

**Comment by Nitishreddy787** [comment]
When i launch the same profile url in external chrome browser, it is retaining the login details, but facing issue is with the in app WebView.

**Comment by poovamraj** [comment]
I guess the current login uses Chrome Custom Tab and the cookies are not shared between that and Web View. So if you use the webpage on a chrome custom tab, it should work. Are you using Chrome Custom Tabs?

**Comment by Nitishreddy787** [comment]
Thanks @poovamraj, I tried using custom tabs and it is working.
