### ISSUE TITLE
UserProfile createdAt wrong date - does not respect the GMT

### ISSUE THREAD

**Issue by VladSVAssets** [auth0/Auth0.Android#553]
### Describe the problem

I have created an account at "Fri Apr 29 10:09:23 GMT+03:00 2022", but the UserProfile returns createdAt "Fri Apr 29 07:09:23 GMT+03:00 2022". I assume it is the time without the GMT. For the Credentials expiresAt, the time is correct "Sat Apr 30 10:09:25 GMT+03:00 2022" - current date plus one day I assume.

From the comments on the code, I only see comment about Credentials.expiresA, but none for UserProfile.createdAt. For me at least, it would have no logic in returning dates in multiple formats.
`

    /**
     * Getter for the expiration date of the Access Token.
     * Once expired, the Access Token can no longer be used to access an API and a new Access Token needs to be obtained.
     *
     * @return the expiration date of this Access Token
     */
    @field:SerializedName("expires_at") public val expiresAt: Date
`

### What was the expected behavior?

I would expect for the UserProfile.createdAt date to be correct and respect the GMT, as the Credentials.expiresAt does. 

### Reproduction

We are using Auth0 Universal login. To reproduce this issue:
1. Create a new account using "WebAuthProvider.login(auth0)" with "params["screen_hint"] = "signup""
2. Get the user profile using "client.userInfo(credentials.accessToken)"

### Environment

- **Version of this library used:2.6.0**
- **Which framework are you using, if applicable: Android Studio Bumblebee | 2021.1.1 Patch 3**
- **Other modules/plugins/libraries that might be involved: No**
- **Any other relevant information you think
 would be useful:**

![Screen Shot 2022-04-29 at 10 17 20 AM](https://user-images.githubusercontent.com/65168919/165902564-61d04b99-09e3-454e-8db4-5d203fdc4743.png)
![Screen Shot 2022-04-29 at 10 16 44 AM](https://user-images.githubusercontent.com/65168919/165902571-a98b2480-2f14-44a0-ba5a-6a4832c1202a.png)

**Comment by VladSVAssets** [comment]
Hello!

Any updates on this?

**Comment by poovamraj** [comment]
Hi @VladSVAssets, Sorry for the late response. Can you provide more information on how this User Profile was created? i.e whether using other IdP like Google?

**Comment by VladSVAssets** [comment]
Hi @poovamraj ! The user is created by using the standard sign up where you enter an email and a password, if this is what you are referring. It is not a Google/Facebook sign up.

**Comment by poovamraj** [comment]
Hi @VladSVAssets, can you share with us the tenant you are using? and if you are comfortable, you can share the user name as well.

**Comment by VladSVAssets** [comment]
@poovamraj the tenant is 'roofstock', and the user name is 'vlad+prodna80@stessa.com'.

**Comment by VladSVAssets** [comment]
Hi @poovamraj ! Any updates on this?

**Comment by VladSVAssets** [comment]
Any updates here? Anyone?

**Comment by VladSVAssets** [comment]
Hello! Any news on this?

**Comment by poovamraj** [comment]
@VladSVAssets we are looking into this issue along with other improvements in our SDK. We have already started looking into it so we will keep you updated as soon as we have more information.

**Comment by poovamraj** [comment]
Hey @VladSVAssets, we have fixed this issue in the above-mentioned PR, feel free to check it out and provide your feedback. Feel free to reopen this issue if you have any more doubts about this.

**Comment by VladSVAssets** [comment]
@poovamraj 
1. Do you know when the next official release will be made including this fix? 
2. What's the easiest way for me to test these changes inside my project? Can I use a "minor/alpha" version of the SDK instead of the official release (f.e. "2.7.0-alpha123" instead of "2.7.0")?

**Comment by poovamraj** [comment]
1. We are planning for a release soon in the next few weeks. 
2. The next release should be minor release, I would suggest waiting for it through Maven. But you can clone and use this library to locally test and provide us with feedback if there is anything to improve.

**Comment by VladSVAssets** [comment]
Hello! I have just tested this on v2.8.0 and it works as expected. Thanks!
