### ISSUE TITLE
Expand or redefine definition of NetworkErrorException and/or isNetworkError function

### ISSUE THREAD

**Issue by alvindizon** [auth0/Auth0.Android#558]
### Describe the problem you'd like to have solved

Currently, there exists `isNetworkError` for `AuthenticationException` that checks if its cause is `NetworkErrorException`, which in turn is defined as an `Auth0Exception` with message `Failed to execute the network request`. Now in our code, we do not log errors if `isNetworkError` is true for an `AuthenticationException`. However, our logs are still flooded with `AuthenticationExceptions` that ultimately point to exceptions such as `UnknownHostException` and `SocketTimeoutException`, as their causes, which means our users have encountered connectivity issues, which we do not wish to log (we allow users to retry in this case).

### Describe the ideal solution

Redefine `isNetworkError` so that it checks if any of the causes are `UnknownHostException` or `SocketTimeoutException`.

## Alternatives and current work-arounds

We have code in place that checks if an  `AuthenticationException` has either `UnknownHostException` or `SocketTimeoutException` as its cause, in this case we do not send logs.

### Additional information, if any

If the Auth0 team thinks this request is sensible I can make a PR for this.

**Comment by poovamraj** [comment]
Hi @alvindizon this sounds great. Can you expand more on how you are planning to solve this issue so that we can be in the same page before a PR can be created for this?

**Comment by poovamraj** [comment]
Hi @alvindizon, we were thinking it would be great if you can provide us a way to reproduce this issue so that we can analyze and provide a fix that wont affect backward compatibility as well

**Comment by alvindizon** [comment]
Hi @poovamraj sorry for the late reply, here's how we replicate the UnknownHostException:

1. We have the ID token expiration set to some short value, say 300 seconds or lower for easier testing
2. Log in to app
3. Send app to background
4. Wait for duration specified in ID token expiration
5. Turn off Internet connection in phone
6. Open app again.

The exact error is: `Caused by: java.net.UnknownHostException: Unable to resolve host "mycompany.auth0.com": No address associated with hostname`

**Comment by alvindizon** [comment]
I was thinking about this, and thought of another solution. We normally use OkHttp interceptors that throw exceptions if there's no internet connection, something similar to this: https://stablekernel.com/article/seamless-network-state-monitoring-with-retrofit-okhttp/

Would it make sense to allow developers to use custom interceptors with the client that Auth0 uses?

**Comment by poovamraj** [comment]
Hey @alvindizon, We have implemented this feature in this PR - https://github.com/auth0/Auth0.Android/pull/580

Please feel free to check it out and provide us your feedback. We will be closing this issue for now but don't mind reopening it if you have more suggestions for us.
