### ISSUE TITLE
Redirect logged user to change password screen buy using auth0 sdk

### ISSUE THREAD

**Issue by yusufonderd** [auth0/Auth0.Android#559]
I'm not sure this feature already available or not. I cant find this function in native Android SDK. 

After user logged in . User can change own password from using auth0 sdk. Sdk should allow redirect to change password screen. For now I can't do this operation properly. And also I don't know how to do it ?  Is there a another solution for this ?

**Comment by poovamraj** [comment]
Hi @yusufonderd 👋 

Are you referring to resetting the user password? This can be done through `AuthenticationAPIClient#resetPassword`. You can find the different ways supported to do this by Auth0 [here](https://auth0.com/docs/authenticate/database-connections/password-change#trigger-an-interactive-password-reset-flow)

**Comment by poovamraj** [comment]
Hey @yusufonderd, any update on this?

**Comment by poovamraj** [comment]
Hey @yusufonderd, we are closing this issue for now. Please feel free to reopen it when you can share more information on this.
