### ISSUE TITLE
Using Auth0 SDK and Google sign-in for a native experience (no browser redirect)--is it possible?

### ISSUE THREAD

**Issue by alvindizon** [auth0/Auth0.Android#560]
### Describe the problem you'd like to have solved

We would like to add Google sign-in to our app. We currently use `passwordlessWithEmail` to sign-in our users, but we'd like to add a sign-in with Google button. Looking at our options, it seems that using `WebAuthProvider` with connection set to `google-oauth2` fits our requirement, but it involves redirecting our users to a browser where they will either enter their Google credentials or pick an already signed-in Google account. We would like to use the native dialog similar to the one that appears here:https://developers.google.com/identity/one-tap/android or with Google sign-in: https://developers.google.com/identity/sign-in/android/sign-in

Does the Auth0 SDK already have something that can work with our scenario?

### Describe the ideal solution

A native way to connect Auth0 and Google sign-in methods

## Alternatives and current work-arounds

We can do Google sign-in and just pass the received credentials to the current login code that we have but that would still involve having the user enter a verification code. We'd like to have our users automatically signed in after clicking the Google sign-in button

**Comment by poovamraj** [comment]
Hi @alvindizon 

From the looks of it, we cannot provide this feature through our SDK since that would mean providing a very thin wrapper around the Google SDK and that would cause troubles like having a hard dependency with the Google SDK and lot of maintenance providing all the features from the Google SDK.

Though we would like to understand more about one thing. Can you expand on this point?
> but that would still involve having the user enter a verification code

**Comment by alvindizon** [comment]
@poovamraj I was just speaking generally and thinking about what it would take using our current code, which uses `passwordlessWithEmail` for login and involves the user receiving a verification code, if we were to use Google's SDK and Auth0 together.

We are currently testing a `WebAuthProvider` based approach to Google sign-in which involves the user clicking a button and being redirected to a browser where they'll be signed-in via Google. It works but we'd like to receive user's first name and last name, something that Auth0 doesn't do (we only get Credentials in return).

Is this approach correct if we want users to use their Google account to create accounts with us?

**Comment by alvindizon** [comment]
Also would like to note that this feature seems to have been requested numerous times, based on some similar issues here in Github and in community.auth0.com. If the Auth0 teams deems this feature as not feasible, developers would appreciate if it there was some official document that describes how developers can work with Auth0 given this scenario (maybe something like "What if we want to use Google sign-in and Auth0"). Currently, the information is all over the place and can only be found by searching Github issues and the forums
