### ISSUE TITLE
MFA Required error when renewing auth tokens

### ISSUE THREAD

**Issue by karlity** [auth0/Auth0.Android#562]
### Describe the problem

Using the universal login implementation, I'm running into an issue where I'm using the SecureCredentialsManager to silently renew tokens in the background when the access_token expires but the refresh_token has not.  What I'm running into is every time I go to renew with 
` manager.getCredentials(
                object : Callback<Credentials, CredentialsManagerException> {` 

I get an error: "An error occurred while trying to use the Refresh Token to renew the Credentials."

After not figuring out what was happening, I tested with the `client.renewAuth(<refresh_token>).start() `and received this error in the callback: "403 Mfa Required"

I cannot find any documentation on what to do in this instance.  After hitting the "Remember after 30 days" option in the authentication flow, I was able to open the WebAuthProvider and not have to go through the flow again as it seemed to recognize I was logged in and put me through but that is only after re-opening the WebAuthProvider. Using the silent renewal methods continue to return errors.  I see solutions for the web available but can't seem to find any for Android specifically if any exist. Please advise!

### Environment

- **Version of this library used:** 2.7.0

**Comment by poovamraj** [comment]
Hey @karlity 👋 

You can find the solution for this here  - https://community.auth0.com/t/how-to-bypass-mfa-for-refresh-token-requests/26008

Hope this helps.

**Comment by poovamraj** [comment]
Hi @karlity, hope this solved your issue. We will be closing this for now, feel free to reopen it if you have any doubts!
