### ISSUE TITLE
Redirect failed using chrome browser directly instead of using custom tabs

### ISSUE THREAD

**Issue by clarkshu1016** [auth0/Auth0.Android#568]
### What was the expected behavior?

Should be redirected back to the sample app even if the app was killed in the background

### Reproduction

- Step 1  using the sample app , when open the custom tabs chrome, copy the link, and close the chrome custom tabs
- Step 2 switch to the chrome browser, paste the link, and go to the login page
- Step 3 kill the demo app in the background
- Step 4 input email and password try to login, after input credentials in the chrome browser, there is no redirect back to demo, instead just shows Oops, something went wrong error,if the app not kill in the background, will redirect successfully.

### Environment

Version of this library used:
 sample app from GitHub main branch

**Comment by poovamraj** [comment]
Hi, can you show share the screenshot of the page where it fails? Also it would be great to understand the use case you are trying to test here

**Comment by clarkshu1016** [comment]
https://drive.google.com/file/d/11n85MZLSeaObRvrQUHhtBnsdkFMZTFvj/view?usp=sharing
@poovamraj , input the password, and email, and click "continue" button, nothing happened if the sample app was killed, will be stuck on this page, but if the app is still in the background, can redirect back sample app.

Test on pixel 5 
android 12
chrome version:102.0.5005.99

**Comment by poovamraj** [comment]
Thanks a lot @clarkshu1016, Can you use `chrome://inspect` and provide the HAR file and any error/warning rendered on the console?

**Comment by clarkshu1016** [comment]
reproduced  this issue and record a video 
https://drive.google.com/file/d/1QfPjRYQEpRTI9fmfoL_kRBBCqPQ1o2aT/view?usp=sharing
this is HAR file from device chrome browser,please check it ,thanks @poovamraj 
https://drive.google.com/file/d/18Pih2hZztdubDJ6m776pr0NU3mUIKhIG/view?usp=sharing

**Comment by clarkshu1016** [comment]
Any updates on this ticket?

**Comment by poovamraj** [comment]
@clarkshu1016 This use case is not covered by the SDK. we need an active application so that we can complete the PKCE code exchange. If you are trying to login the user with email, you can use passwordless login. I am closing this issue now but feel free to reopen it if you have more doubts

**Comment by clarkshu1016** [comment]
@poovamraj  just wanna know more technical mechanism detail why deep link seems not working after the app was killed,it's possible to ask the team to explain more details? thanks

**Comment by poovamraj** [comment]
@clarkshu1016 [PKCE](https://oauth.net/2/pkce/#:~:text=PKCE%20(RFC%207636)%20is%20an,is%20using%20a%20client%20secret.) is a code exchange done to avoid authorisation code injection. This is maintained in memory and killing the app will destroy this as well. Without this, we will not be able to exchange the authorisation code for the access code. You can read more about it [here](https://datatracker.ietf.org/doc/html/rfc7636)
