### ISSUE TITLE
Handling Refresh token revocation

### ISSUE THREAD

**Issue by alexandrudumbravan-nutmeg** [auth0/Auth0.Android#578]
Hello. We are trying to verify the following scenario in our applications:
1. Login with user A
2. Revoke the refresh token for user A
3. Clear the application and log the user out

We are currently using the `SecureCredentialsManager` class to handle the Auth0 credentials. When we want to access the credentials we invoke `SecureCredentialsManager.getCredentials()`. And I want to double check if this is the correct behaviour when Auth0 will try to renew the authentication using the refresh token through the `getCredentials` method:
1. Auth0 will attempt to load the encrypted credentials
2. Auth0 will then verify if the information expired
3. Auth0 will then renew the authentication

When renewing the authentication for a user which had its refresh token revoked the `getCredentials` method invokes the `onFailure` from the callback. In the `onFailure` method it will pass a `CredentialsManagerException` object which will have as a cause an `AuthenticationException`. The `AuthenticationException` will have the following field be true.
`    public val isRefreshTokenDeleted: Boolean
        get() = "invalid_grant" == code
                && 403 == statusCode
                && "The refresh_token was generated for a user who doesn't exist anymore." == description`

Is all of this correct?

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:** 2.7.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment]
Hi @alexandrudumbravan-nutmeg,

Yes, the flow you mentioned is correct. Do you think we should improve access to this information (For example - capture in README or documentation)?

**Comment by alexandrudumbravan-nutmeg** [comment]
Hello @poovamraj,

That would be great. When I initially implemented this I was struggling to find how to get access to the AuthenticationException to check those fields and I ended up combing the code for it. Having it documented would help.

Thank you.

**Comment by poovamraj** [comment]
Great, we will take a note of it and we will close this issue for now. Please feel free to reach out to us if you have any more doubts.

**Comment by alexandrudumbravan-nutmeg** [comment]
Hello @poovamraj ,

I think I might have to reopen this one because I found a bug when revoking the refresh token. The description i'm getting is "Unknown or invalid refresh token." however for `    public val isRefreshTokenDeleted: Boolean
        get() = "invalid_grant" == code
                && 403 == statusCode
                && "The refresh_token was generated for a user who doesn't exist anymore." == description
` a different description is verified. As a workaround I can check the code and statusCode on my side, but just an FYI.

**Comment by poovamraj** [comment]
@alexandrudumbravan-nutmeg The description was added to handle an edge case mentioned [here](https://github.com/auth0/Auth0.Android/pull/522). It should be the code and status code that should verify this

**Comment by alexandrudumbravan-nutmeg** [comment]
@poovamraj Cool. Thank you for the help
