### ISSUE TITLE
Will android/ios native sdk support "login with Device Biometrics" or not?

### ISSUE THREAD

**Issue by clarkshu1016** [auth0/Auth0.Android#594]
### Describe the problem you'd like to have solved
just want to know, will native SDK support "login with device biometrics " or not? 
https://www.youtube.com/watch?v=EwZc2pOCC94

**Comment by poovamraj** [comment]
@clarkshu1016 Using biometrics with Universal Login is supported as an MFA factor: https://auth0.com/docs/login/mfa/fido-authentication-with-webauthn#platform-authenticators- and https://auth0.com/docs/login/mfa/fido-authentication-with-webauthn/configure-webauthn-device-biometrics-for-mfa

Hope this helps.

**Comment by clarkshu1016** [comment]
@poovamraj  I checked the source code of native SDK, seems there aren't device biometrics for MFA on native SDK, if I am correct, the login with Device Biometrics feature it's implemented on the web, right?

**Comment by clarkshu1016** [comment]
@poovamraj sorry to ask you again, could you help me check it? there is no code on the native side about device biometrics if I understand correctly?
