### ISSUE TITLE
Potential crash possibility with refresh request

### ISSUE THREAD

**Issue by bennycao** [auth0/Auth0.Android#599]
### Describe the problem

Having a read of the `continueGetCredentials` code, when a refresh is required there can potentially be a crashed caused as certain exceptions are not handled.

the code here https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L511 only catches `AuthenticationException`, but `saveCredentials` can throw in multiple locations `CredentialsManagerException`.  Save is called here after refresh https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L508

This would cause a crash if i'm reading it right.

### What was the expected behavior?

Exception to be handled

### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment]
Hi @bennycao Thanks for raising this. Good catch. we have fixed this issue here - https://github.com/auth0/Auth0.Android/pull/600

This should be released soon. We are closing this issue for now. Please feel free to reopen it if you have any more doubts
