### ISSUE TITLE
Expose more fine-grained exceptions from SecureCredentialsManager.getCredentials()

### ISSUE THREAD

**Issue by pocmo** [auth0/Auth0.Android#602]
In the case of an error `SecureCredentialsManager` invokes `Callback.onFailure()` with `CredentialsManagerException`. Except for the message (which can't really be evaluated from code) there's no indication what error happened (apart from the `isDeviceIncompatible` flag).

In comparison the iOS SDK exposes different error cases (also see the additional `AuthenticationError` type exposed for `renewFailed`):
https://auth0.github.io/Auth0.swift/Structs/CredentialsManagerError.html 

It would be nice to expose similar error cases in the Android SDK so that the different errors can be handled more gracefully on the app side. Especially I am interested in distinguishing temporary errors (e.g. network issues) from permanent errors (e.g. no refresh token).

**Comment by pocmo** [comment]
I just noticed that in the case where the refresh fails `CredentialsManagerException` has an `AuthenticationException` set as `cause`. That may get me most of what I need.

**Comment by poovamraj** [comment]
@pocmo did you try accessing the `error.cause` like this

```kotlin
credentialsManager.getCredentials(object : Callback<Credentials, CredentialsManagerException> {
    override fun onSuccess(result: Credentials) {
    }

    override fun onFailure(error: CredentialsManagerException) {
        println(error.cause?.message)
    }
})
```

**Comment by poovamraj** [comment]
Yes @pocmo. I was just responding that. Since it solves your issue, we will close this ticket. Please feel free to reopen it if you have any more doubts
