### ISSUE TITLE
open class Auth0 is effectively final since 2.0.0

### ISSUE THREAD

**Issue by TWiStErRob** [auth0/Auth0.Android#611]
### Describe the problem you'd like to have solved
We need to override the `Auth0.authorizeUrl` from `/authorize` to `/somethingelse/authorize`.
In the current implementation (old 1.25) we can use `class MyAuth0 extends Auth { @Override public String getAuthorizeUrl() { ... } }`.
Sadly during the [Kotlin konversion](https://github.com/auth0/Auth0.Android/commit/ba9ef068d644df0d9a5d8d11d236613ef5273d46) in 2.0.0, `class Auth0` stayed `open`, but there are no overridable funs/vals/vars in it.

### Describe the ideal solution
Add the `open` keyword to each `fun`/`val`/`var` in `Auth0.kt`.

## Alternatives and current work-arounds
N/A

## Minimal repro to show what's the problem:
```kotlin
open class Auth0 {
    public val authorizeUrl: String get() = "..."
}
class MyAuth0 : Auth0() {
    // [OVERRIDING_FINAL_MEMBER] 'authorizeUrl' in 'Auth0' is final and cannot be overridden
    override val authorizeUrl: String get() = "/somethingelse/..."
}
```

cc @aeramli

**Comment by poovamraj** [comment]
Hi @TWiStErRob, we will close this for now since we couldn't really see a scenario where this needs to be supported.  Please feel free to reopen this issue with more details and we will be happy to help.

**Comment by poovamraj** [comment]
Hey @TWiStErRob, we have fixed this here - https://github.com/auth0/Auth0.Android/pull/622. We will notify once this is released.
