### ISSUE TITLE
JCenter Outage 

### ISSUE THREAD

**Issue by bartcone-fulfilld** [auth0/Auth0.Android#616]
Hi Auth0 team - I'm linking an issue below from the `auth0-flutter` repo. In short, there's a JCenter outage at the time of this issue creation (https://status.gradle.com/incidents/9740r6bzx438) and it's causing build failures in the `auth0-flutter` library.

I posted a comment on the current workaround, but I'm admittedly not a gradle expert so was hoping you all could come together and help with a better resolution.

https://github.com/auth0/auth0-flutter/issues/181#issuecomment-1297070192

**Comment by Widcket** [comment]
Hi @bartcone-fulfill, as mentioned in https://github.com/auth0/auth0-flutter/issues/181#issuecomment-1297137774 the JCenter outage was resolved.
