### ISSUE TITLE
Retry of SecureCredentialsManager.saveCredentials after CredentialsManagerException fails again if old keys are present

### ISSUE THREAD

**Issue by paulyoungtt** [auth0/Auth0.Android#618]
### Describe the problem

Users who had been using our app for a while, and then upgraded their device or otherwise modified their lock screen settings, were no longer able to sign in.

We traced this to an issue with the way cleanup is done when SecureCredentialsManager.saveCredentials encounters an error. Newer RSA/AES keys are cleaned up, allowing for retry, but older keys are not. As a result, the app's attempt to retry the call to saveCredentials resulted in the same exception being thrown.

### What was the expected behavior?

The retry would succeed & the user would be able to sign in.

### Reproduction

It's a pretty heavy lift to repro to be honest. You'd have to start with a client using an older version of the Auth0 SDK that stores credentials using the old key alias. You then upgrade the client to use the current version of the Auth0 SDK. You then also update the device so that the key store security changes enough to throw one of the corresponding exceptions leading to the attempt at cleaning up the stored keys.

Rather than trying to build up a repro case, we verified it by adding logging in our app and providing it to specific customers who were experiencing the failure, confirming that they had the older key alias values in their credentials storage, and then validated the potential fix by performing the removal of the offending older keys from storage prior to our retry of the saveCredentials call. So while this is an available workaround, this seems like it should be fixed in the library itself.

### Environment

Auth0.Android 2.8.0

**Comment by poovamraj** [comment]
Hi @paulyoungtt that is a pretty detailed issue report, thanks for that. Is it anyway possible to figure out what was the old version of Auth0 that the user was using?

**Comment by paulyoungtt** [comment]
> Hi @paulyoungtt that is a pretty detailed issue report, thanks for that. Is it anyway possible to figure out what was the old version of Auth0 that the user was using?

Hi @poovamraj, thanks for following up. It looks like we started at version 1.15.2.

**Comment by poovamraj** [comment]
Hey @paulyoungtt Thanks a lot for this great catch and even fantastic PR. We have included it in our next release and we will keep you updated about the release.
