### ISSUE TITLE
Browser cookies are not cleared on logout()

### ISSUE THREAD

**Issue by iuriirodyk** [auth0/Auth0.Android#624]
### Describe the problem

Hi Community!
We’re using Auth0 sdk for Android version 2.6.0 and on logout we’re not able to clear cookies. We’re using federated auth and custom tenant if it matters.
Redirect URL on logout() doesn’t do anything either, federated parameter same. Scheme is the same custom scheme as for login. All works well, but cookies are still no matter what and the user doesn’t start from the very first login page upon next login in the app.
Chrome Custom Tab cookies are not visible for the Cookie Manager, so I’m guessing only Auth0 SDK can get it done.

### What was the expected behavior?

Browser cookies are cleared after `WebAuthProvider.logout(auth)` and upon next login there are no cookies from previous users.

### Reproduction

There are just 2 methods that we use: `login()` and `logout()`. 

<img width="962" alt="Screenshot 2022-12-07 at 8 33 49 am" src="https://user-images.githubusercontent.com/66931628/206027917-b428d683-e1c9-4e08-9559-f813d3184875.png">

<img width="592" alt="Screenshot 2022-12-07 at 8 34 09 am" src="https://user-images.githubusercontent.com/66931628/206027928-46c9e89e-9f42-4016-a2c5-b9a584217d1a.png">

### Environment

- **Version of this library used: 2.6.0**

**Comment by iuriirodyk** [comment]
> Hi, are these the cookies for the federated IdP?

Yes, correct

**Comment by poovamraj** [comment]
Unfortunately, it looks like @iuriirodyk, you can provide product feedback [here](https://auth0.com/feedback) if you want and our PMs could explore more on this. I'll close this issue now.
