### ISSUE TITLE
Call to AuthenticationAPIClient.userInfo has a changed error payload for when the access token is expired

### ISSUE THREAD

**Issue by alexandrudumbravan-nutmeg** [auth0/Auth0.Android#629]
### Describe the problem

I'm not sure if this is the right place to post this issue but it looks like there were some changes made to the Auth0 system.
When we would call /userinfo before with an access token that was expired we would get a custom JSON and error message similar to the one presented [here](https://community.auth0.com/t/what-error-do-we-get-when-token-is-expired/9346). Currently when we call /userInfo we instead get a body which says "Unauthorised" with no JSON and a 401 status code. Should we rely on the status code from now on or is there a bug on the BE side of Auth0.

### What was the expected behavior?

I expected to call AuthenticationException.getCode and check if the code is "unauthorized"

### Reproduction
1. Obtain a valid access token
2. Wait for the token to expire
3. Call AuthenticationAPIClient.userInfo with the expired access token
4. The call to AuthenticationException.getCode should return unauthorized but instead it returns a0.sdk.internal_error.plain with the description set as Unauthorized and status code as 401

### Environment

- **Version of this library used:** 2.8.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment]
Hi @alexandrudumbravan-nutmeg, can you let us know what is the value returned in [here](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/AuthenticationException.kt#L172). Have you setup any rules?

**Comment by poovamraj** [comment]
@alexandrudumbravan-nutmeg we are closing this for now. Please feel free to reopen this with more information.

**Comment by alexandrudumbravan-nutmeg** [comment]
@poovamraj My apologies. I missed the previous message. The line you indicate would've returned false because the error code is a0.sdk.internal_error.plain
