### ISSUE TITLE
Universal Login -- Browser Session on Logout

### ISSUE THREAD

**Issue by dabluck** [auth0/Auth0.Android#630]
### The Problem

We have recently moved from native login to universal login, as recommended by Auth0. Everything is working well but there are several cases we are concerned about and I can't find any good documentation on handling them.

Auth0 uses custom tabs so the user's default browser basically creates the app session. Our app sometimes displays an in-app webview using custom tabs as well for pages that haven't been built for native.

After the user logs in, the in-app tabs "just work". Your signed-in account is authorized and page displays properly. But nothing links these two sessions together after the initial login. So, for example, the user could become logged out in the browser but remain logged in in the app. This would cause a protected page to display a sign-in form inside an app where you're already logged in. Very bad UX. In the worst case, a user could login to a separate account in the browser, then our in-app webview would show a different account's information.

The reverse situation also occurs. When the user logs out of the app, the browser session persists. I think this is counter-intuitive since the logout actually opens a browser window, and logging in does change the browser session.

Are we missing anything or is this how it is expected to work? Is there anything we can do to link these two sessions? Ideally it seems like logging out of the browser or the application should end the session in the other place, that way the user cannot be confused.

Thanks,
Dustin

**Comment by poovamraj** [comment]
Hi @dabluck to do this you have to ensure the session is active by yourself.

1. When native app opens, check whether the web session is logged in using `WebAuth.login` with `prompt=none`
2. On your browser application, depending on whether it is SPA or not, you have to check for session before opening.
3. When logged out from native side, you should always call `WebAuth.logout`

This will ensure the session is in sync in both the places. Hope this answers your question.

**Comment by poovamraj** [comment]
@dabluck we are closing this issue for now. Please feel free to reopen it if you have more doubts
