### ISSUE TITLE
Audience value is not escaped 

### ISSUE THREAD

**Issue by olliestringfield-accedo** [auth0/Auth0.Android#633]
### Describe the problem

Using the `BaseAuthenticationRequest.setAudience(audience: String)` function does not escape the given value.
i.e `"https://mydomain.com"` is not escaped to `"https:\/\/mydomain.com"`
We are also using the iOS SDK which does escape the audience value with the corresponding `setAudience(_:)` API in the iOS SDK

### What was the expected behavior?

We expect the value passed through the `setAudience(_:)` function to escape the value and add the result into the request parameters.

### Reproduction

1. Add Auth0 framework to an Android app
2. Initialise an AuthenticationAPIClient object
3. Call `login(username, password)` and `setAudience(audience)` and `await()` the credentials
4. Observe API call and parameters

### Environment

- **Version of this library used:** 2.8.0
- **Which framework are you using, if applicable:** Auth0.Android
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment]
@olliestringfield-accedo can you provide details on how this is affecting the SDK usage? Auth0 seems to handle the authorization URL generated this way properly

**Comment by poovamraj** [comment]
Hi @olliestringfield-accedo we are not able to reproduce this successfully on our end. Please feel free to reopen this issue with more information.
