### ISSUE TITLE
UI automation testing with Compose

### ISSUE THREAD

**Issue by lucanicoletti** [auth0/Auth0.Android#636]
Hello! :wave:
We recently moved from native login, using login with email and password to WebAuth login, using the SDK webview that prompts the user to login.
We had UI tests in place for E2E tests, which performed the login by inserting email and password to the fields (composable functions) and performing the login button click.
Since our app now opens the webview, we lose control and can’t input the fields, or click the login button in it.
My question is: can we achieve this somehow? Is there a way to tell the SDK to perform a “silent” login, so we can skip the login page?

Thanks in advance.

Posted [here](https://community.auth0.com/t/ui-automation-testing-with-compose/102490?u=lnicoletti) and requested to be shared here as well, so I'm doing so :)

**Comment by poovamraj** [comment]
@lucanicoletti this is currently possible using UI Automator. You can find a sample on how we do it on our Flutter repository here - https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/example/android/app/src/androidTest/kotlin/com/auth0/auth0_flutter_example/SmokeTest.kt

Hope this one helps. I'll close this issue now but feel free to comment here and I can reopen it if this doesn't help.
