### ISSUE TITLE
idToken not being provided if not manually added via scope property result in exception thrown

### ISSUE THREAD

**Issue by ryandary** [auth0/Auth0.Android#648]
https://github.com/auth0/Auth0.Android/blob/a0e5d7464fb3f64d65def18585335de6087e5f4c/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.kt#L539

The language of the documentation suggests that the scope that are used when performing the initial auth will be applied on the renew, however it seems that this is not always the case.  We found that when calling renew without specifically adding the scope parameter, the result of the call is an exception because the payload returned by the server did not contain the idToken.

**Comment by poovamraj** [comment]
Hi @ryandary 

> the response will include an id_token and an access_token if 'openid' scope was requested when the refresh_token was obtained

The documentation does say "if" openid scope is present. Have any suggestions to make this better?

**Comment by ryandary** [comment]
That's clear.  In my case, it is being provided in auth, so my expectation is that it will be provided in refresh.

**Comment by poovamraj** [comment]
@ryandary the `renewAuth` method will work only based on the parameters provided. It doesn't know of any previous state. You can consider it as a pure function that isn't influenced by previous states.

However what you can do is use our `SecureCredentialsManager` to manage your token and it will renew the token depending on the scope and does the management internally and securely. Hope this answers your questions. Feel free to let me know if you have more doubts and I'd be happy to help.

**Comment by ryandary** [comment]
Perhaps the phrase that is confusing is "if 'openid' scope was requested when the refresh_token was obtained" as this suggests some prior state that is being considered.  The "was requested... when.. was obtained" implies that some state is being remembered either internally on device, in the cloud or possibly in the token itself.

It is unclear to the caller (me in this case) that scope needed to be passed explicitly and that it needed to match what was passed at initial auth.  The sentence that I started this thread with implies that as long as the initial auth included that scope that this function would also return the tokens.

**Comment by ryandary** [comment]
The fact that the exception is thrown seems to suggest that the internal implementation also makes expectations that are based on state rather than on simply passed-in values.

**Comment by poovamraj** [comment]
Can you share the exception that you are referring to here?

**Comment by ryandary** [comment]
Here is a snippet.  This is caused by calling renewAuth on AuthenticationAPIClient without using the addParameter and passing the scope and the initial auth was called by passing the scope "openid email offline_access".

Caused by: com.auth0.android.Auth0Exception: Something went wrong
	at com.auth0.android.authentication.AuthenticationAPIClient$Companion$createErrorAdapter$1.fromException(AuthenticationAPIClient.kt:816)
	... 23 more
Caused by: java.lang.NullPointerException: idToken must not be null
	at com.auth0.android.request.internal.CredentialsDeserializer.deserialize(CredentialsDeserializer.kt:38)

The point of interest is the **idToken must not be null** portion.

**Comment by poovamraj** [comment]
@ryandary we have added a fix to this. Thanks a lot for raising this to us :) This should be released soon.
