### ISSUE TITLE
WebAuthProvider onSuccess callback is not called on some devices

### ISSUE THREAD

**Issue by nininea** [auth0/Auth0.Android#656]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using pretty simple code base here from sdk
```
`    WebAuthProvider.login(account)
            .withScheme(getString(R.string.com_auth0_schema))
            .withScope(AUTH_SCOPE)
            .start(this, object : Callback<Credentials, AuthenticationException> {
                override fun onSuccess(result: Credentials) {
                    viewModel.signInSucceeded(result.accessToken, result.refreshToken)
                }

                override fun onFailure(error: AuthenticationException) {
                    Timber.d(error)
                    viewModel.signInFailed(error.getDescription())
                }
            })`
```
            
 if I open auth page on Samsung devices , android 11 or android 12, redirect does nothing. On other tested devices it works fine. So all configuration staff it correct and works, but app link issue is on Samsung devices. 
           
           Pretty crucial situation, any suggestion from your side ?

### Reproduction

1. paste same code in your activity
2. run it on samsung device with android 11 or android 12 
3. after success log in nothing happens, you will stay in browser 

### Auth0.Android version

2.9.0

### Android version(s)

11/12

**Comment by poovamraj** [comment]
@nininea I just checked it on a Samsung device running 13 and it worked. Can you share the screen recording of this and also see if there is any error reported in the Chrome console https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by nininea** [comment]
yes, on android 13 it works fine for me as well

**Comment by nininea** [comment]
sharing screen recording 
https://github.com/auth0/Auth0.Android/assets/82098854/9445afc4-3abd-4119-b3f1-7b755916561c

**Comment by poovamraj** [comment]
I am not sure what is happening at 5-7 seconds as the popup to redirect app is shown after that. Also any chance you can check the console logs from Chrome using the feature I linked above?

Another thing that can be done to debug is to use our sample app - https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt and try to reproduce this issue. If it does reproduce, please share the repo with us and we can take a look into it.

**Comment by poovamraj** [comment]
@nininea any luck reproducing this in our sample repo?

**Comment by nininea** [comment]
hey @poovamraj  it was not my device, there we reproduced this issue. will update you pretty soon. 

at 5-7 seconds user opens url in chrome (from application), instead of default browser and redirection works from there, chooser is shown (android 11) device is : Samsung Galaxy A52, running android 11.

**Comment by poovamraj** [comment]
Hi @nininea so if I understand this right, you are mentioning that the issue is because the chooser is shown? If so, can you run this command `adb shell dumpsys package r` and show us the result you get for your package name

**Comment by nininea** [comment]
I have updated `sdk version to 2.9.3`
I'm facing this issue on my Samsung galaxy s21, redirection is not working only on my device

```
[com.mypackage.app]
    1685465658061: "Ver":"7603", "Session":"0", "Write":"43", "Verifing":"1329", "Verified":"1500", "Commit":"0", "end":
    "7686"}, 

```

**Comment by nininea** [comment]
there is definitely a problem on samsung devices :(  have no idea how to debug more, everything seems correct, but redirect activity is not opening . 

I have the same issue on` sdk 2.9.0 and 2.9.3.`


> onNewIntent is not called from samsung device, as it happens in normal cases.
But if I click same link in my mobile , onNewIntent is called.

<img width="533" alt="Screenshot 2023-05-31 at 12 24 14" src="https://github.com/auth0/Auth0.Android/assets/82098854/cfa5a482-0480-4922-885c-00c4ec3af995">

 So it's happening while redirection 

![Screenshot 2023-05-31 at 12 39 32](https://github.com/auth0/Auth0.Android/assets/82098854/ab911cd4-a9e9-4569-afc2-c07842f5bc4e)

**Comment by nininea** [comment]
Last final update: I removed samsung internet and app using chrome  instead, it works fine for now. But not solution for sure :/

**Comment by poovamraj** [comment]
@nininea happy that custom scheme worked for you. If you want to debug further and use `https` scheme, we can try App Links. Please comment here and we can reopen this issue. Thanks.
