### ISSUE TITLE
Should `SocketException` be considered a network exception 

### ISSUE THREAD

**Issue by bennycao** [auth0/Auth0.Android#657]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

the `isNetworkError` property on AuthenticationException currently defines a network error who's exception is a `NetworkErrorException`, `UnknownHostException` or `SocketTimeoutException` . 

Should `SocketException` also be checked and marked as a network error ? We don't log network errors, but a lot of `java.net.SocketException: Connection reset` fall through and get logged.

### Describe the ideal solution

`SocketException` considered a network error

**Comment by poovamraj** [comment]
@bennycao This has been fixed in this release - https://github.com/auth0/Auth0.Android/releases/tag/2.9.3. Hope this helps. Thanks for your feedback and keep it coming 💪
