### ISSUE TITLE
java.lang.SecurityException: Permission Denial: starting Intent  being thrown when starting auth page

### ISSUE THREAD

**Issue by bennycao** [auth0/Auth0.Android#663]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In our bug monitoring we are seeing uses receiving `java.lang.SecurityException: Permission Denial: starting Intent` exceptions which causes a crash. Full stack trace below
```
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://login..../... cmp=team.opay.pay/com.opay.webview.WebFoundationActivity (has extras) } from ProcessRecord{79a1d4e 32017:au..../u0a127} (pid=32017, uid=10127) not exported from uid 10099
        at android.os.Parcel.readException(Parcel.java:2013)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4492)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy2.startActivity(Unknown:-1)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4502)
        at android.app.Activity.startActivityForResult(Activity.java:4460)
        at android.app.Activity.startActivity(Activity.java:4821)
        at android.app.Activity.startActivity(Activity.java:4789)
        at com.auth0.android.provider.CustomTabsController.launchAsDefault(CustomTabsController.java:147)
        at com.auth0.android.provider.CustomTabsController.lambda$launchUri$0(CustomTabsController.java:129)
        at com.auth0.android.provider.CustomTabsController.$r8$lambda$_YrKtXm9P1FQ2YfgJXMvohV1xz0(CustomTabsController.java:1)
        at com.auth0.android.provider.CustomTabsController$$InternalSyntheticLambda$1$0913a647ebce4bd91e86469924f1ce077256f4822b38cc89dc9281c0bbe5dfa9$0.run(CustomTabsController:9)
        at java.lang.Thread.run(Thread.java:764)
```

My understanding is that `team.opay.pay/com.opay.webview.WebFoundationActivity` which users could have on their phone is hijacking the opening of `https` requests, in this case to out auth0 login url `https://login....`.

Is there a way to force auth0 to handle `https` schemes or at least be a default choice. By adding `<category android:name="android.intent.category.DEFAULT" />` to `AuthenticationActivity` intent ?

### Reproduction

couldn't reproduce

### Auth0.Android version

2.9.1

### Android version(s)

.

**Comment by poovamraj** [comment]
@bennycao is this happening when the browser is opened or after the login is successful (i.e) is the URL login URL or callback URL

The suggestions I can think of are
If it is callback URL:
- Can you use custom schemes? That is the recommended way to handle callback.
- Can you try using App Links so that your app is used to open the callback URL

If it is login URL:
- Can you try using the `BrowserPicker` API we provide to select a preferred browser?

Do let us know as this is something we would like to avoid

**Comment by bennycao** [comment]
> @bennycao is this happening when the browser is opened or after the login is successful (i.e) is the URL login URL or callback URL
> 
> The suggestions I can think of are If it is callback URL:
> 
>     * Can you use custom schemes? That is the recommended way to handle callback.
> 
>     * Can you try using App Links so that your app is used to open the callback URL
> 
> 
> If it is login URL:
> 
>     * Can you try using the `BrowserPicker` API we provide to select a preferred browser?
> 
> 
> Do let us know as this is something we would like to avoid for all our users.

@poovamraj As i understand it, it is when opening the login url. The configuration of the scheme for your `AuthenticationActivity` handles the intent for `https` scheme.
What i believe is happening is the application for `team.opay.pay/com.opay.webview.WebFoundationActivity` is also configured to handle `https` scheme. And it is chosen to open `https://login....` . 
Therefore it is not an issue with picking a browser, but which application handles the intent.
I could be wrong and misunderstanding this also...

Can the intent-filter configuration for AuthenticationActivity be tightened and be more specific with a host or  category <category android:name="android.intent.category.DEFAULT" /> ?

**Comment by poovamraj** [comment]
@bennycao so it looks like you are trying to open the Login URL (Universal Login Page) and there is some other app that is set as the default browser and doesn't seem to have `exported` set to true. 

The preferred browser is a mechanism where you can particularly specify the browser you would choose. If you choose Chrome here, then the app wouldn't be able to take preference over it. 

The configuration you are mentioning are to receive the callback URL and the best way for that are app links and custom scheme. But the case for us here seem to be the login URL (please verify this is not the callback URL in your logs).

**Comment by bennycao** [comment]
> @bennycao so it looks like you are trying to open the Login URL (Universal Login Page) and there is some other app that is set as the default browser and doesn't seem to have `exported` set to true.
> 
> The preferred browser is a mechanism where you can particularly specify the browser you would choose. If you choose Chrome here, then the app wouldn't be able to take preference over it.
> 
> The configuration you are mentioning are to receive the callback URL and the best way for that are app links and custom scheme. But the case for us here seem to be the login URL (please verify this is not the callback URL in your logs).

It's definitely is the login URL as `act=https://login....` as we have configured the callback with a scheme set to `android://....`.
In terms of the `BrowserPicker` api, not sure what we would do differently than what is by default. And based on the warning here https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/provider/CustomTabsOptions.java#L157 not sure it is what we want to do

**Comment by poovamraj** [comment]
Unfortunately that is the only way ahead to fix this. The SDK is working as intended and the user has a non browser app set to open. We can educate the user about this depending on the exception but there wouldn't be a way ahead for us.

**Comment by poovamraj** [comment]
We will close this issue as it can't be handled on our end. Feel free to comment here and we can reopen it.
