### ISSUE TITLE
CredentialManager getCredentials returning stale credentials.

### ISSUE THREAD

**Issue by shariqislam786** [auth0/Auth0.Android#668]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In version 2.8.0 a change [Pull Request #572](https://github.com/auth0/Auth0.Android/pull/572)  was introduced, where we are now checking only accessToken expiry to refresh crendentials, However we were previously using minimum of id token expiry and access token expiry.

The problem this introduces is that getCredentials call is returning stale (expired) id token if the access token is still valid. And there is also no method in CredentialManager to refresh the idToken if we detect ourselves that id token has expired. The only way of doing it is to Manually get new Credentials using the refreshToken stored in Credential Manager and then call saveCredentials. This kind of Goes again the functionality of the auto refresh capability of Credential Manager. 

IMO this should either be reverted to its old behaviour or We should provide a flag somewhere which can tell the credential manager to perform cache refresh on id token expiry.

### Reproduction

1. Set the id token expiration to a low number like 1-2 minutes in app settings on auth0 portal.
2. Use the Auth0 Sample app.
3. Declare a CredentialManager object in LoginActivity as shown in this page https://auth0.com/docs/libraries/auth0-android/auth0-android-save-and-renew-tokens.
4. Use above declared and call CredentialManager.saveCredentials to save the credentials in Shared Prefs onSuccessfull Auth. 
5. Also declare CredentialManager object in MainActivity similar to LoginActivity.
6. Add a refresh button to MainActivity and in its listener call CredentialManager.getCredentials.
7. click refresh button after the supposed expiry as per step 1.
8. In the debugger you can see the Credentials object returned has an id token which is expired. And there is no method or flag you can call/use to fix it unless you refresh the credentials manually and re-save them.

If you perform the same steps for library versions below 2.8.0 the getCredentials never return expired credentials.

### Auth0.Android version

2.8.0

### Android version(s)

12

**Comment by ASKabanets** [comment]
Noticed the same behavior on `2.9.3`

**Comment by shariqislam786** [comment]
@poovamraj I am passing these ID tokens to our back-end when making any http call as Auth mechanism. Which i am validating later for signature, expiry, issuer, audience and also validating if the call that has come to backend is for the same user for which the token is generated for email based, So that you cannot alter anyone else's data using someone else's token. With an ID token i am able to achieve this without making a server call to Auth0. By fetching the public key and reusing to validate signature of the token. And if i have a valid signature then I am trusting all the data in the token.

I am ok with the forceRefresh, But couldn't find it in the CredentialManager code or an example on how to do it Can you please help me to find if there is one?

**Comment by shariqislam786** [comment]
FYI! Found the force refresh option.
