### ISSUE TITLE
adding auth0.android library to project increases proguard time

### ISSUE THREAD

**Issue by iLona-Karpova** [auth0/Auth0.Android#675]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Adding to the project
implementation 'com.auth0.android:auth0:2.9.3'
increases Proguard time and resources consume.
Without auth0 library build takes 3 minutes. With auth0 library build takes 16 minutes and sometimes leads to crashes. Here is the log:
"Daemon worker" #21 prio=5 os_prio=31 cpu=274810,44ms elapsed=387,95s tid=0x000000012d00c000 nid=0xa203 runnable [0x000000016fd83000] java.lang.Thread.State: RUNNABLE at proguard.classfile.ProgramClass.getString(ProgramClass.java:188) at proguard.classfile.constant.ClassConstant.getName(ClassConstant.java:78) at proguard.classfile.ProgramClass.getClassName(ProgramClass.java:212) at proguard.classfile.ProgramClass.getName(ProgramClass.java:161) at proguard.classfile.visitor.ClassNameFilter.visitProgramClass(ClassNameFilter.java:126) at proguard.classfile.ProgramClass.accept(ProgramClass.java:430) at proguard.classfile.ClassPool.classesAccept(ClassPool.java:125) at proguard.classfile.visitor.AllClassVisitor.visitClassPool(AllClassVisitor.java:45) at proguard.classfile.visitor.MultiClassPoolVisitor.visitClassPool(MultiClassPoolVisitor.java:85) at proguard.classfile.visitor.ClassPoolClassVisitor.visitProgramClass(ClassPoolClassVisitor.java:62) at proguard.classfile.visitor.MultiClassVisitor.visitProgramClass(MultiClassVisitor.java:67) at proguard.classfile.visitor.ClassNameFilter.visitProgramClass(ClassNameFilter.java:128) at proguard.classfile.ProgramClass.accept(ProgramClass.java:430) at proguard.classfile.ClassPool.classesAccept(ClassPool.java:125) at proguard.classfile.visitor.AllClassVisitor.visitClassPool(AllClassVisitor.java:45) at proguard.classfile.visitor.MultiClassPoolVisitor.visitClassPool(MultiClassPoolVisitor.java:85) at proguard.classfile.visitor.MultiClassPoolVisitor.visitClassPool(MultiClassPoolVisitor.java:85) at proguard.classfile.ClassPool.accept(ClassPool.java:111) at proguard.DescriptorKeepChecker.checkClassSpecifications(DescriptorKeepChecker.java:84) at proguard.Initializer.execute(Initializer.java:305) at proguard.ProGuard.initialize(ProGuard.java:285) at proguard.ProGuard.execute(ProGuard.java:114)

### Reproduction

add 
implementation 'com.auth0.android:auth0:2.9.3'
to the build.gradle

### Auth0.Android version

2.9.3

### Android version(s)

compileSdkVersion 33

**Comment by poovamraj** [comment]
@iLona-Karpova we are not able to reproduce this in the sample app. Can you provide a reproducible sample?

**Comment by poovamraj** [comment]
@iLona-Karpova we will close this issue due to inactivity. Feel free to comment here and we can reopen the issue.
