### ISSUE TITLE
NullPointException in OAuthManager

### ISSUE THREAD

**Issue by MarcusCwl** [auth0/Auth0.Android#681]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi team

We recently found the Auth0 SDK contributing crash 

Please check line 204 of OAuthManager

In the function `AssertNoError`
The SDK forces an optional argument `errorDescription` as non-null which causes the NPE.

```
//Helper Methods
    @Throws(AuthenticationException::class)
    private fun assertNoError(errorValue: String?, errorDescription: String?) {
        if (errorValue == null) {
            return
        }
        ...
        ...
        when {
            ...
            ERROR_VALUE_UNAUTHORIZED.equals(errorValue, ignoreCase = true) -> {
                //Should not force errorDescription non-null
                throw AuthenticationException(ERROR_VALUE_UNAUTHORIZED, errorDescription!!)
            }
           ...
           ...
        }
    }
```

Please help check and fix.

### Reproduction

Just start Application

### Additional context

We already report this issues but not get resolved.
And the number is quite high. Please help fix it asap.

### Auth0.Android version

2.9.3

### Android version(s)

7-13

**Comment by poovamraj** [comment]
@MarcusCwl this issue should be fixed in our latest version. Can you check it out and let us know if it still reproduces?

**Comment by poovamraj** [comment]
This has been fixed in the latest version so we are closing this issue now.
