### ISSUE TITLE
Force login with login prompt

### ISSUE THREAD

**Issue by johnnyzen** [auth0/Auth0.Android#683]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

What has happened to prompt=login? The documentation page is 404? https://auth0.com/docs/login/max-age-reauthentication

I am trying to prevent auto login when using WebAuthProvider.login as multiple users are sharing same device.

Thanks

### Reproduction

WebAuthProvider.login(account).withOrganization(getString(R.string.com_auth0_organisation))

### Auth0.Android version

2.9.3

### Android version(s)

13

**Comment by poovamraj** [comment]
@johnnyzen You can see the sample below

```
val credentials = WebAuthProvider.login(account)
                .withParameters(mapOf("prompt" to "login"))
                .await(requireContext())
```
