### ISSUE TITLE
renewAuth cannot refresh access token/id token

### ISSUE THREAD

**Issue by ritdaw** [auth0/Auth0.Android#69]
I'm trying to test renewing with a refresh token.

```
        client.renewAuth(AccountManager.getCredentials(this).getRefreshToken())
                .addParameter("scope", "openid profile email")
                .start(authenticationCallback);
```
But getting either of the below errors in the onFailure callback.
Grant not found, cannot refresh access token
Unsupported grant type: refresh_token

Account > Advanced > OAuth 2.0 API Authorization is turned on.

Any thoughts?

**Comment by ritdaw** [comment]
Since posting this, onSuccess is now getting called but the credentials object is only populating the access token and not the id token.

**Comment by lbalmaceda** [comment]
Hi @ritdaw 
As you're using the client with the OIDCConformant flag on false (default value) you'll need to exchange the refresh_token by calling `client.delegationWithRefreshToken(string)`. This will be done automatically (depending on the flag's value) when this PR https://github.com/auth0/Auth0.Android/pull/68 gets merged.

**Comment by ritdaw** [comment]
Thanks, worked that out in the end!
