### ISSUE TITLE
Cookie not cleared after logout

### ISSUE THREAD

**Issue by nimithar** [auth0/Auth0.Android#704]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The docs mention that calling WebAuthProvider.logout() would remove the cookie set by the browser at authentication time, but after logging out, I am able to login without having to re-enter my credentials for a few minutes after logging out.

### Reproduction

1. Login via SSO -> redirected to the IdP -> enter user credentials -> logged in
2. Logout
3. Login via SSO -> user is logged into the app without having to re-enter credentials

### Auth0.Android version

2.10.2

### Android version(s)

13.6

**Comment by poovamraj** [comment]
@nimithar Please check out the documentation on logging out from IdPs here - https://auth0.com/docs/authenticate/login/logout/log-users-out-of-idps

You have to pass the `federated` parameter and the logout is supported only by select IdPs. Hope this helps. We will close this issue now but feel free to comment here and we can reopen this issue if required.
