### ISSUE TITLE
NPE in AuthenticationActivity.kt:72

### ISSUE THREAD

**Issue by asif1189** [auth0/Auth0.Android#749]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,
We are using `com.auth0.android:auth0:2.10.1` version of library & we are getting Null Pointer Exceptions in AuthenticationActivity. Below are the Crashlytics logs that we are getting.

```
com.auth0.android.provider.AuthenticationActivity.launchAuthenticationIntent (AuthenticationActivity.kt:72)
com.auth0.android.provider.AuthenticationActivity.onResume (AuthenticationActivity.kt:50)
android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1412)
android.app.Activity.performResume (Activity.java:7300)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3814)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3854)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```
Looks like this issue is related to this issue #137

### Reproduction

We are not able to reproduce this issue on our end but we are getting Crashlytics logs on a daily basis.

<img width="1423" alt="Screenshot 2024-07-05 at 5 44 33 PM" src="https://github.com/auth0/Auth0.Android/assets/152283145/d339c224-d97b-4872-b2d2-dc75334cd06c">

### Auth0.Android version

2.10.1

### Android version(s)

Android 9 (88%)

**Comment by desusai7** [comment]
Hi @asif1189,

We will look into this and get back to you.

**Comment by asif1189** [comment]
Hi @desusai7,

Any updates on this issue ?

**Comment by asif1189** [comment]
Hey @desusai7,

Did you get a chance to look into this issue ? 
It's still impacting a lot of users & is the top crash in our crashlytics dashboard.

**Comment by pmathew92** [comment]
Closing this as it is handled in https://github.com/auth0/Auth0.Android/pull/759
