### ISSUE TITLE
AuthenticationException.getDescription() has reversed if-logic

### ISSUE THREAD

**Issue by joknu1** [auth0/Auth0.Android#755]
### Checklist

- [X] The issue can be reproduced in the [Auth0.Android sample app](https://github.com/auth0-samples/auth0-android-sample/tree/master/00-Login-Kt) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.Android#readme), [Examples](https://github.com/auth0/Auth0.Android/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/auth0/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In `com.auth0.android.authentication.AuthenticationException` there is a function:

```
    public fun getDescription(): String {
        if (!TextUtils.isEmpty(description)) {
            return description!!
        }
        return if (UNKNOWN_ERROR == getCode()) {
            String.format("Received error with code %s", getCode())
        } else "Failed with unknown error"
    }
```
where I would expect latter `if` to check for non-equal `UNKNOWN_ERROR != getCode()` instead.

### Reproduction

1. Open `AuthenticationException`
2. Check logic of `getDescription()`

### Auth0.Android version

2.11.0

### Android version(s)

14

**Comment by pmathew92** [comment]
Closing this as this has been fixed as part of 
https://github.com/auth0/Auth0.Android/pull/756
