### ISSUE TITLE
renewAuth doesn't return valid tokens

### ISSUE THREAD

**Issue by charsleysa** [auth0/Auth0.Android#80]
Hi all!

I'm trying to use the new /oauth/token endpoints with the 1.5 version of this library.

I can successfully login and receive correct access_token, id_token, and refresh_token but when I call renewAuth I am not getting back any valid tokens.

I am calling `.setOIDConformant(true);` before any calls to the Auth0 APIs and I have the flag switched on in the Auth0 Management Console for the Android Client.

```java
authClient.renewAuth(credentials.getRefreshToken())
    .addParameter("scope", "opened name email profile tribalId app_metadata offline_access")
    .start(authenticationCallback)
```
The `Credentials` object that I get in the callback has `accessToken` set to what seems to be an old APIv1 token that is 16 characters long and both the `idToken` and `refreshToken` are set to null with the `type` set to `Bearer`.

Any help would be much appreciated.

Cheers!

**Comment by lbalmaceda** [comment]
Hi @charsleysa,
Thanks for the report. This is a known issue and we're working on it. Will let you know when it's fixed.

Cheers

**Comment by lbalmaceda** [comment]
@charsleysa it has been fixed. 👍

**Comment by brassier** [comment]
I'm seeing a similar issue in the Auth0.JS (8.4.0) API.  Any chance the same fix is needed there?
