### ISSUE TITLE
How to add user metadata on custom signup?

### ISSUE THREAD

**Issue by kiaanpillay** [auth0/Auth0.Android#85]
Hi, I am currently trying to add a phone number as custom metadata in my sign up as follows

`    Map<String, Object> metadata = new HashMap<>();
    metadata.put("contact_num", phoneNumber);

  
            authentication
                    .signUp(email, pass,  "Username-Password-Authentication")
                    .setScope("openid role")
                    .addSignUpParameters(metadata)
                    .start(new BaseCallback<Credentials, AuthenticationException>() {`

However this never seems to work. What am I doing wrong? Is this possible?

**Comment by lbalmaceda** [comment]
Hi @kiaanpillay 
The Auth API differentiates creating a user from signing up. The first one just creates the user while the second also logs him in. As the last one has 2 requests, you can set additional parameters for each of them by calling `addAuthenticationParameters` and `addSignUpParameters`.
To set the `user_metadata` you'll need to use that same key when adding the sign up parameters: 

```java
//Define your custom fields
Map<String, Object> metadata = new HashMap<>();
metadata.put("contact_num", phoneNumber);

//Define the sign up parameters, adding the user_metadata
Map<String, Object> params = new HashMap<>();
params.put("user_metadata", metadata);

//Add the sign up parameters to the request
authentication
                .signUp(email, pass,  "Username-Password-Authentication")
                .setScope("openid role")
                .addSignUpParameters(params);
```

Cheers
