### ISSUE TITLE
Error: Missing username parameter

### ISSUE THREAD

**Issue by prazjain** [auth0/Auth0.Android#88]
Hi, I have generated a one time code using AuthenticationAPIClient, and I am calling authAPIClient.loginWithPhoneNumber(phonenumber,code)

But this is failing, and exception says: code = invalid_request description= missing username parameter

Is there something I am missing?
(I am using this library: 'com.auth0.android:auth0:1.6.0')
I have seen that everytime I call generate one time token, it gives me a new token (regardless of whether previous token was used or not, so does this mean user need to pass in latest token received or any of previous unused token can be used).

Scenario: 
1) User generates 1st one time token.
2) Token not received in few mins (sms delivery delays from network provider etc etc).
3) User generates 2nd one time token.
4) User receives 1st one time token.
5) User goes and inputs this 1st one time token to login.
6) Will this token succeed in logging in? or User need to wait for 2nd token to deliver in sms and try that one?

Thanks

**Comment by prazjain** [comment]
I am using API like this:

```
auth0APIClient.loginWithPhoneNumber(phNumber,code).start(new BaseCallback<Credentials, AuthenticationException>() {
            @Override
            public void onSuccess(Credentials payload) {
                logInStatusListener.loginStatus(true,"");
            }

            @Override
            public void onFailure(AuthenticationException error) {
                logInStatusListener.loginStatus(false, error.getMessage());
            }
        });
```

**Comment by prazjain** [comment]
I am using Android client, but someone using web client seems to have resolved it like this:
https://auth0.com/forum/t/solved-error-missing-username-parameter-but-im-not/1546

I do not think I can change from http to https when I am using your library, can I?

**Comment by lbalmaceda** [comment]
Hi @prazjain 
The "username" in this case is the `email` or `phone`. The error states that it's missing. Keep in mind that on the second request you need to use the same `connection name` and `identifier` (email/phone) as in the first one.
A new token is generated every time you execute the first request, that's fine. The previous token might be used in the short time but I can't answer how long does it last. You'll have to search/ask [here](https://support.auth0.com/). 

Check the readme as it shows a sample on how to log in using passwordless with email. The steps are similar to SMS. -> https://github.com/auth0/auth0.android#passwordless-login
