### ISSUE TITLE
Custom UI and passwordless login(Phone no + code): Authentication failure

### ISSUE THREAD

**Issue by erzohrakhan** [auth0/Auth0.Android#91]
My code was working fine for 1.4.0 library. Then I upgraded to 1.7 0 library and authentication failed but now when again I degraded to  auth 1.4.0 library. Authentication is still failing 
Failed to request a passwordless Code/Link: An error occurred when trying to authenticate with the server.
                                                                   com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
                                                                       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:23)
                                                                       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:9)
                                                                       at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:137)
                                                                       at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:68)
                                                                       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by lbalmaceda** [comment]
Hi @erzohrakhan 
Please enable Http logging by calling `auth0.setLoggingEnabled(true)` in your Auth0 instance, before calling any of the API methods, or put a breakpoint on the `BaseRequest#parseUnsuccessfulResponse` method to see what the response from the server was.

**Comment by erzohrakhan** [comment]
Hi Luciano,
Thanks for replying.
debugger output:
response = {Response@5506} "Response{protocol=http/1.1, code=500,
message=Internal Server Error, url=https://erzohrakhan.auth0.com/oauth/ro}"
 body = {RealResponseBody@5521}
 cacheControl = null
 cacheResponse = null
 code = 500
 handshake = {Handshake@5522}
 headers = {Headers@5523} "Date: Mon, 24 Apr 2017 18:04:45
GMT\nContent-Type: application/json; charset=utf-8\nContent-Length:
140\nConnection: keep-alive\nKeep-Alive: timeout=100\nX-Auth0-RequestId:
c6eed996e80460f9b918\nX-RateLimit-Limit: 100\nX-RateLimit-Remaining:
99\nX-RateLimit-Reset: 1493057950\nset-cookie:
auth0=s%3Azlkv3aLG94i8MDw6XP9sX0eFfB2sm49L.u3SQGYDcFdQKvE9cVdxqF44X4JImeK0PezRak4qiuEs;
Path=/; Expires=Thu, 27 Apr 2017 18:04:45 GMT; HttpOnly;
Secure\nCache-Control: no-cache\nOkHttp-Sent-Millis:
1493057085404\nOkHttp-Received-Millis: 1493057086144\n"
 message = "Internal Server Error"
  count = 21
  hashCode = 0
  shadow$_klass_ = {Class@3811} "class java.lang.String"
  shadow$_monitor_ = -1977963323
 networkResponse = {Response@5525} "Response{protocol=http/1.1, code=500,
message=Internal Server Error, url=https://erzohrakhan.auth0.com/oauth/ro}"
  body = null
  cacheControl = null
  cacheResponse = null
  code = 500
  handshake = {Handshake@5522}
  headers = {Headers@5547} "Date: Mon, 24 Apr 2017 18:04:45
GMT\nContent-Type: application/json; charset=utf-8\nContent-Length:
140\nConnection: keep-alive\nKeep-Alive: timeout=100\nX-Auth0-RequestId:
c6eed996e80460f9b918\nX-RateLimit-Limit: 100\nX-RateLimit-Remaining:
99\nX-RateLimit-Reset: 1493057950\nset-cookie:
auth0=s%3Azlkv3aLG94i8MDw6XP9sX0eFfB2sm49L.u3SQGYDcFdQKvE9cVdxqF44X4JImeK0PezRak4qiuEs;
Path=/; Expires=Thu, 27 Apr 2017 18:04:45 GMT; HttpOnly;
Secure\nCache-Control: no-cache\nOkHttp-Sent-Millis:
1493057085404\nOkHttp-Received-Millis: 1493057086144\n"
  message = "Internal Server Error"
  networkResponse = null
  priorResponse = null
  protocol = {Protocol@5526} "http/1.1"
  request = {Request@5548} "Request{method=POST, url=
https://erzohrakhan.auth0.com/oauth/ro, tag=Request{method=POST, url=
https://erzohrakhan.auth0.com/oauth/ro, tag=null}}"

I have attached logcat.

Thanks,
Zohra

**Comment by erzohrakhan** [comment]
App measurement is starting up, version: 10298
04-24 23:34:02.453 29923-29923/in.eventloop.heylo I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-24 23:34:02.486 29923-29923/in.eventloop.heylo V/FA: Collection enabled
04-24 23:34:02.486 29923-29923/in.eventloop.heylo V/FA: App package, google app id: in.eventloop.heylo, 1:332194766264:android:ff50b5a2ad2932ed
04-24 23:34:02.486 29923-29923/in.eventloop.heylo I/FA: To enable faster debug mode event logging run:
                                                          adb shell setprop debug.firebase.analytics.app in.eventloop.heylo
04-24 23:34:02.486 29923-29923/in.eventloop.heylo D/FA: Debug-level message logging enabled
04-24 23:34:02.598 29923-29923/in.eventloop.heylo V/FA: Registered activity lifecycle callback
04-24 23:34:02.601 29923-29923/in.eventloop.heylo I/FirebaseInitProvider: FirebaseApp initialization successful
04-24 23:34:02.610 29923-30205/in.eventloop.heylo V/FA: Using measurement service
04-24 23:34:02.611 29923-30205/in.eventloop.heylo V/FA: Connecting to remote service
04-24 23:34:02.623 29923-29923/in.eventloop.heylo I/InstantRun: starting instant run server: is main process
04-24 23:34:02.858 29923-29923/in.eventloop.heylo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-24 23:34:03.185 29923-29923/in.eventloop.heylo V/FA: onActivityCreated
04-24 23:34:03.513 29923-29923/in.eventloop.heylo D/LoginActivity: Country Code +91
04-24 23:34:03.516 29923-29923/in.eventloop.heylo D/LoginActivity: Receiver regd
04-24 23:34:03.521 29923-30205/in.eventloop.heylo V/FA: Using measurement service
04-24 23:34:03.521 29923-30205/in.eventloop.heylo V/FA: Connection attempt already in progress
04-24 23:34:03.522 29923-30205/in.eventloop.heylo V/FA: Activity resumed, time: 80451695
04-24 23:34:03.532 29923-30227/in.eventloop.heylo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-24 23:34:03.559 29923-30205/in.eventloop.heylo D/FA: Connected to remote service
04-24 23:34:03.559 29923-30205/in.eventloop.heylo V/FA: Processing queued up service tasks: 2
04-24 23:34:03.680 29923-30227/in.eventloop.heylo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-24 23:34:03.685 29923-30227/in.eventloop.heylo I/OpenGLRenderer: Initialized EGL, version 1.4
04-24 23:34:03.844 29923-29923/in.eventloop.heylo W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
04-24 23:34:08.665 29923-30205/in.eventloop.heylo V/FA: Inactivity, disconnecting from the service
04-24 23:34:18.829 29923-29923/in.eventloop.heylo D/LoginActivity: user mobile no+919482529771
04-24 23:34:21.023 29923-30699/in.eventloop.heylo D/OkHttp: --> POST https://erzohrakhan.auth0.com/passwordless/start HTTP/1.1
04-24 23:34:21.033 29923-30699/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-24 23:34:21.034 29923-30699/in.eventloop.heylo D/OkHttp: Content-Length: 112
04-24 23:34:21.035 29923-30699/in.eventloop.heylo D/OkHttp: Auth0-Client: eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsInZlcnNpb24iOiIxLjcuMCJ9
04-24 23:34:21.035 29923-30699/in.eventloop.heylo D/OkHttp: Accept-Language: en_US
04-24 23:34:21.088 29923-30699/in.eventloop.heylo D/OkHttp: {"client_id":"gl46Lk0Pw0LQWN3VDJd9lPjb50PgA9I0","send":"code","phone_number":"+919482529771","connection":"sms"}
04-24 23:34:21.089 29923-30699/in.eventloop.heylo D/OkHttp: --> END POST (112-byte body)
04-24 23:34:21.104 29923-29923/in.eventloop.heylo I/Choreographer: Skipped 136 frames!  The application may be doing too much work on its main thread.
04-24 23:34:22.285 29923-29923/in.eventloop.heylo I/Choreographer: Skipped 58 frames!  The application may be doing too much work on its main thread.
04-24 23:34:31.921 29923-30699/in.eventloop.heylo D/OkHttp: <-- HTTP/1.1 200 OK (10829ms)
04-24 23:34:31.930 29923-30699/in.eventloop.heylo D/OkHttp: Date: Mon, 24 Apr 2017 18:04:31 GMT
04-24 23:34:31.931 29923-30699/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-24 23:34:31.932 29923-30699/in.eventloop.heylo D/OkHttp: Content-Length: 115
04-24 23:34:31.932 29923-30699/in.eventloop.heylo D/OkHttp: Connection: keep-alive
04-24 23:34:31.933 29923-30699/in.eventloop.heylo D/OkHttp: Keep-Alive: timeout=100
04-24 23:34:31.934 29923-30699/in.eventloop.heylo D/OkHttp: X-Auth0-RequestId: 33a023d1fa11291fe7b4
04-24 23:34:31.934 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Limit: 50
04-24 23:34:31.935 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Remaining: 49
04-24 23:34:31.935 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Reset: 1493057143
04-24 23:34:31.936 29923-30699/in.eventloop.heylo D/OkHttp: Cache-Control: no-cache
04-24 23:34:31.944 29923-30699/in.eventloop.heylo D/OkHttp: Strict-Transport-Security: max-age=15724800
04-24 23:34:31.945 29923-30699/in.eventloop.heylo D/OkHttp: X-Robots-Tag: noindex, nofollow, nosnippet, noarchive
04-24 23:34:31.953 29923-30699/in.eventloop.heylo D/OkHttp: OkHttp-Sent-Millis: 1493057070818
04-24 23:34:31.954 29923-30699/in.eventloop.heylo D/OkHttp: OkHttp-Received-Millis: 1493057071903
04-24 23:34:31.969 29923-30699/in.eventloop.heylo D/OkHttp: {"_id":"5869623398420f9a11acf430","phone_number":"+919482529771","request_language":"en_US","phone_verified":false}
04-24 23:34:31.973 29923-30699/in.eventloop.heylo D/OkHttp: <-- END HTTP (115-byte body)
04-24 23:34:32.032 29923-29923/in.eventloop.heylo D/LoginActivity: onSuccess received in callback
04-24 23:34:35.908 29923-29923/in.eventloop.heylo V/LoginActivity: Recvd SMS Broadcast receiver
04-24 23:34:35.908 29923-29923/in.eventloop.heylo D/LoginActivity: Onreceive Called
04-24 23:34:36.620 29923-29923/in.eventloop.heylo D/LoginActivity: Address: +14153476902getDisplay: Sent from your Twilio trial account - Your Heylo verification code is: 725449get Message Sent from your Twilio trial account - Your Heylo verification code is: 725449
04-24 23:34:36.621 29923-29923/in.eventloop.heylo D/LoginActivity: code 725449
04-24 23:34:45.342 29923-30699/in.eventloop.heylo D/OkHttp: --> POST https://erzohrakhan.auth0.com/oauth/ro HTTP/1.1
04-24 23:34:45.343 29923-30699/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-24 23:34:45.344 29923-30699/in.eventloop.heylo D/OkHttp: Content-Length: 155
04-24 23:34:45.345 29923-30699/in.eventloop.heylo D/OkHttp: Auth0-Client: eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsInZlcnNpb24iOiIxLjcuMCJ9
04-24 23:34:45.346 29923-30699/in.eventloop.heylo D/OkHttp: Accept-Language: en_US
04-24 23:34:45.349 29923-30699/in.eventloop.heylo D/OkHttp: {"password":"725449","scope":"openid","client_id":"gl46Lk0Pw0LQWN3VDJd9lPjb50PgA9I0","username":"+919482529771","connection":"sms","grant_type":"password"}
04-24 23:34:45.351 29923-30699/in.eventloop.heylo D/OkHttp: --> END POST (155-byte body)
04-24 23:34:45.352 29923-29923/in.eventloop.heylo I/Choreographer: Skipped 96 frames!  The application may be doing too much work on its main thread.
04-24 23:34:46.159 29923-30699/in.eventloop.heylo D/OkHttp: <-- HTTP/1.1 500 Internal Server Error (803ms)
04-24 23:34:46.161 29923-30699/in.eventloop.heylo D/OkHttp: Date: Mon, 24 Apr 2017 18:04:45 GMT
04-24 23:34:46.164 29923-30699/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-24 23:34:46.165 29923-30699/in.eventloop.heylo D/OkHttp: Content-Length: 140
04-24 23:34:46.166 29923-30699/in.eventloop.heylo D/OkHttp: Connection: keep-alive
04-24 23:34:46.167 29923-30699/in.eventloop.heylo D/OkHttp: Keep-Alive: timeout=100
04-24 23:34:46.167 29923-30699/in.eventloop.heylo D/OkHttp: X-Auth0-RequestId: c6eed996e80460f9b918
04-24 23:34:46.168 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Limit: 100
04-24 23:34:46.169 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Remaining: 99
04-24 23:34:46.170 29923-30699/in.eventloop.heylo D/OkHttp: X-RateLimit-Reset: 1493057950
04-24 23:34:46.179 29923-30699/in.eventloop.heylo D/OkHttp: set-cookie: auth0=s%3Azlkv3aLG94i8MDw6XP9sX0eFfB2sm49L.u3SQGYDcFdQKvE9cVdxqF44X4JImeK0PezRak4qiuEs; Path=/; Expires=Thu, 27 Apr 2017 18:04:45 GMT; HttpOnly; Secure
04-24 23:34:46.180 29923-30699/in.eventloop.heylo D/OkHttp: Cache-Control: no-cache
04-24 23:34:46.181 29923-30699/in.eventloop.heylo D/OkHttp: OkHttp-Sent-Millis: 1493057085404
04-24 23:34:46.182 29923-30699/in.eventloop.heylo D/OkHttp: OkHttp-Received-Millis: 1493057086144
04-24 23:34:46.195 29923-30699/in.eventloop.heylo D/OkHttp: {"error":"access_denied","error_description":"Invalid URI \"undefined/users/c21zfDU4Njk2MjMzOTg0MjBmOWExMWFjZjQzMA==.json?auth=undefined\""}
04-24 23:34:46.197 29923-30699/in.eventloop.heylo D/OkHttp: <-- END HTTP (140-byte body)
04-24 23:35:43.909 29923-32362/in.eventloop.heylo V/FA: Recording user engagement, ms: 100372
04-24 23:35:43.919 29923-32362/in.eventloop.heylo V/FA: Using measurement service
04-24 23:35:43.923 29923-32362/in.eventloop.heylo V/FA: Connecting to remote service
04-24 23:35:43.986 29923-32362/in.eventloop.heylo V/FA: Activity paused, time: 80552049
04-24 23:35:44.113 29923-32362/in.eventloop.heylo I/FA: Tag Manager is not found and thus will not be used
04-24 23:35:44.145 29923-32362/in.eventloop.heylo D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=100372, _sc=LoginActivity, _si=5311793151896407155}]
04-24 23:35:44.284 29923-32362/in.eventloop.heylo V/FA: Using measurement service
04-24 23:35:44.285 29923-32362/in.eventloop.heylo V/FA: Connection attempt already in progress
04-24 23:35:44.287 29923-32362/in.eventloop.heylo D/FA: Connected to remote service
04-24 23:35:44.290 29923-32362/in.eventloop.heylo V/FA: Processing queued up service tasks: 2

**Comment by lbalmaceda** [comment]
@erzohrakhan looks like you have some rule configured to modify the login response, am I right? The part that indicates this in the log is:
```
{"error":"access_denied","error_description":"Invalid URI "undefined/users/c21zfDU4Njk2MjMzOTg0MjBmOWExMWFjZjQzMA==.json?auth=undefined""}
```

In `error_description` there are 2 undefined values:
**undefined**/users/c21zfDU4Njk2MjMzOTg0MjBmOWExMWFjZjQzMA==.json?auth=**undefined**

**Comment by erzohrakhan** [comment]
What I am trying to do is  I will get Id token from Auth0 and in turn I
will generate custom token through delegation API call and I will be using
that custom token to integrate with firebase.
I am using auth0 for authentication and firebase as a backend in my app.

**Comment by erzohrakhan** [comment]
When I disabled firebase in my project it is working fine. Plus one more
problem even if I save private key of my project under settings tab of
firebase, and after pressing save button If i come back and check the
private key it is showing some different value. Private key text box is not
getting updated properly.

**Comment by lbalmaceda** [comment]
@erzohrakhan The `access_denied` code indicates that it's a Rule error (not auth0.android related). It seems that 2 values are `undefined` when you build that URL. I suggest you check those variables values or hardcode them to try to debug it.
About the private key field, i guess it needs a valid certificate/key value and because it acts as a secret/password it might get obfuscated or removed so you can't get it back once you set it.

**Comment by erzohrakhan** [comment]
Auth0 auth0 = //create account
AuthenticationAPIClient client = new AuthenticationAPIClient(auth0);
String apiType = "firebase";
String token = //Your Auth0 id_token of the logged in User
client.delegationWithIdToken(token, apiType)
  .start(new BaseCallback<Map<String, Object>, AuthenticationException>() {
        @Override
        public void onSuccess(Map<String, Object> payload) {
            //Your Firebase token will be in payload
        }

        @Override
        public void onFailure(AuthenticationException error) {
            //Delegation call failed
        }
    });



*https://auth0.com/docs/libraries/lock-android/delegation-api
<https://auth0.com/docs/libraries/lock-android/delegation-api> Link states
that I have to use delegation API with two parameters  idtoken and apitype.
As per my understanding this idtoken will be generated by auth0 after
successful authentication. My code was working for 1.4.0 library although
it was failing at mAuth.signwihtcustomtoken but I was able to succcessfully
authenticate. But due to some changes now even authentication is failing
for 1.4.0 library. My code: *apiClient.delegationWithIdToken(tokenId,
apiType)

        .start(new BaseCallback<Map<String, Object>,
AuthenticationException>() {
            @Override
            public void onSuccess(Map<String, Object> payload) {

                mAuth.signInWithCustomToken(payload.get("idToken").toString()).
                        addOnCompleteListener(LoginActivity.this, new
OnCompleteListener<AuthResult>() {
                            @Override
                            public void onComplete(@NonNull
Task<AuthResult> task) {
                                if (task.isSuccessful()) {
                                    Log.d(TAG, "signnwithCustom:success");
                                    FirebaseUser user =
FirebaseAuth.getInstance().getCurrentUser();
                                    launchHomeOrWelcomePage();

                                } else {
                                    //if sign in fails
                                    Log.w(TAG, "sign in with custom
token failed");

                                }

                            }
                        }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        if (e instanceof FirebaseAuthException) {
                            Log.w(TAG, "" + ((FirebaseAuthException)
e).getErrorCode());
                        }
                    }
                });

            }

            @Override
            public void onFailure(AuthenticationException error) {
                Log.e(TAG, "authentication exception  error" +
                        error.getMessage(), error);

            }
        });

https://auth0.com/authenticate/android/firebase step 4 in this link is
not clear. Where do I have to write this command?

curl --data \
 "client_id=YOUR_CLIENT_ID&\
 &grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer\
 &refresh_token=\
 &scope=open_id\
 &api_type=firebase"\
 https://YOUR_ACCOUNT.auth0.com/delegation

**Comment by erzohrakhan** [comment]
Hi Luciano,
Can you please help me in solving this issue? My deadlines are close by and
before that I have to resolve this issue.
Regards,
Zohra
