### ISSUE TITLE
Custom UI and passwordless login(Phone no + SMS): Authentication failure with firebase

### ISSUE THREAD

**Issue by erzohrakhan** [auth0/Auth0.Android#92]
On enabling firebase as a add on auth0 authentication is failing. I have attached logcat.

[adblogcat1.pdf](https://github.com/auth0/Auth0.Android/files/952883/adblogcat1.pdf)

**Comment by hzalaz** [comment]
@erzohrakhan please don't use a pdf and just put the log under the code comment since we won't open any pdf from non-verified sources. 

Also if you need help using auth0 please use https://support.auth0.com since this is not a support channel, its used for issue tracking of the library

**Comment by erzohrakhan** [comment]
Hi Hernan,
I have already raised this issue with support.auth0.com but no body replied.
LogCat:

04-25 00:52:20.866 27145-27334/in.eventloop.heylo D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=1252, _sc=LoginActivity, _si=600150248244876335}]
04-25 00:52:26.211 27145-27334/in.eventloop.heylo V/FA: Inactivity, disconnecting from the service
04-25 00:52:26.665 27145-27334/in.eventloop.heylo V/FA: Using measurement service
04-25 00:52:26.665 27145-27334/in.eventloop.heylo V/FA: Connecting to remote service
04-25 00:52:26.682 27145-27334/in.eventloop.heylo V/FA: Activity resumed, time: 85154839
04-25 00:52:26.714 27145-27334/in.eventloop.heylo D/FA: Connected to remote service
04-25 00:52:26.714 27145-27334/in.eventloop.heylo V/FA: Processing queued up service tasks: 1
04-25 00:52:31.738 27145-27151/in.eventloop.heylo W/art: Suspending all threads took: 10.593ms
04-25 00:52:31.739 27145-27334/in.eventloop.heylo V/FA: Inactivity, disconnecting from the service
04-25 00:52:38.249 27145-27151/in.eventloop.heylo W/art: Suspending all threads took: 6.645ms
04-25 00:52:43.687 27145-27145/in.eventloop.heylo D/LoginActivity: user mobile no+919482529771
04-25 00:52:43.777 27145-27151/in.eventloop.heylo W/art: Suspending all threads took: 16.569ms
04-25 00:52:43.824 27145-28471/in.eventloop.heylo D/OkHttp: --> POST https://erzohrakhan.auth0.com/passwordless/start HTTP/1.1
04-25 00:52:43.824 27145-28471/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-25 00:52:43.824 27145-28471/in.eventloop.heylo D/OkHttp: Content-Length: 112
04-25 00:52:43.824 27145-28471/in.eventloop.heylo D/OkHttp: Auth0-Client: eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsInZlcnNpb24iOiIxLjcuMCJ9
04-25 00:52:43.824 27145-28471/in.eventloop.heylo D/OkHttp: Accept-Language: en_US
04-25 00:52:43.862 27145-28471/in.eventloop.heylo D/OkHttp: {"client_id":"gl46Lk0Pw0LQWN3VDJd9lPjb50PgA9I0","send":"code","phone_number":"+919482529771","connection":"sms"}
04-25 00:52:43.862 27145-28471/in.eventloop.heylo D/OkHttp: --> END POST (112-byte body)
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: <-- HTTP/1.1 200 OK (2505ms)
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Date: Mon, 24 Apr 2017 19:22:45 GMT
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Content-Length: 115
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Connection: keep-alive
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Keep-Alive: timeout=100
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: X-Auth0-RequestId: 89f2d1d5a1446cea7e4a
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Limit: 50
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Remaining: 49
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Reset: 1493061838
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Cache-Control: no-cache
04-25 00:52:46.368 27145-28471/in.eventloop.heylo D/OkHttp: Strict-Transport-Security: max-age=15724800
04-25 00:52:46.369 27145-28471/in.eventloop.heylo D/OkHttp: X-Robots-Tag: noindex, nofollow, nosnippet, noarchive
04-25 00:52:46.369 27145-28471/in.eventloop.heylo D/OkHttp: OkHttp-Sent-Millis: 1493061765338
04-25 00:52:46.369 27145-28471/in.eventloop.heylo D/OkHttp: OkHttp-Received-Millis: 1493061766364
04-25 00:52:46.370 27145-28471/in.eventloop.heylo D/OkHttp: {"_id":"5869623398420f9a11acf430","phone_number":"+919482529771","request_language":"en_US","phone_verified":false}
04-25 00:52:46.370 27145-28471/in.eventloop.heylo D/OkHttp: <-- END HTTP (115-byte body)
04-25 00:52:46.376 27145-27145/in.eventloop.heylo D/LoginActivity: onSuccess received in callback
04-25 00:53:05.815 27145-27145/in.eventloop.heylo V/LoginActivity: Recvd SMS Broadcast receiver
04-25 00:53:05.815 27145-27145/in.eventloop.heylo D/LoginActivity: Onreceive Called
04-25 00:53:05.836 27145-27145/in.eventloop.heylo D/LoginActivity: Address: +14153476902getDisplay: Sent from your Twilio trial account - Your Heylo verification code is: 070628get Message Sent from your Twilio trial account - Your Heylo verification code is: 070628
04-25 00:53:05.836 27145-27145/in.eventloop.heylo D/LoginActivity: code 070628
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: --> POST https://erzohrakhan.auth0.com/oauth/ro HTTP/1.1
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: Content-Length: 155
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: Auth0-Client: eyJuYW1lIjoiQXV0aDAuQW5kcm9pZCIsInZlcnNpb24iOiIxLjcuMCJ9
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: Accept-Language: en_US
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: {"password":"070628","scope":"openid","client_id":"gl46Lk0Pw0LQWN3VDJd9lPjb50PgA9I0","username":"+919482529771","connection":"sms","grant_type":"password"}
04-25 00:53:09.995 27145-28471/in.eventloop.heylo D/OkHttp: --> END POST (155-byte body)
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: <-- HTTP/1.1 500 Internal Server Error (608ms)
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: Date: Mon, 24 Apr 2017 19:23:10 GMT
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: Content-Type: application/json; charset=utf-8
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: Content-Length: 140
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: Connection: keep-alive
04-25 00:53:10.604 27145-28471/in.eventloop.heylo D/OkHttp: Keep-Alive: timeout=100
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: X-Auth0-RequestId: 108c3a5172854767301c
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Limit: 100
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Remaining: 99
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: X-RateLimit-Reset: 1493062655
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: set-cookie: auth0=s%3AjiAUhbJLmx66iKMbJ94oDPKnSjFXCAqP.pSw0GwWudwcIsuaX6Hw3hnhXWj2K6qNlOfg%2Fi%2FFQLPg; Path=/; Expires=Thu, 27 Apr 2017 19:23:10 GMT; HttpOnly; Secure
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: Cache-Control: no-cache
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: OkHttp-Sent-Millis: 1493061790010
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: OkHttp-Received-Millis: 1493061790604
04-25 00:53:10.605 27145-28471/in.eventloop.heylo D/OkHttp: {"error":"access_denied","error_description":"Invalid URI \"undefined/users/c21zfDU4Njk2MjMzOTg0MjBmOWExMWFjZjQzMA==.json?auth=undefined\""}
04-25 00:53:10.606 27145-28471/in.eventloop.heylo D/OkHttp: <-- END HTTP (140-byte body)
04-25 00:53:10.644 27145-28471/in.eventloop.heylo E/LoginActivity: Failed to request a passwordless Code/Link: An error occurred when trying to authenticate with the server.
                                                                   com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
                                                                       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:23)
                                                                       at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:9)
                                                                       at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:137)
                                                                       at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:68)
                                                                       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
When I was working with auth1.4.0 library authentication was working with firebase but now even authentication is failing with auth1.4.0 . Currently I am using auth1.7.0 library 
Auth0 auth0 = //create account
AuthenticationAPIClient client = new AuthenticationAPIClient(auth0);
String apiType = "firebase";
String token = //Your Auth0 id_token of the logged in User
client.delegationWithIdToken(token, apiType)
  .start(new BaseCallback<Map<String, Object>, AuthenticationException>() {
        @Override
        public void onSuccess(Map<String, Object> payload) {
            //Your Firebase token will be in payload        
        }

        @Override
        public void onFailure(AuthenticationException error) {
            //Delegation call failed
        }
    });
https://auth0.com/docs/libraries/lock-android/delegation-api  states that I have to use delegation API with two parameters  idtoken and apitype. As per my understanding this idtoken will be generated by auth0 after successful authentication. My code was working for 1.4.0 library although it was failing at mAuth.signwihtcustomtoken but I was able to succcessfully authenticate. But due to some changes now even authentication is failing for 1.4.0 library.
My code:
 apiClient.delegationWithIdToken(tokenId, apiType)
        .start(new BaseCallback<Map<String, Object>, AuthenticationException>() {
            @Override
            public void onSuccess(Map<String, Object> payload) {

                mAuth.signInWithCustomToken(payload.get("idToken").toString()).
                        addOnCompleteListener(LoginActivity.this, new OnCompleteListener<AuthResult>() {
                            @Override
                            public void onComplete(@NonNull Task<AuthResult> task) {
                                if (task.isSuccessful()) {
                                    Log.d(TAG, "signnwithCustom:success");
                                    FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
                                    launchHomeOrWelcomePage();

                                } else {
                                    //if sign in fails
                                    Log.w(TAG, "sign in with custom token failed");

                                }

                            }
                        }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        if (e instanceof FirebaseAuthException) {
                            Log.w(TAG, "" + ((FirebaseAuthException) e).getErrorCode());
                        }
                    }
                });

            }

            @Override
            public void onFailure(AuthenticationException error) {
                Log.e(TAG, "authentication exception  error" +
                        error.getMessage(), error);

            }
        });
https://auth0.com/authenticate/android/firebase step 4 in this link is not clear. Where do I have to write this command?
curl --data \
 "client_id=YOUR_CLIENT_ID&\
 &grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer\
 &refresh_token=\
 &scope=open_id\
 &api_type=firebase"\
 https://YOUR_ACCOUNT.auth0.com/delegation

**Comment by erzohrakhan** [comment]
Please reopen this issue. Even if we ask questions related to auth0 on stackoverflow we never get reply from auth0 team.
